### ISSUE TITLE
Empty state value when I write nothing.

### ISSUE THREAD

**Issue by johnunclesam** [ckeditor/ckeditor5-react#10]
Is there a way to get empty value when I write nothing?

Example: if I write something and then delete it, `data` is:

`<p>&nbsp;</p>`

And if I use an `Enter` button on my keyboard it is:

`<p>&nbsp;</p><p>&nbsp;</p>`

I need to get nothing really. Empty state like this: `""`.

How to?

**Comment by pomek** [comment]
The issue touches the CKEditor 5 itself, not the React integration. 

I'm leaving a URL to issue where we are discussing it – https://github.com/ckeditor/ckeditor5/issues/401.
