### ISSUE TITLE
Is there a way to provide `name` and `hasError` to the `Editor`?

### ISSUE THREAD

**Issue by desfero** [ckeditor/ckeditor5-react#100]
Is there a way to provide `name` and `hasError` to the editor instance?
Because by default it uses `main` as `name` and therefore generates `aria-label=Rich Text Editor main` (it would be even better when to allow specifying `aria-labeledby` here). 
Same with `hasError` as i need to set `aria-invalid="true"` when the input state is invalid.

**Comment by Mgsy** [comment]
cc @pomek

**Comment by oleq** [comment]
> Is there a way to provide `name` and `hasError` to the editor instance?
> Because by default it uses `main` as `name` and therefore generates `aria-label=Rich Text Editor main` (it would be even better when to allow specifying `aria-labeledby` here).

Not unless you want to define your own editor class and specify it in [`document.createRoot()`](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_document-Document.html#function-createRoot) method.

You can change it when the editor is running, though:

```js
editor.editing.view.change( writer => {
    const viewEditableRoot = editor.editing.view.document.getRoot();

    writer.setAttribute( 'aria-label', 'Rich Text Editor, anything', viewEditableRoot );
} );
```

> Same with hasError as i need to set aria-invalid="true" when the input state is invalid.

Same here:

```js
editor.editing.view.change( writer => {
    const viewEditableRoot = editor.editing.view.document.getRoot();

    writer.setAttribute( 'aria-invalid', 'true', viewEditableRoot );
} );
```

**Comment by lnmp4000** [comment]
> > Is there a way to provide `name` and `hasError` to the editor instance?
> > Because by default it uses `main` as `name` and therefore generates `aria-label=Rich Text Editor main` (it would be even better when to allow specifying `aria-labeledby` here).
> 
> There's no way unless you want to define your own editor class and specify it in [`document.createRoot()`](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_document-Document.html#function-createRoot) method.
> 
> You can change it when the editor is running, though:
> 
> ```js
> editor.editing.view.change( writer => {
>     const viewEditableRoot = editor.editing.view.document.getRoot();
> 
>     writer.setAttribute( 'aria-label', 'Rich Text Editor, anything', viewEditableRoot );
> } );
> ```
> 
> > Same with hasError as i need to set aria-invalid="true" when the input state is invalid.
> 
> Same here:
> 
> ```js
> editor.editing.view.change( writer => {
>     const viewEditableRoot = editor.editing.view.document.getRoot();
> 
>     writer.setAttribute( 'aria-invalid', 'true', viewEditableRoot );
> } );
> ```

Sorry to drag this back again, but I'm experiencing the same issue using the `MultiRootEditor`, is there a way to implement a similar workaround to this? Our input names are not designed to be exposed to the user so we end up with `aria-label` with values such as `Rich Text Editor. Editing area: G161b127a-a0dc-46a0-841d-95ab2110dede.0.Ccab4f009-3401-4b29-a0de-5f78a16dae3f`.

I was trying to implement something using the event
` editor.ui.focusTracker.on('change:isFocused', (_e, _name, value) => { ... })`
but any changes I make to the DOM at this point get overwritten. I'm not sure how to make the leap from focus to getting the current active editor.
