### ISSUE TITLE
Append content at the end of editor with react (editor.model is getting undefined)

### ISSUE THREAD

**Issue by JitPatil12** [ckeditor/ckeditor5-react#102]
Please check the attached image - 
I want to try below code with React - 
model.change( writer => {
    writer.insertText( 'foo', paragraph, 'end' );
} );

from 
https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_writer-Writer.html

<img width="605" alt="abcs" src="https://user-images.githubusercontent.com/53329395/61930069-03246380-af7d-11e9-9334-10bee1546ee2.PNG">

Kindly suggest how to append data at cursor position in CKEditor with React

**Comment by jodator** [comment]
Could you provide how did you invoke this code? It looks like you're logging [event object](https://ckeditor.com/docs/ckeditor5/latest/api/module_utils_eventinfo-EventInfo.html).

**Comment by JitPatil12** [comment]
import CKEditor from "@ckeditor/ckeditor5-react";
import CKEditor from "@ckeditor/ckeditor5-react";

public render() {
return( <div>
        <CKEditor
          editor={InlineEditor}
          data={this.props.contentHTML || ""}
          

          onInit={editor => {
            // You can store the "editor" and use when it is needed.
            console.log("Editor is ready to use!", editor);
          }}
          onChange={(event, editor) => {
            const html = editor.getData();

            // check if there is no text
            var tmp = document.createElement("DIV");
            tmp.innerHTML = html || "";
            var text = tmp.textContent || tmp.innerText || "";

            if (text.trim() != "") {
              this.updateParentData(html);
              //editor.setData(html);
            }
          }}
          onBlur={editor => {
            console.log("Blur.", editor);
          }}
          onFocus={editor => {
            console.log("Focus.", editor);
            this.onFocus(editor);
            model.change( writer => {
writer.insertText( 'foo', paragraph, 'end' );
} );;
          }}
        />
     )
----------------------------------------------------------------
I want to used writer class as well to append content 
as per below URL -
https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_writer-Writer.html

**Comment by jodator** [comment]
Oh, I see now - there's a bug in our docuemnation. Thanks for reporting!

The proper API is in the [CKEditor5 react integration sample](https://github.com/ckeditor/ckeditor5-react/blob/db98f54ab542d698535b56b832714af234a464e0/sample/index.html#L61-L69):

https://github.com/ckeditor/ckeditor5-react/blob/db98f54ab542d698535b56b832714af234a464e0/sample/index.html#L61-L69

**Comment by JitPatil12** [comment]
Thank you for prompt reply...
It's working now but getting 'undefined' -
I am adding new text as 'foo' at end of test or cursor position  
<img width="537" alt="testtest" src="https://user-images.githubusercontent.com/53329395/61939360-5e615080-af93-11e9-85d4-a6914701fa6e.PNG">

**Comment by JitPatil12** [comment]
Hi @jodator ,

Thanks in advance.
Please look into below. I want to append the content at cursor position in CKEditor 5 and React as per https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_writer-Writer.html

import React from "react";
import CKEditor from "@ckeditor/ckeditor5-react";
import InlineEditor from "@ckeditor/ckeditor5-build-classic";
import {} from "@ckeditor/ckeditor5-engine/src/model/writer";
//import TrackChanges from "@ckeditor/ckeditor5-track-changes/src/tr";
var str = new Array();
export interface ITextEditorProps {
  contentHTML?: string;
  onContentChange(txt?: string): void;
  isReadOnlyFlg?: boolean;
  editorFor?: string;
  draggedComponent?: {};
}

export default class TextEditor extends React.Component<ITextEditorProps, any> {
  constructor(props: any) {
    super(props);
    this.onChange = this.onChange.bind(this);
    this.onBlur = this.onBlur.bind(this);
    this.onFocus = this.onFocus.bind(this);
    this.updateParentData = this.updateParentData.bind(this);
    this.state = {
      content: this.props.contentHTML,
      isReadOnlyFlag: props.isReadOnlyFlg
      //draggedComponent: props.draggedComponent
    };
  }

  updateParentData(value) {
    this.props.onContentChange(value);
    this.setState({ content: value });
  }

  onChange(value) {
    this.setState({ content: value });
  }

  onBlur(evt) {
    console.log("onBlur event called with event info: ", evt);
  }
  onFocus(evt) {
    console.log("onBlur event called with event info: ", evt);
    /* evt.model.change(writer => {
      writer.insertText("foo", "paragraph", "end");
    });
*/
    /*CKEditor.model.change(writer => {
      writer.insertText(npm i @ckeditor/ckeditor5-editor-classic
        "foo",
        CKEditor.model.document.selection.getFirstPosition()
      );
    });*/
  }
  afterPaste(evt) {
    console.log("afterPaste event called with event info: ", evt);
  }

  drop = async ev => {
    ev.preventDefault();
    let fieldObj = JSON.parse(ev.dataTransfer.getData("text"));
    console.log(fieldObj.id);
    /*let fieldObjNew = {
      id: fieldObj.id,
      name: fieldObj.name,
      description: fieldObj.description,
      Value: fieldObj.value
    };*/
    //await this._onAddCustomBlock("MyCustomBlock", fieldObjNew);
  };

  UNSAFE_componentWillReceiveProps(nextProps) {
    str = [];
    if (this.state.content !== nextProps.contentHTML) {
      str.push(nextProps.contentHTML + this.state.content);
    } else if (nextProps.contentHTML !== this.props.contentHTML) {
      str.push(this.props.contentHTML + nextProps.contentHTML);
    }
    console.log("str = " + str);
    this.setState({
      content: str != undefined ? str.toString() : ""
    });
  }

  public render() {
    return (
      <div>
        <CKEditor
          editor={InlineEditor}
          data={this.state.content || ""}
          onInit={editor => {
            // You can store the "editor" and use when it is needed.
            console.log("Editor is ready to use!", editor);
          }}
          onChange={(event, editor) => {
            const html = editor.getData();

            // check if there is no text
            var tmp = document.createElement("DIV");
            tmp.innerHTML = html || "";
            var text = tmp.textContent || tmp.innerText || "";

            if (text.trim() != "") {
              this.updateParentData(html);
              //editor.setData(html);
            }
          }}
          onBlur={(event, editor) => {
            console.log("Blur.", editor);
          }}
          onFocus={(event, editor) => {
            console.log("Focus.", editor);
            //this.onFocus(editor);
            /* editor.model.document.on("change", () => {
              console.log("The Document has changed!");
            });*/
          }}
        />
      </div>
    );
  }
}

**Comment by pomek** [comment]
The following `onFocus` callback inserts text `"foo"` at the place where the cursor is located:

```js
onFocus={ ( event, editor ) => {
	console.log( 'Focus.', editor );

	editor.model.change( writer => {
		const position = editor.model.document.selection.getFirstPosition();
		writer.insertText( 'foo', position, 'after' );
	} );
} }
```

Does it help you?

**Comment by oleq** [comment]
We can update https://stackoverflow.com/questions/57265263/ckeditor5-append-content-at-curosr-position-of-editor-with-react/57268821#57268821 when this issue is resolved.

**Comment by JitPatil12** [comment]
Hi @pomek  and @oleq ,

Thank you for reply.
In above my code, I am using setState method to assign content state in react then using as **data={this.state.content || ""}** in CKEditor. When I am assigning writer to content  this.setState({
      content: writer
    });...........It's breaking app please suggest CKEditor with React. You can refer above React TextEditor code

**Comment by Reinmar** [comment]
> We can update https://stackoverflow.com/questions/57265263/ckeditor5-append-content-at-curosr-position-of-editor-with-react/57268821#57268821 when this issue is resolved.

Done.
