### ISSUE TITLE
ckeditor-duplicated-modules message when i run tests

### ISSUE THREAD

**Issue by leonardovillela** [ckeditor/ckeditor5-react#104]
I'm using CKEditor5 in my react app. With the `@ckeditor/ckeditor5-build-inline` and when i run my jest tests that import a component that uses CKEditor i get this message:
```
console.error node_modules/@ckeditor/ckeditor5-build-inline/build/ckeditor.js:5      ckeditor-duplicated-modules: Some CKEditor 5 modules are duplicated. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-duplicated-modules
       undefined
```

I read the guide explain why this errors happen, but in my case i don't doing anything wrong. Is it a problem of `@ckeditor/ckeditor5-build-inline`?

**Comment by pomek** [comment]
I had the same problem in the past when I wanted to check some stuff using our builds. I couldn't understand why it happens. I decided to add a build at the beginning of a list of files to test:

https://github.com/ckeditor/ckeditor5-react/blob/db98f54ab542d698535b56b832714af234a464e0/scripts/utils/getkarmaconfig.js#L41-L43

It resolved our case. I am not sure whether it helps you though.

**Comment by leonardovillela** [comment]
In my case i use jest for test framework.

**Comment by pomek** [comment]
You need to add a path to Inline Build in Jest configuration (as [`testRegex`](https://jestjs.io/docs/en/configuration#testregex-string-array-string)). The build will be imported as a global variable (`InlineEditor`) and you can use it without import anything in particular test file.

Same like we did in our Karma config:

https://github.com/ckeditor/ckeditor5-react/blob/db98f54ab542d698535b56b832714af234a464e0/scripts/utils/getkarmaconfig.js#L40-L46

**Comment by leonardovillela** [comment]
Ok, I tried to use `testRegex`, but it didn't work. You have other option?

**Comment by leonardovillela** [comment]
What works for me, because i haven't a need to render the `InlineEditor`. Is mock inline-build. I do this in setupFiles jest.

`
import { configure } from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';

jest.mock('custom-ckeditor5-build-inline');

configure({ adapter: new Adapter() });
`
