### ISSUE TITLE
ckeditor5-react can be published in ES6

### ISSUE THREAD

**Issue by Viktor-the-great** [ckeditor/ckeditor5-react#105]
CKEditor 5 Builds are published in the original ES6 format. If environment requires ES5, I need to transpile CKEditor 5 source to ES5 ([ckeditor5 doc](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/advanced-setup.html#option-building-to-es5-target)).
ckeditor5-react are published in ES5 format, so I need to manually filter ckeditor5-react build (in webpack config).

I think ckeditor5-react Builds should be published in ES6 format like other CKEditor 5 builds.

**Comment by Mgsy** [comment]
cc @pomek

**Comment by pomek** [comment]
I don't see any reason why we couldn't do that. 

All that we need to do is just remove `@babel/preset-env` from the presets array in Webpack configuration.

All tests pass:

```
Finished in 1.915 secs / 0.509 secs @ 10:08:39 GMT+0200 (Central European Summer Time)

SUMMARY:
✔ 35 tests completed
```

Will the change be a BC?

@Reinmar, WDYT?

**Comment by ma2ciek** [comment]
The other question is why you need this transpilation. Because the support for IE11 is still [an open issue](https://github.com/ckeditor/ckeditor5/issues/330) and currently it does not work.

**Comment by Reinmar** [comment]
> All that we need to do is just remove `@babel/preset-env` from the presets array in Webpack configuration.

Sounds fine to me. Although, I don't know what kind of implications this will have for people who use CKE5 in CRA apps. I guess none, because CKE5 is already ES6 there, so it already needs to be treated with Terser (instead of Uglify) and hence already require changing the configuration. Is that correct? No documentation changes will be required?

**Comment by pomek** [comment]
> No documentation changes will be required?

No, we don't need to change anything.

**Comment by Reinmar** [comment]
Let's do it then.
