### ISSUE TITLE
CKeditor with base64 image support - need some help please!

### ISSUE THREAD

**Issue by gj1118** [ckeditor/ckeditor5-react#106]
Hi , 
I need some help please. Would you be kind enough to show us with an example on how to use `Ckeditor5` with `React` and `base64` image upload support please ?  

I have already installed and included the following libraries 

```JavaScript
import CKEditor from '@ckeditor/ckeditor5-react';
import ClassicEditor from '@ckeditor/ckeditor5-build-classic';
import Base64UploadAdapter from '@ckeditor/ckeditor5-upload/src/base64uploadadapter';
```

and then I have 

```JavaScript
 <CKEditor
       editor={ ClassicEditor }
       data="<p>Hello from CKEditor 5!</p>"
       onInit={ editor => {
           // You can store the "editor" and use when it is needed.
           console.log( 'Editor is ready to use!', editor );
       } }
       onChange={ ( event, editor ) => {
           const data = editor.getData();
           console.log( { event, editor, data } );
       } }
       onBlur={ editor => {
           console.log( 'Blur.', editor );
       } }
       onFocus={ editor => {
           console.log( 'Focus.', editor );
       } }
  />
```

but after that I don't know how to enable Base64 support. 
Please note that these are examples from the CKEditor site only. 

Any help will be well appreciated. 

Thank you for your time and patience.

**Comment by Mgsy** [comment]
Hello, please take a look at [Base64 image upload adapter documentation](https://ckeditor.com/docs/ckeditor5/latest/features/image-upload/base64-upload-adapter.html). As you can see, you should add `Base64UploadAdapter` plugin to your build and it will become enabled by default. 

In React integration, it's required to prepare a custom build which includes `Base64UploadAdapter` plugin and import it to your component. So, this line:
```
import ClassicEditor from '@ckeditor/ckeditor5-build-classic';
```
should be replaced with a path to your custom build. [Here](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html) you'll find a guide on how to add plugins to a build.

**Comment by dextel2** [comment]
can you provide a working example ?

**Comment by Mgsy** [comment]
> can you provide a working example ?

@dextel2, please take a look at [Adding plugins to a build](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html#adding-a-plugin-to-a-build) guide to learn how to do it.

**Comment by dextel2** [comment]
> > can you provide a working example ?
> 
> @dextel2, please take a look at [Adding plugins to a build](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html#adding-a-plugin-to-a-build) guide to learn how to do it.

that guide is for javascript if i'm not wrong, kindly provide for reactjs, I am facing the same issue as the original question

**Comment by Mgsy** [comment]
> that guide is for javascript if i'm not wrong, kindly provide for reactjs, I am facing the same issue as the original question

If you integrate a custom build with React, at first you have to [prepare the build](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#customizing-the-builds), then [integrate it with React](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#quick-start). Preparing the build is not related to React. 

Alternatively, you can [build the editor from the source](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#integrating-ckeditor-5-built-from-source) directly from your React project.

**Comment by dextel2** [comment]
@Mgsy Hey I made the online build and followed the docs i.e. `npm add file:./ckeditor5` the folder is in the root directory next to node_modules and importing like following

```
import Editor from "ckeditor5-custom-build/build/ckeditor";
import { CKEditor } from "@ckeditor/ckeditor5-react";
```

Yet I am getting the error `CKEditorError: ckeditor-duplicated-modules`

**Comment by kimmikirino** [comment]
I'm having the same issue too. It works without the base64uploadadapter

**Comment by HumbleBee14** [comment]
One thing is clear for sure - There's no clear documentation on how to use / integrate CKEDITOR with React.js based code!

Seems like nobody uses this for reactjs, because mostly I found for vanilla js / php based solutions only!

I'm not even sure how to add plugins ,DESPITE READING THE DOCUMENTTATION ! Plus the team doesn't seems to be interested either in giving a practical example / complete process, always pointing to the same documentation guide which basically no one is able to make sense of on how exactly to do it.

I don't understand why there's so Much complexity around this text editor as compared to other editors where everything is so simple to use without much fuss!! (FEEDBACK)

**Comment by ruslan090** [comment]
I am also facing same problem. CKEditorError: ckeditor-duplicated-modules.
