### ISSUE TITLE
autoFocus prop

### ISSUE THREAD

**Issue by ghost** [ckeditor/ckeditor5-react#11]
I added autoFocus prop with this code:

```js
_initializeEditor() {
    const { editor, config, data, onInit, onChange, autoFocus } = this.props;
...
if (autoFocus) this.editorInstance.editing.view.focus();
```

and using it like this:

`<CKEditor autoFocus />`.

Is it worth adding it?

**Comment by Reinmar** [comment]
It is – but the question is whether it shouldn't be added to the editor first? CKEditor 4 has such an option: https://docs.ckeditor.com/ckeditor4/latest/api/CKEDITOR_config.html#cfg-startupFocus

**Comment by johnunclesam** [comment]
So, are you meaning via `config` prop, @Reinmar?

**Comment by Reinmar** [comment]
Yep, you're right. We wouldn't need an additional property of the component then.

**Comment by Mgsy** [comment]
I've extracted a proposal from this ticket to a new one. You can track the progress [here](https://github.com/ckeditor/ckeditor5/issues/1926).

**Comment by castroCrea** [comment]
My temporary Solution
```
      onInit={editor => {
        editor.editing.view.focus()
      }}
```

**Comment by 7iomka** [comment]
> My temporary Solution
> 
> ```
>       onInit={editor => {
>         editor.editing.view.focus()
>       }}
> ```

If editor have already some content inside, focus will make carret at the start of editable area.
How to move it at the end?
I try this
```
editor.model.change(writer => {
        writer.setSelection(editor.model.document.getRoot(), 'end');
      });
```
but nothing happens.
Any ideas?
