### ISSUE TITLE
Can't compile CSS after add any feature or plugin

### ISSUE THREAD

**Issue by hoainamcr** [ckeditor/ckeditor5-react#111]
I know that's webpack config, so I can fix that, can you help me.
this is component
![image](https://user-images.githubusercontent.com/8084862/64412164-013fdb00-d0b9-11e9-9549-00da1521c310.png) please focus line 5

this is webpack config, and I have 2 option as well
![image 1](https://user-images.githubusercontent.com/8084862/64412220-22083080-d0b9-11e9-9032-44b8e9481043.png)

**OR**
![image 2](https://user-images.githubusercontent.com/8084862/64412265-35b39700-d0b9-11e9-8c48-24725ded77af.png)

but every thing cause error like below
![image](https://user-images.githubusercontent.com/8084862/64412425-86c38b00-d0b9-11e9-9216-ab1880cac91c.png)

this's react project, please help me know how to fix that issue, I guess that by **postcss** but don't know how to fix that. Thank you so much

**Comment by pomek** [comment]
You need to exclude CSS files used by CKEditor 5 from the project’s CSS loader. Now, CKEditor 5 assets are handled by `sass-loader`.

See: https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#modifying-webpack-configuration
