### ISSUE TITLE
Editor Blurry in Chrome, Good in Firefox

### ISSUE THREAD

**Issue by sbrodkey** [ckeditor/ckeditor5-react#112]
Here we can see the dropdown options are blurry in chrome:
![blurryInChrome](https://user-images.githubusercontent.com/3452128/64441850-abf5d080-d09c-11e9-8f5d-13b25dfc976f.PNG)

However, they are good in firefox, as seen here:
![goodInFirefox](https://user-images.githubusercontent.com/3452128/64441849-abf5d080-d09c-11e9-9c22-9291140f6750.PNG)

The "Paste the media URL in the input." popup is also blurry. 

All that is done here is copying the example from the docs:
https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html

I am hesitant to use CKEditor5 at the moment due these visual issues. If it looked in Chrome how it does in Firefox, I'd certainly have less hesitation.

**Comment by Mgsy** [comment]
Hi, we are aware of this issue and unfortunately, this is a problem caused by Chrome. Right now, the only solution is to change the styling on your own. Please, see open issue https://github.com/ckeditor/ckeditor5/issues/1053 and feel free to join the discussion.
