### ISSUE TITLE
what do you do with the html once you are done editing?

### ISSUE THREAD

**Issue by GamlielSchwartz** [ckeditor/ckeditor5-react#114]
I'm a bit confused really what you are supposed to do when you have the "data" saved as a string with the html. Like is there functionality to render the edited document outside of the editor? That is the point of this after all. I must be missing something...

**Comment by Mgsy** [comment]
CKEditor 5 is a content editor, so it's up to you how you'll use the data created by it. For example, you can write an article, then save it to the database and display it on your website using HTML generated with CKEditor 5. Actually, all depends on your use case.

Here you'll find guides which might be useful:
- [Getting and saving data](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/saving-data.html)
- [Content styles](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/content-styles.html).
