### ISSUE TITLE
Support for Context and Watchdog features

### ISSUE THREAD

**Issue by guillegette** [ckeditor/ckeditor5-react#118]
Hi there, how do you recommend to add Watchdog to this ? Thanks!

**Comment by Mgsy** [comment]
Hello, unfortunately, Watchdog isn't supported in CKEditor 5 integrations. However, there is a [feature request](https://github.com/ckeditor/ckeditor5/issues/4693) for it, feel free to add 👍 to the first post to bump its popularity and join the discussion.

**Comment by ma2ciek** [comment]
Currently, there's no easy way to integrate it outside of the Angular integration, because the integration is responsible for creating and destroying the editor, so the feature must be implemented inside the integration.

**Comment by ma2ciek** [comment]
I'm reopening the issue to track it.

**Comment by ma2ciek** [comment]
Perhaps to not overcomplicate the implementation it'd be good to introduce some kind of adapters that could handle the `<ckeditor>` component \<-> CKEditor5 feature glue code. I'll propose an API that should work for it.

**Comment by ma2ciek** [comment]
Perhaps it could be also a good moment to address #168. I mean - we should probably restart the editor when the component's configuration changes and the watchdog feature(s) provide a simple API for it.

**Comment by trungpham71198** [comment]
<img width="728" alt="Screen Shot 2020-12-27 at 15 55 56" src="https://user-images.githubusercontent.com/58923438/103167236-056aab80-485c-11eb-8e54-154c05dd8481.png">

<img width="470" alt="Screen Shot 2020-12-27 at 15 47 44" src="https://user-images.githubusercontent.com/58923438/103167117-def84080-485a-11eb-930d-57a09f9a5333.png">

<img width="472" alt="Screen Shot 2020-12-27 at 15 47 24" src="https://user-images.githubusercontent.com/58923438/103167119-e6b7e500-485a-11eb-9240-7c6c19d3a99f.png">

Can anyone help me fix this? Thank you.

**Comment by ma2ciek** [comment]
Hi @trungpham71198, could you report this bug in a separate issue? This one is already closed.
