### ISSUE TITLE
Not working in IE11

### ISSUE THREAD

**Issue by RahulShahUI** [ckeditor/ckeditor5-react#119]
ckeditor5-react not working in IE. showing object errors.

**Comment by Mgsy** [comment]
Hello, CKEditor 5 doesn't support IE11. See the [discussion](https://github.com/ckeditor/ckeditor5/issues/330) to learn more about it. If you'd like to run CKEditor 5, please, use a browser from our [browser compatibility list](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/support/browser-compatibility.html).
