### ISSUE TITLE
We do still need componentWillReceiveProps?

### ISSUE THREAD

**Issue by johnunclesam** [ckeditor/ckeditor5-react#12]
What this means really?

```js
  componentWillReceiveProps(newProps) {
    if (this.editorInstance && newProps.data) {
      this.editorInstance.setData(newProps.data);
    }
  }
```

We do still need it (which would be UNSAFE_componentWillReceiveProps)?

**Comment by pomek** [comment]
> What this means really?

Maybe I'm wrong but we want to update the editor's content if properties contain the `data` key and the editor is ready to use (mount and initialized).

> We do still need it

We will check it out during work on #5.

I'm closing this ticket. If you would like to add anything, do it in #3 (which touches the same method).
