### ISSUE TITLE
Adding comments to editor seems to disconnect the editor from the handler.

### ISSUE THREAD

**Issue by ansorensen** [ckeditor/ckeditor5-react#120]

**Comment by ansorensen** [comment]
I have a react component wrapping a build of the classic editor (that has comments in the build). However, whenever I call the addCommentThread from the editor's init function, the editor seems to disconnect from react. I can type on it, but the handleChangeText() function steps getting called and the actual data in react is stale.

I'm basing the comments implementation on the save and load implementation here. https://ckeditor.com/docs/ckeditor5/latest/features/collaboration/comments/comments-integration.html

Do I need to somehow use the adapter version?

```
function MyComponent (text) {
const editor = ...
const editorConfig = ...

function handleInitEditor(editor: any) {
    let commentsPlugin = editor.plugins.get('Comments')
    commentsPlugin.addCommentThread({
      threadId: 'thread-1',
      comments: [
        {
          commentId: 'comment-1',
          authorId: 'user-1',
          content: '<p>Are we sure we want to use a made-up disorder name?</p>',
          createdAt: new Date('09/20/2018 14:21:53'),
        },
        {
          commentId: 'comment-2',
          authorId: 'user-2',
          content: '<p>Why not?</p>',
          createdAt: new Date('09/21/2018 08:17:01'),
        },
      ],
    })
}

function handleChangeText() {
  // code here doesn't fire unless I comment out commentsPlugin.addCommentThread above
}


return (
<CKEditor
        editor={editor}
        config={editorConfig}
        data={text}
        onInit={handleInitEditor}
        onChange={handleChangeText}
      />)
}
```

**Comment by Mgsy** [comment]
Hi! Comments is our commercial plugin and this repository is a part of the open-source part of the project. Please, contact us through the [support channel](https://ckeditor.com/contact/).

**Comment by ansorensen** [comment]
(it would be nice if your open source projects actually worked with your commercial projects... or you should put a disclaimer on them that they don't)

**Comment by ansorensen** [comment]
Also, hiding information relevant to both the open source project and your commercial projects in private support threads is part of the reason why I posted in the first place. There are no working examples of the above.

**Comment by ma2ciek** [comment]
Hi @ansorensen ,

Not sure if will help you but we provide two samples of integrating React with our commercial plugins: 
- https://github.com/ckeditor/ckeditor5-collaboration-samples/tree/master/real-time-collaboration-for-react
- https://github.com/ckeditor/ckeditor5-collaboration-samples/tree/master/track-changes-for-react
