### ISSUE TITLE
Remove link to BrowserStack

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-react#121]
![image](https://user-images.githubusercontent.com/156149/69346024-65af1700-0c72-11ea-9b1c-5919acd54743.png)

**Comment by pomek** [comment]
[We just need to release the package.](https://github.com/ckeditor/ckeditor5-react/commit/63f804bc4c84c485467a2aadc10a354be143e027) I'll do it tomorrow. However, there is a breaking change (now the dist will be published in ES6). But I guess the change is safe enough to do a release on Friday.

**Comment by pomek** [comment]
Let's keep the issue open. We won't forget about it.

**Comment by pomek** [comment]
Fixed with the latest release:

![image](https://user-images.githubusercontent.com/2270764/69420594-4a4e1580-0d1f-11ea-9473-ac2d3da634a2.png)

https://github.com/ckeditor/ckeditor5-react/releases/tag/v2.0.0
