### ISSUE TITLE
How can i change config dynamically?

### ISSUE THREAD

**Issue by Jagadeesz** [ckeditor/ckeditor5-react#122]
"config={myCustomConfiguration}" this calls only at the time of init (onInit).
Nothing happens when i try to change "myCustomConfiguration" even in render()

Pl advice

**Comment by Mgsy** [comment]
Hi! You can't change the config dynamically on a ready editor's instance. If you'd like to update the editor with a new config, you should [destroy](https://ckeditor.com/docs/ckeditor5/latest/api/module_core_editor_editor-Editor.html#function-destroy) it and initialize once again with the new config.

**Comment by msrshahrukh100** [comment]
Those of us still looking for a solution to this, they can do something like this

```
addEditor = () => {
    const config = this.getEditorConfig();
    ClassicEditor
      .create( document.querySelector( '#editor' ), config)
      .then(newEditor => this.setState({editor: newEditor}))
      .catch( error => {
          console.log( error );
      });
  }
```

and use 

```
const { editor } =  this.state;
editor.destroy();
```

to destroy old editor instance and use the `addEditor` function to create a new one. The `getEditorConfig` should give you the updated config you wish to apply for the new editor.
