### ISSUE TITLE
Could we expose an optional callback handler to be called here instead of only logging errors?

### ISSUE THREAD

**Issue by ansorensen** [ckeditor/ckeditor5-react#123]
https://github.com/ckeditor/ckeditor5-react/blob/9c60780b8069392a2db346dc872660c2aabf51fa/src/ckeditor.jsx#L95

**Comment by ansorensen** [comment]
Another approach would be to optionally wrap the editor into an error boundary and show the error message there.

**Comment by pomek** [comment]
We could provide support for `onError` attribute but it will be called only if an error occurs during the editor's initialization. If the `onError` attribute won't be defined, `console.log( error )` could be called instead (as a default value).

Is it enough?

**Comment by ansorensen** [comment]
It's a start! (I can do a pull request this week for this issue).  Reading through the CKEditor5 docs, it doesn't look like there's an 'error' event listed in the [events](https://ckeditor.com/docs/ckeditor5/latest/api/module_editor-inline_inlineeditor-InlineEditor.html#event-change:state). When there is such functionality (and I can try to look into bringing that about), I can probably do a new pull request to expand the onError function here to add an error listener with the callback.

For our current use case, however, the errors we run into are most likely to be initialization issues, so this functionality would allow us to display errors to the users for the most likely cases and make it easier to identify and fix bugs (and eventually log them directly ourselves).
