### ISSUE TITLE
How to modify the height of CK in react

### ISSUE THREAD

**Issue by admiao** [ckeditor/ckeditor5-react#125]
我找遍了文档 并没有关于ck5 设置高度的资料

**Comment by Mgsy** [comment]
Hi! Please, while creating an issue, use English language, so we'll be able to understand you. 

According to the title name - you can change the height of the editor by changing `ck-editor__editable_inline` class. 

See https://stackoverflow.com/questions/46559354/how-to-set-the-height-of-ckeditor-5-classic-editor for more information.
