### ISSUE TITLE
Copy paste

### ISSUE THREAD

**Issue by KMadhanSPM** [ckeditor/ckeditor5-react#128]
In Windows, While I copying from google sheets and pasting in CKEditor 5 and CKEditor 5 react .
The content comes with following html tags and css styles   .
These tags are comes in CKEditor 5

![Screenshot (1)](https://user-images.githubusercontent.com/43366631/71573392-a3bd1780-2b09-11ea-8410-964a4b062f28.png)

**Comment by Mgsy** [comment]
Hi! Thanks for the report. Currently, CKEditor 5 doesn't support pasting from Google Sheets, so some unexpected behaviour might occur. I've opened a [feature request](https://github.com/ckeditor/ckeditor5/issues/6059), so feel free to add 👍 to the first post to bump its popularity.
