### ISSUE TITLE
Error when building with create-react-app.

### ISSUE THREAD

**Issue by ghost** [ckeditor/ckeditor5-react#13]
I'm using `create-react-app@1.5.2` and when I build using `npm run build` it says:

```log
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

        ./node_modules/@ckeditor/ckeditor5-build-classic/build/ckeditor.js:5:7374

Read more here: http://bit.ly/2tRViJ9

error Command failed with exit code 1.
```

How to do?

Maybe is there a way to disable es5 using just es6 in CRA?

**Comment by pomek** [comment]
We are aware of this problem. At this moment I don't have any working solution. 

The problem occurs with both CKEditor 5 builds and CKEditor 5 Framework. 

It shouldn't be a thing if [the build will be built as an ES5 code](https://docs.ckeditor.com/ckeditor5/latest/builds/guides/integration/advanced-setup.html#option-building-to-es5-target) but I didn't check it out.

For the CKE5 Framework, we have to parse our sources by babel and transpile it to es5. But I also didn't check it out.

Sorry for the delay, I didn't notice the ticket.

**Comment by ma2ciek** [comment]
No worries, his/her account is deleted already :D
