### ISSUE TITLE
Need WPS Writer Support

### ISSUE THREAD

**Issue by KMadhanSPM** [ckeditor/ckeditor5-react#130]
CKEditor 5 is not supporting the contents copied from WPS Writer. It converts the values to &nbsp.
Will you have any solution for this issue?

**Comment by Mgsy** [comment]
Hi! Thanks for the report. Unfortunately, currently, it's not possible to paste content from WPS to the editor. There's a feature request for it - https://github.com/ckeditor/ckeditor5/issues/2488. Feel free to add 👍 to the first post to bump its popularity.
