### ISSUE TITLE
uglifyjs-webpack-plugin vulnerability

### ISSUE THREAD

**Issue by tx-michael** [ckeditor/ckeditor5-react#133]
In the `webpack.config`, the minimizer plugin used currently is `UglifyJsWebpackPlugin`. This Plugin has a dependency `serialize-javascript` which has a cross-site scriting vulnerability: https://npmjs.com/advisories/1426. 

Uglifyjs-webpack-plugin itself is archived so the webpack config should switch to to use `terser-webpack-plugin`.

**Comment by pomek** [comment]
As we switched our builds to Terser some months ago (https://github.com/ckeditor/ckeditor5/issues/1353), I think we can agree that the change should be applied in this repo as well.
