### ISSUE TITLE
Make CkEditor responsive

### ISSUE THREAD

**Issue by msrshahrukh100** [ckeditor/ckeditor5-react#135]
Is there any docs for making the ckeditor responsive? The documentation isn't clear and I cannot find the solution anywhere. 

I am creating the ckeditor as below, but after the width of 600px the UI is breaking

  ```
addEditor = () => {
    const config = this.getEditorConfig();

    ClassicEditor
      .create( document.querySelector( '#editor' ), config)
      .then(newEditor => this.setState({editor: newEditor}))
      .catch( error => {
          console.log( error );
      });
  }
```

**Comment by alainmy** [comment]
![Masterchef Celebrity Chile - 1x20 mpg_snapshot_00 01 48](https://user-images.githubusercontent.com/34689823/85752082-1c77e780-b6d9-11ea-82db-1a7e1ade5dbc.jpg)
