### ISSUE TITLE
On press Enter page scroll goes down

### ISSUE THREAD

**Issue by sohanpc** [ckeditor/ckeditor5-react#137]
Hi 
I am using https://www.npmjs.com/package/react-ckeditor-component plugin for the text editor.
It working 

But I press the Enter key then page goes down will scroll. Could you please resolve that. 
Thanks

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. When using CKEditor 5 with React, we definitely recommend using our [official integration](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html). There should be no such problems after following our guide.
