### ISSUE TITLE
Getting Error in Math Type Using VueJs

### ISSUE THREAD

**Issue by bhavink21** [ckeditor/ckeditor5-react#138]
@Mgsy  i tried creating a custom build but still the error continues and i am not able to integrate **mathtype.**
whenever i install mathtype in the repository of ckeditor cloned from custom build it just removes the ckeditor pannel.
[https://github.com/bhavink21/ckeditor_mathtype.git](url)
here is the link of my repository where i tried adding custom build.
please help.
[ckeditor_mathtype/ckeditor5-build-classic/sample/index.html](url)
this is the sample file in the package where we can have a look of custom ckeditor before embedding it in the vue file.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. To be able to deal with this issue, I need to see the error you are getting and detailed steps to reproduce it. So it would be helpful if you provided those.
Apart from that, we are aware of the problems with integrating MathType in CKEditor + VueJS and you can read about some solutions [here](https://github.com/ckeditor/ckeditor5/issues/2048). If that doesn't do the trick, another workaround is to build a custom CKEditor with MathType plugin from source, and then add it to VueJS.
Hope that helps!

**Comment by bhavink21** [comment]
@FilipTokarski 

📋 Steps to reproduce

- Clone this Repo: https://github.com/bhavink21/ckeditor_mathtype.git
- composer install
- npm install
- php artisan serve
- npm run watch
- git clone -b stable https://github.com/ckeditor/ckeditor5-build-classic.git
- cd ckeditor5-build-classic
- npm install
- npm install --save-dev @ckeditor/ckeditor5-alignment
- npm install @wiris/mathtype-ckeditor5
- Edit the src/ckeditor.js file to add your plugin to the list of plugins which will be included in the build and to add your feature’s button to the toolbar:
 `// The editor creator to use.
import ClassicEditorBase from '@ckeditor/ckeditor5-editor-classic/src/classiceditor';
import Essentials from '@ckeditor/ckeditor5-essentials/src/essentials';
import UploadAdapter from '@ckeditor/ckeditor5-adapter-ckfinder/src/uploadadapter';
import Autoformat from '@ckeditor/ckeditor5-autoformat/src/autoformat';
import Bold from '@ckeditor/ckeditor5-basic-styles/src/bold';
import Italic from '@ckeditor/ckeditor5-basic-styles/src/italic';
import BlockQuote from '@ckeditor/ckeditor5-block-quote/src/blockquote';
import EasyImage from '@ckeditor/ckeditor5-easy-image/src/easyimage';
import Heading from '@ckeditor/ckeditor5-heading/src/heading';
import Image from '@ckeditor/ckeditor5-image/src/image';
import ImageCaption from '@ckeditor/ckeditor5-image/src/imagecaption';
import ImageStyle from '@ckeditor/ckeditor5-image/src/imagestyle';
import ImageToolbar from '@ckeditor/ckeditor5-image/src/imagetoolbar';
import ImageUpload from '@ckeditor/ckeditor5-image/src/imageupload';
import Link from '@ckeditor/ckeditor5-link/src/link';
import List from '@ckeditor/ckeditor5-list/src/list';
import Paragraph from '@ckeditor/ckeditor5-paragraph/src/paragraph';
import Alignment from '@ckeditor/ckeditor5-alignment/src/alignment';     // <--- ADDED
import MathType from '@wiris/mathtype-ckeditor5/src/plugin';  // <--- ADDED
export default class ClassicEditor extends ClassicEditorBase {}
// Plugins to include in the build.
ClassicEditor.builtinPlugins = [
    Essentials,
    UploadAdapter,
    Autoformat,
    Bold,
    Italic,
    BlockQuote,
    EasyImage,
    Heading,
    Image,
    ImageCaption,
    ImageStyle,
    ImageToolbar,
    ImageUpload,
    Link,
    List,
    Paragraph,
    Alignment,                                                         // <--- ADDED
   MathType                                                            // <--- ADDED
];
// Editor configuration.
ClassicEditor.defaultConfig = {
    toolbar: {
        items: [
            'heading',
            '|',
            'alignment',                                                 // <--- ADDED
            'bold',
            'italic',
            'link',
            'bulletedList',
            'numberedList',
            'imageUpload',
            'blockQuote',
            'undo',
            'redo',
            'MathType',                                           // <--- ADDED
            'ChemType'                                           // <--- ADDED
        ]
    },
    image: {
        toolbar: [
            'imageStyle:full',
            'imageStyle:side',
            '|',
            'imageTextAlternative'
        ]
    },
    // This value must be kept in sync with the language defined in webpack.config.js.
    language: 'en'
};`
- yarn run build
- execute [ckeditor_mathtype/ckeditor5-build-classic/sample/index.html](url)

**Comment by FilipTokarski** [comment]
Hi, I managed to run the CKeditor5 build you provided with no errors and MathType is working fine. So I think there may be some issues with your setup and not with CKEditor.

**Comment by bhavink21** [comment]
Could

> Hi, I managed to run the CKeditor5 build you provided with no errors and MathType is working fine. So I think there may be some issues with your setup and not with CKEditor.

@FilipTokarski  Could you please send me the steps of installation that you followed?
