### ISSUE TITLE
How to avoid duplicate node_modules in ckeditor5-react?

### ISSUE THREAD

**Issue by codeporan** [ckeditor/ckeditor5-react#139]
when I am trying to add plugins in ckeditor, it shows duplicated error . 
import React from "react";
import ReactDOM from "react-dom";
import ClassicEditor from '@ckeditor/ckeditor5-build-classic';

import CKEditor from "@ckeditor/ckeditor5-react";
import FontSize from "@ckeditor/ckeditor5-font";
import "./styles.css";

class App extends React.Component {
  componentDidMount() {
    ClassicEditor.create(document.querySelector(".editor"), {
      plugins: [FontSize],
      toolbar: [
        "heading",
        "|",
        "fontSize" //...,
      ],
      fontSize: {
        options: [
          generatePtSetting("10"),
          generatePtSetting("12"),
          generatePtSetting("14"),
          "default",
          generatePtSetting("18"),
          generatePtSetting("20"),
          generatePtSetting("22")
        ]
      }
    });

    function generatePtSetting(size) {
      return {
        model: size,
        title: size,
        view: {
          name: "span",
          styles: {
            "font-size": `${size}pt`
          }
        }
      };
    }
  }

  render() {
    return(<div>test</div>)
  }
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
How can I fix this?

https://codesandbox.io/s/ckeditor-5-ozkbo

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. When using CKEditor 5 with React please follow our [integration guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html). If you want to customise your editor and add some plugins, you will need to [build the editor from source](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#integrating-ckeditor-5-built-from-source).
Additionally, to avoid `duplicated modules` error in the future, make sure that all CKEditor plugins you installed have the same version.
Hope that helps!

**Comment by codeporan** [comment]
I did not understand how can explain code how it can be used ?

**Comment by FilipTokarski** [comment]
Follow [this guide to create a customised editor](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html#adding-a-plugin-to-a-build).
Then add editor to your React app by [importing your build](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#quick-start). 
So instead of: 
`import ClassicEditor from '@ckeditor/ckeditor5-build-classic';`
add:
`import MyCustomEditor from 'pathToMyEditor/build/ckeditor.js';`
