### ISSUE TITLE
CKFINDER

### ISSUE THREAD

**Issue by ederzadravec** [ckeditor/ckeditor5-react#141]
I spent 4 hours debugging your application, why don't you document this ##### right

Does it cost to put that in `CKFINDER` it is necessary to recover the API `{url: ''http://......, uploaded: true}` for the upload to work?

![image](https://user-images.githubusercontent.com/10898106/76577238-6c70cc80-64a3-11ea-85c6-b363a1b6c124.png)

![image](https://user-images.githubusercontent.com/10898106/76577256-772b6180-64a3-11ea-997c-295a4c9a1dee.png)

![image](https://user-images.githubusercontent.com/10898106/76577262-7e526f80-64a3-11ea-9d13-e49954ca4844.png)

**Comment by Mgsy** [comment]
Hi, I'm sorry for the late response, your issue somehow has slipped off our attention. Please, note that this repository is related to CKEditor 5 react integration, as your question seems to be related to CKEditor 5 itself. Could you please open a new issue with the detailed description in [our main repository](https://github.com/ckeditor/ckeditor5/issues)?
