### ISSUE TITLE
Cannot set property 'boundaries' of undefined

### ISSUE THREAD

**Issue by devlargs** [ckeditor/ckeditor5-react#142]
Anyone experienced this issue? 
![image](https://user-images.githubusercontent.com/30046754/76597972-ba85de80-653c-11ea-95c5-22395450048b.png)

It is working fine in localhost

![image](https://user-images.githubusercontent.com/30046754/76598072-f8830280-653c-11ea-9c47-3641e25345a9.png)

But it is failing in production 
![image](https://user-images.githubusercontent.com/30046754/76598118-17819480-653d-11ea-9fe1-dd6a3323183b.png)

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. I didn't have any problem with using CKEditor in React production build, so in order to look into this, I need to see your editor configuration, list of plugins and detailed steps to reproduce the issue.

**Comment by devlargs** [comment]
Hi, Thanks for the fast response. Im currently using this:

`https://www.npmjs.com/package/@ck-classic/ckeditor5-build-classic`
`https://github.com/devlargs/ckeditor5-build-classic`

**Comment by FilipTokarski** [comment]
When building for production in React, please check if your file `build/index.html` has proper import paths (there should be a dot at the beginning), for example:
`"./static/css/main.d1b05096.chunk.css"`
instead of
`"/static/css/main.d1b05096.chunk.css"`

Apart from that, if you encounter further problems, please make sure that you followed our official [React integration guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html).

**Comment by chaoningx** [comment]
i got the same problem.  after run build. i got ckeditor.js file in build folder and i modify two place.

-  first search method named "getItems"
`
* getItems(t = {}) {
  t.boundaries = this, t.ignoreElementEnd = !0;
  const e = new si(t);
  for (const t of e) yield t.item
}
`
change to 
`
* getItems(t = {}) {
  if (!t) {.t = {} }
  t.boundaries = this, t.ignoreElementEnd = !0;
  const e = new si(t);
  for (const t of e) yield t.item
}
`
- the second, search method named "getNearestSelectionRange" find the code like 

`
if (e) {
 const t = e.next();
  t.done || (n = !1, yield{walker: e, value: t.value})
}
`

change to: 

`
if (e && e.next) {
  const t = e.next();
  t.done || (n = !1, yield{walker: e, value: t.value})
}
`

and it running well.

**Comment by matt-heath** [comment]
Experiencing the same issue as @devlargs above.

**Comment by yankustefan** [comment]
I am experiencing a similar issue.
<img width="1158" alt="Screenshot 2020-03-23 at 13 11 35" src="https://user-images.githubusercontent.com/8319813/77315483-edcc2880-6d07-11ea-8375-c19b77f65827.png">

**Comment by FilipTokarski** [comment]
For everyone experiencing this issue, could you please be so kind to provide detailed steps/create a live demo sample? This will be very helpful for us when looking into this

**Comment by yankustefan** [comment]
Thanks for your feedback Filip. I am experiencing this on an app I can't make public.  So I will make a "blank" app, and see if I can reproduce it.
What I can say now is that first I had a custom build. And I replaced it with @ckeditor/ckeditor5-build-balloon@18.0.0 and removed the config property from <CKEditor>, but it's still failing.

**Comment by yankustefan** [comment]
Ok, I found the "cause" of the problem:
Upgrading "react-scripts": "1.1.4" to "react-scripts": "3.4.1" causes the symptoms mentioned above.
I assume that some of if the involved dependencies interferes with CKEditor.

**Comment by FilipTokarski** [comment]
Thanks @yankustefan for the insight!
cc @pomek

**Comment by yankustefan** [comment]
@FilipTokarski Thanks for your attention! 

Well, I removed package-lock.json, cleared the node_modules folder and re-installed all my dependencies. Now it works. Also with react-scripts 3.4.1.

**Comment by BurakKartal1** [comment]
@yankustefan did same but it did not work for me.

**Comment by FilipTokarski** [comment]
I tried it once again with react-scripts 3.4.1 and I can't reproduce the error. Running app in dev mode, as well as building for production, work fine. So the problem doesn't seem to be caused by editor and its react integration. I'm afraid you will have to debug this by yourself, and if everything fails, please provide detailed steps for reproduction - together with contents of your package.json and editor configuration.

**Comment by denisdedov** [comment]
Hi! The problem exists. We have it on the prod and local. I tried to remove package-lock.json, yarn.lock and re-install all libs but it doesn't help.

CKEditorError: unexpected-error {"originalError":{"message":"Cannot read property 'getTrimmed' of null","stack":"TypeError: Cannot read property 'getTrimmed' of null\n    at

**Comment by Mgsy** [comment]
To everyone experiencing this issue - could you please provide detailed steps to reproduce the problem or prepare a demo with a minimal amount of code required to reproduce it? Without that, we won't be able to debug it and check what's going on.

**Comment by denisdedov** [comment]
> To everyone experiencing this issue - could you please provide detailed steps to reproduce the problem or prepare a demo with a minimal amount of code required to reproduce it? Without that, we won't be able to debug it and check what's going on.

**react-scripts 3.4.1 react 16.3.1 react-dom 16.3.1** "**@ckeditor/ckeditor5-build-decoupled-document": "15.0.0",
    "@ckeditor/ckeditor5-react": "1.1.3",**  I can send some part of code and maybe video. Do you have  email on which I can send information ?

**Comment by lordlpua** [comment]
For me I found resolve. Not good but... Downgrade react-scripts to 3.00 and it works.

**Comment by frmendez** [comment]
for me, upgrading 	react-scripts from 3.0.0 to 3.4.1 caused this issue

**Comment by frmendez** [comment]
@yankustefan can you provide your package.json to compare?

**Comment by mesija** [comment]
hi, same issue...

my package.json is:
```
{
  "name": "test",
  "version": "1.0.0",
  "private": true,
  "dependencies": {
    "@ckeditor/ckeditor5-build-classic": "^12.4.0",
    "@ckeditor/ckeditor5-react": "^1.1.3",
    "@ckeditor/ckeditor5-remove-format": "^10.0.4",
    "@ckeditor/ckeditor5-table": "^13.0.2",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-scripts": "^3.4.1"
  },
  "scripts": {
    "start": "react-scripts start"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ]
}
```
i created a small example where you can see this error, here it is https://github.com/mesija/ckeditor-issue

@Mgsy hope you can solve this error. If you need more details let me know :)

**Comment by mesija** [comment]
I found a solution for my case, it was not at all obvious and i am not sure what exactly was the problem. I just opened the root file of the editor (/node_modules/@ckeditor/ckeditor5-build-classic/build/ckeditor.js) in PhpStorm and selected "Code> Reformat Code" from the menu.

I do not know how this solves the problem (I suspect changing the file updated some cache files in the system for this module or something) and after that everything worked for me, even after reinstalling the module in its original form.

**Comment by FraserThompson** [comment]
I have this issue too and none of the above solutions work. `react-scripts` is at 3.4.0 and since my dev environment uses Docker it's a fresh environment each time, so the problem can't be caused by stale files.

I've made a minimal test case here which reproduces the issue for me (minus Docker): https://github.com/FraserThompson/ckeditor-minimal-test-case

**Comment by irvanherz** [comment]
Got same issue in production server, but not in local. I've tried to upgrade nodejs, and issue happens. So I decide to downgrade my nodejs to previous version. But issue now still happened in local.
This is second times i got same problem. Previously, I did delete node_modules and run yarn install, but this solution doesn't work anymore for now.

**Comment by MasTahFuLL1993** [comment]
Hey everyone, we have encountered the same issue and found out where the problem originated. 

For us the problem and solution turned out to be inside package.json under the "browserslist" section. We had to remove the "not ie <= 11" part to get it to work.

![image](https://user-images.githubusercontent.com/12097191/87608336-f05fed00-c6ff-11ea-8494-c886a77dfc76.png)

It was really hard to pinpoint where the issue originated from because of this issue mentioned in the create react app docs. 
![image](https://user-images.githubusercontent.com/12097191/87608505-6401fa00-c700-11ea-988c-63ad368af4f4.png)

https://create-react-app.dev/docs/supported-browsers-features/

For @devlargs you may have a different configuration set up inside your browserslist for both development and production or not have cleared your cache on you local/dev which explains the different behavior for both your local/dev and prod environments.

**Comment by devlargs** [comment]
> Hey everyone, we have encountered the same issue and found out where the problem originated for us.
> 
> For us the problem and solution turned out to be inside package.json under the "browserslist" section. We had to remove the "not ie <= 11" part to get it to work.
> 
> ![image](https://user-images.githubusercontent.com/12097191/87608336-f05fed00-c6ff-11ea-8494-c886a77dfc76.png)
> 
> It was really hard to pinpoint where the issue originated from because of this other issue mentioned in the create react app docs.
> ![image](https://user-images.githubusercontent.com/12097191/87608505-6401fa00-c700-11ea-988c-63ad368af4f4.png)
> 
> https://create-react-app.dev/docs/supported-browsers-features/
> 
> For @devlargs @irvanherz and others facing differences between your local/dev and prod environments. You may have a different configuration set up inside your browserslist for both development and production or not have cleared your cache on your local/dev or prod which explains the difference in behavior.
> 
> ![image](https://user-images.githubusercontent.com/12097191/87609820-e93ade00-c703-11ea-9f56-1d32a3f670ce.png)

thanks @MasTahFuLL1993 this is working

**Comment by pierre-H** [comment]
Same problem even with the fix of @MasTahFuLL1993 😢

**Comment by timofeyp** [comment]
I have the same issue. Did a component as described here: [https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#quick-start](url)

```
import React, { Component } from 'react';
import { CKEditor } from '@ckeditor/ckeditor5-react';

import ClassicEditor from '@ckeditor/ckeditor5-build-classic';

class App extends Component {
    render() {
        return (
            <div className="App">
                <h2>Using CKEditor 5 build in React</h2>
                <CKEditor
                    editor={ClassicEditor}
                    data="<p>Hello from CKEditor 5!</p>"
                    onReady={(editor: any) => {
                        // You can store the "editor" and use when it is needed.
                        console.log('Editor is ready to use!', editor);
                    }}
                    onChange={(event: any, editor: { getData: () => any }) => {
                        const data = editor.getData();
                        console.log({ event, editor, data });
                    }}
                    onBlur={(event: any, editor: any) => {
                        console.log('Blur.', editor);
                    }}
                    onFocus={(event: any, editor: any) => {
                        console.log('Focus.', editor);
                    }}
                />
            </div>
        );
    }
}

export default App;
```

![image](https://user-images.githubusercontent.com/37977572/109296817-0317d400-7842-11eb-84e5-e9a36a468ac6.png)


"react": "17.0.1"
"react-scripts": "4.0.1"
