### ISSUE TITLE
How to set CKEDITOR.env.isCompatible?

### ISSUE THREAD

**Issue by irvanherz** [ckeditor/ckeditor5-react#151]
Hello,
I'm using `@ckeditor/ckeditor5-react 2.1.0` and `@ckeditor/ckeditor5-build-classic 19.0.0`. The docs said:

> Since version 4.5 CKEditor is only disabled in environments that are known to be incompatible.

However this behavior can be forced by set `CKEDITOR.env.isCompatible` flag to `true`.

So I tried it in componentDidMount (I know it was a dumb ways. LOL), but later it said: `'CKEDITOR' is undefined.`

Please let me know how to do it properly in React.
Thank you.

**Comment by Mgsy** [comment]
Hi, CKEditor 4 and CKEditor 5 are applications with completely different architecture. `CKEDITOR.env.isCompatible` is a CKEditor 4 configuration option and it doesn't exist in CKEditor 5, that's why you can't change it.
