### ISSUE TITLE
How to render toolbar buttons in a new row instead of the main row?

### ISSUE THREAD

**Issue by henok-tesfaye** [ckeditor/ckeditor5-react#153]
<img width="714" alt="Screen Shot 2020-05-23 at 5 40 47 PM" src="https://user-images.githubusercontent.com/51118408/82733464-a3bdee00-9d1c-11ea-8854-f259e1edc1aa.png">

I integrated CKEditor5 in my app from the source, and now I want to render the buttons which are displayed in menu item, in the second row of the toolbar. I don't want to be in menu item.

```
ClassicEditor.defaultConfig = {
  toolbar: {
    items: [
      'Essentials',
      'heading',
      'Mathtype',
      'ChemType',
      '|',
      'bold',
      'italic',
      'underline',
      ....
    ]
  }
}

```

How can I display buttons in a new row instead of the main row?

**Comment by henok-tesfaye** [comment]
we can add this prop in toolbar object, `shouldNotGroupWhenFull: true` , but I want to render the last two items in the next row since they are related with the buttons displayed in the beginning of the second row. How to group them?

<img width="711" alt="Screen Shot 2020-05-24 at 11 16 31 AM" src="https://user-images.githubusercontent.com/51118408/82749183-14621a80-9db0-11ea-9bb3-abf1f0658568.png">

**Comment by Mgsy** [comment]
Hi, there's no official feature for allowing line breaks in the toolbar, however, you can introduce it on your own. Please, see the [following comment](https://github.com/ckeditor/ckeditor5/issues/6146#issuecomment-589618383) in the feature request.
