### ISSUE TITLE
Support for className property

### ISSUE THREAD

**Issue by shabith** [ckeditor/ckeditor5-react#156]
Hi Guys,

Will `className` property be implemented in a future release?

**Comment by Mgsy** [comment]
Hi, can you tell us more about your use case? What you'd like to achieve with `className`?

**Comment by shabith** [comment]
Hello @Mgsy, Let say that I need to highlight the component based on the validation so if we have a className property we can utilize it in a situation like that.

**Comment by Mgsy** [comment]
So, I think the best way would be putting your component in a container and adding `className` to it. To be honest, I don't think we'll be introducing such property to the editor component.
