### ISSUE TITLE
How can I add "View Source" option in it?

### ISSUE THREAD

**Issue by ArchanaSharma95** [ckeditor/ckeditor5-react#158]
I want to add editor with "View Source" option. It is the basic requirement of my project. Please suggest how can I integrate "View Source" option. I haven't seen any documentation regarding this, please suggest.

**Comment by FilipTokarski** [comment]
Hi, in CKEditor 5 there is no "View Source" option. This is one of the features of CKEditor4, but please keep in mind that CKE4 and CKE5 are separate apps with very different architecture.
There is a long [discussion about this feature](https://github.com/ckeditor/ckeditor5/issues/592), especially comments on [current state](https://github.com/ckeditor/ckeditor5/issues/592#issuecomment-470424532) and some more explanation [here](https://github.com/ckeditor/ckeditor5/issues/592#issuecomment-502036006).  
If this feature is important to you, please feel free to add to this discussion. For now, I'll close this one as a duplicate.
