### ISSUE TITLE
unable to install packages - tokens invalidated (https://status.npmjs.org/incidents/dn7c1fgrr7ng) 

### ISSUE THREAD

**Issue by O365Tycho** [ckeditor/ckeditor5-react#16]
npm install --save @ckeditor/ckeditor5-react @ckeditor/ckeditor5-build-inline
npm WARN notice Due to a recent security incident, all user tokens have been invalidated. Please see https://status.npmjs.org/incidents/dn7c1fgrr7ng for more details. To generate a new token, visit https://www.npmjs.com/settings/~/tokens or run "npm login".
npm ERR! code E404
npm ERR! 404 Not Found: @ckeditor/ckeditor5-react@latest

**Comment by pomek** [comment]
See: https://github.com/ckeditor/ckeditor5-react/issues/4

**Comment by pomek** [comment]
The first version has just been published. 

Now using `npm install @ckeditor/ckeditor5-react` will install the package in version `1.0.0-beta.1`.

The feedback is welcome.
