### ISSUE TITLE
can I integrate CKEditor5 without doing yarn eject? I want to build from source.

### ISSUE THREAD

**Issue by rishabhsinghal-rgb** [ckeditor/ckeditor5-react#166]

**Comment by FilipTokarski** [comment]
cc @pomek can you take a look at it?

**Comment by pomek** [comment]
Sure, I'll check it out today using CRA@3.

**Comment by pomek** [comment]
I've just checked whether you can add new rules (somehow) to Webpack configuration using CRA and unfortunately, it's still impossible. Answering the question, building the editor from the source in CRA without ejecting is not doable right now.
