### ISSUE TITLE
Multiple editor instances deletion triggers onChange bug in React

### ISSUE THREAD

**Issue by nikijiandani** [ckeditor/ckeditor5-react#169]
## 📝 Provide detailed reproduction steps (if any)
Link to Codesandbox with the issue recreated - [https://codesandbox.io/s/ckeditor5-onchange-bug-e0nt4?file=/src/App.js](https://codesandbox.io/s/ckeditor5-onchange-bug-e0nt4?file=/src/App.js)

### ✔️ Expected result

When I delete the second item in the list, the first item and third item still remain.

### ❌ Actual result

When I delete the second item in the list, the third item duplicates and takes up index 1 and 2.

## 📃 Other details

When I use the onBlur event instead of onChange, it works as expected.

* Browser: Chrome 
* OS: …
* CKEditor version: 5
* Installed CKEditor plugins: Default built in plugins - 	Alignment, Autoformat, BlockQuote, Bold, CKFinder, CKFinderUploadAdapter, Essentials, FontColor, FontSize, Heading, Highlight, HorizontalLine, Image, ImageCaption, ImageStyle, ImageToolbar, ImageUpload, Indent, IndentBlock, Italic, Link, List, MediaEmbed, Paragraph, PasteFromOffice, RemoveFormat, Table, TableToolbar, TextTransformation, Underline

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by ma2ciek** [comment]
I see that it was reported already in #168.
