### ISSUE TITLE
Are you sure that the component works fine with the DecoupledEditor?

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-react#17]
How does it know which element to return to React?

**Comment by pomek** [comment]
Did you see https://github.com/ckeditor/ckeditor5-react/blob/45cd9d31024ad8493209de39086d25d3e72fee60/README.md#document-editor?

A developer must add the toolbar manually. I provided an example how to do it using `onInit` property.

**Comment by ma2ciek** [comment]
But I see that I miss that information in the Angular's readme.

**Comment by Reinmar** [comment]
I saw that section but I didn't know that we're using the editors in the "replace" mode. I thought we use the detached mode and inject them afterwards (in which case decoupled editor would not work by default because it does not expose `editor.element`). In general, we'll have to do the latter (https://github.com/ckeditor/ckeditor5-react/issues/18).
