### ISSUE TITLE
ValidationError: Style Loader Invalid Options  options should NOT have additional properties

### ISSUE THREAD

**Issue by Rajesh-Thiyagarajan** [ckeditor/ckeditor5-react#171]
Dear Team 
Currently i am intergrating the CKEditor5 with React Js.
I got stucked because of below error.
![image](https://user-images.githubusercontent.com/67726510/91451360-55ece080-e84b-11ea-95f5-956db579c251.png)

I am using craco for the webpack configuration.
Here is the my webpack.config

const path = require("path");
const webpack = require("webpack");
const { getLoader, loaderByName, addBeforeLoader } = require("@craco/craco");
const absolutePath = path.join(__dirname, "../components");
const { styles } = require("@ckeditor/ckeditor5-dev-utils");
const cssRegex = /\.css$/;
const cssModuleRegex = /\.module\.css$/;

const enableCKEWebpackConfigPlugin = (webpackConfig, { env, paths }) => {
  // Extract the oneOf array from the relevant webpack.module.rules object
  let oneOf;
  let ix;
  ix = webpackConfig.module.rules.findIndex(item => {
    return item.hasOwnProperty("oneOf");
  });
  oneOf = webpackConfig.module.rules[ix].oneOf;

  // Add the SVG and CSS loaders to the oneOf array
  const additions = [
    {
      test: /ckeditor5-[^/\\]+[/\\]theme[/\\]icons[/\\][^/\\]+\.svg$/,
      use: ["raw-loader"]
    },
    {
      test: /ckeditor5-[^/\\]+[/\\]theme[/\\].+\.css$/,
      use: [
        {
          loader: "style-loader",
          options: {
            injectType: "singletonStyleTag"
          },
        },
        {
          loader: "postcss-loader",
          options: styles.getPostCssConfig({
            themeImporter: {
              themePath: require.resolve("@ckeditor/ckeditor5-theme-lark")
            },
            minify: true
          })
        }
      ]
    },
  ];
  additions.forEach((item, index) => {
    oneOf.push(item);
  });

  // Modify cssRegex
  let loader;
  loader = oneOf.find(item => {
    if (item.test !== undefined)
      return item.test.toString() === cssRegex.toString();
  });
  loader.exclude = [cssModuleRegex, /ckeditor5-[^/\\]+[/\\]theme[/\\].+\.css$/];

  // Modify cssModuleRegex
  loader = oneOf.find(item => {
    if (item.test !== undefined)
      return item.test.toString() === cssModuleRegex.toString();
  });
  loader.exclude = [/ckeditor5-[^/\\]+[/\\]theme[/\\].+\.css$/];

  // Modify file-loader
  loader = oneOf.find(item => {
    if (item.loader !== undefined)
      return (
        item.loader.toString() === require.resolve("file-loader").toString()
      );
  });
  loader.exclude = [
    /\.(js|mjs|jsx|ts|tsx)$/,
    /\.html$/,
    /\.json$/,
    /ckeditor5-[^/\\]+[/\\]theme[/\\]icons[/\\][^/\\]+\.svg$/,
    /ckeditor5-[^/\\]+[/\\]theme[/\\].+\.css$/
  ];

  // Always return a config object.
  return webpackConfig;
};

module.exports = {
  webpack: {
    alias: {},
    plugins: [
      new webpack.ProvidePlugin({
        $: "jquery",
        jQuery: "jquery",
        "window.jQuery": "jquery",
        "window.moment": "moment",
        moment: "moment",
        Raphael: "raphael", // required by morris.js
      }),
    ],
    configure: (webpackConfig, { env, paths }) => {
      const { isFound, match } = getLoader(
        webpackConfig,
        loaderByName("babel-loader")
      );
      if (isFound) {
        const include = Array.isArray(match.loader.include)
          ? match.loader.include
          : [match.loader.include];
        match.loader.include = include.concat[absolutePath];
        const exclude = Array.isArray(match.loader.exclude)
          ? match.loader.exclude
          : [match.loader.exclude]
        match.loader.exclude = {
          test: match.loader.exlude || /node_modules/,
          not: [absolutePath]
        }
      }
      return enableCKEWebpackConfigPlugin(webpackConfig, { env, paths });
    },
  },
};

Here is the package.json
{
  "name": "my-project",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@apollo/react-hooks": "^3.1.5",
    "@ckeditor/ckeditor5-basic-styles": "^21.0.0",
    "@ckeditor/ckeditor5-block-quote": "^21.0.0",
    "@ckeditor/ckeditor5-dev-utils": "^13.0.0",
    "@ckeditor/ckeditor5-easy-image": "^15.0.0",
    "@ckeditor/ckeditor5-editor-classic": "^15.0.0",
    "@ckeditor/ckeditor5-essentials": "^15.0.0",
    "@ckeditor/ckeditor5-font": "^15.0.0",
    "@ckeditor/ckeditor5-heading": "^15.0.0",
    "@ckeditor/ckeditor5-image": "^15.0.0",
    "@ckeditor/ckeditor5-paragraph": "^15.0.0",
    "@ckeditor/ckeditor5-react": "^1.1.3",
    "@ckeditor/ckeditor5-remove-format": "^15.0.0",
    "@ckeditor/ckeditor5-theme-lark": "^15.0.0",
    "@ckeditor/ckeditor5-utils": "^15.0.0",
    "@craco/craco": "^5.6.1",
    "@hookform/error-message": "^0.0.4",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "@types/bootstrap-select": "^1.11.1",
    "apexcharts": "^3.19.3",   
    "bootstrap-select": "^1.13.17",
    "dotenv": "^8.2.0",
    "graphql": "^15.0.0",
    "graphql-anywhere": "^4.2.7",
    "graphql-tag": "^2.10.3",
    "jquery": "^3.5.1",
    "jquery-knob": "1.2.11",
    "jquery-slimscroll": "1.3.8",
    "jquery-sparkline": "2.4.0",
    "jquery.easing": "1.4.1",
    "jquery.flot.spline": "themicon/jquery.flot.spline",
    "jquery.flot.tooltip": "github:krzysu/flot.tooltip",
    "qs": "^6.9.4",
    "query-string": "^6.13.1",
    "raw-loader": "^3.1.0",
    "react": "^16.13.1",
    "react-apexcharts": "^1.3.7",
    "react-dom": "^16.13.1",
    "react-hook-form": "^6.3.0",
    "react-i18next": "^11.7.0",
    "react-native-base64": "^0.1.0",
    "react-redux": "^7.2.0",
    "react-router-dom": "^5.2.0",
    "react-scripts": "3.4.1",
    "redux": "^4.0.5",
    "save": "^2.4.0"
  },
  "scripts": {
    "start": "craco start",
    "build": "craco build",
    "test": "craco test",
    "eject": "craco eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

**Comment by Mgsy** [comment]
Hi, what `style-loader` version you use? There's a chance that you use some \< 1.0.0 version which [might cause troubles with building](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#installing-missing-dependencies). As the documentation says:

> Create React App uses `style-loader` in version `0.23.1` which might cause issues during a building process. To avoid it, it is recommended to bump the version manually to `1.0.0` which is used in CKEditor 5 packages.

**Comment by Rajesh-Thiyagarajan** [comment]
@Mgsy Thank you so much for your quick feedback,
 but i don't what style-loader i am using, can you please send me the yarn command..
 then i will get the idea.

**Comment by Rajesh-Thiyagarajan** [comment]
> Hi, what `style-loader` version you use? There's a chance that you use some < 1.0.0 version which [might cause troubles with building](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#installing-missing-dependencies). As the documentation says:
> 
> > Create React App uses `style-loader` in version `0.23.1` which might cause issues during a building process. To avoid it, it is recommended to bump the version manually to `1.0.0` which is used in CKEditor 5 packages.

@Mgsy 
I have changed the style-loader version now it's working thank you so much.

**Comment by Mgsy** [comment]
> [**@Mgsy**](https://github.com/Mgsy)  
> I have changed the style-loader version now it's working thank you so much.

Great to hear that :) Have fun with CKEditor 5!

**Comment by anmol5varma** [comment]
@Rajesh-Thiyagarajan @Mgsy Can you help me on how to bump the style-loader version. I am using cra version ```3.4.3```?

**Comment by kishan-tocca** [comment]
> > Hi, what `style-loader` version you use? There's a chance that you use some < 1.0.0 version which [might cause troubles with building](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#installing-missing-dependencies). As the documentation says:
> > > Create React App uses `style-loader` in version `0.23.1` which might cause issues during a building process. To avoid it, it is recommended to bump the version manually to `1.0.0` which is used in CKEditor 5 packages.
> 
> @Mgsy
> I have changed the style-loader version now it's working thank you so much.

how can I change style-loader version manually?

**Comment by Mgsy** [comment]
> how can I change style-loader version manually?

It could be done in your `package.json` file.

**Comment by kishan-tocca** [comment]
> > how can I change style-loader version manually?
> 
> It could be done in your `package.json` file.

got it thanx
