### ISSUE TITLE
How to use customize icon for new customize plugin ? using react

### ISSUE THREAD

**Issue by Rajesh-Thiyagarajan** [ckeditor/ckeditor5-react#172]

**Comment by FilipTokarski** [comment]
Hi, could you describe you use case more precisely?

**Comment by Rajesh-Thiyagarajan** [comment]
> Hi, could you describe you use case more precisely?

@FilipTokarski 

Below code my custmized ckeditor5; Now i want to add one customize plugin in that. I am trying to use the customize icon
import React from "react";

import { Col } from 'reactstrap';

import { ContentWrapper } from "@nextaction/components";

import CKEditor from "@ckeditor/ckeditor5-react";
import ClassicEditor from "@ckeditor/ckeditor5-editor-classic/src/classiceditor";

import Essentials from "@ckeditor/ckeditor5-essentials/src/essentials";

import Alignment from "@ckeditor/ckeditor5-alignment/src/alignment";
import Bold from "@ckeditor/ckeditor5-basic-styles/src/bold";
import Italic from "@ckeditor/ckeditor5-basic-styles/src/italic";
import Underline from "@ckeditor/ckeditor5-basic-styles/src/underline";

import Paragraph from "@ckeditor/ckeditor5-paragraph/src/paragraph";

import Heading from "@ckeditor/ckeditor5-heading/src/heading";

import FontFamily from "@ckeditor/ckeditor5-font/src/fontfamily";
import FontColor from "@ckeditor/ckeditor5-font/src/fontcolor";
import FontSize from "@ckeditor/ckeditor5-font/src/fontsize";
import FontBackgroundColor from "@ckeditor/ckeditor5-font/src/fontbackgroundcolor";

import RemoveFormate from "@ckeditor/ckeditor5-remove-format/src/removeformat";

import Image from "@ckeditor/ckeditor5-image/src/image";
import ImageCaption from "@ckeditor/ckeditor5-image/src/imagecaption";
import ImageResize from "@ckeditor/ckeditor5-image/src/imageresize";
import ImageToolbar from "@ckeditor/ckeditor5-image/src/imagetoolbar";
import ImageUpload from "@ckeditor/ckeditor5-image/src/imageupload";
import ImageStyle from "@ckeditor/ckeditor5-image/src/imagestyle";

import Indent from "@ckeditor/ckeditor5-indent/src/indent";
import IndentBlock from "@ckeditor/ckeditor5-indent/src/indentblock";

import Link from "@ckeditor/ckeditor5-link/src/link";

import List from "@ckeditor/ckeditor5-list/src/list";
import NumberList from "@ckeditor/ckeditor5-list/src/listediting";

import Plugin from '@ckeditor/ckeditor5-core/src/plugin';

// import TemplatePreview from "../ckeditor/plugin/templatepreview";
import imageIcon from '@ckeditor/ckeditor5-core/theme/icons/image.svg';
import ButtonView from '@ckeditor/ckeditor5-ui/src/button/buttonview';


import TemplatePreviewIcon from "./templatepreview.png";


class TemplatePreview extends Plugin {
    init() {
        const editor = this.editor;

        editor.ui.componentFactory.add('templatePreview', locale => {
            const view = new ButtonView(locale);

            view.set({
                label: 'Template Preview',
                icon: TemplatePreviewIcon,
                tooltip: true
            });

            // Callback executed once the image is clicked.
            view.on('execute', () => {
                const imageUrl = prompt('Image URL');
                editor.model.change(writer => {
                    const imageElement = writer.createElement('image', {
                        src: imageUrl
                    });

                    // Insert the image in the current selection location.
                    editor.model.insertContent(imageElement, editor.model.document.selection);
                });
            });

            return view;
        });
    }
}

const editorConfiguration = {
    plugins: [
        Essentials,
        Bold,
        Italic,
        Underline,
        Paragraph,
        Heading,
        FontBackgroundColor,
        FontColor,
        FontFamily,
        FontSize,
        RemoveFormate,
        Image,
        ImageCaption,
        ImageResize,
        ImageStyle,
        ImageToolbar,
        ImageUpload,
        Indent,
        IndentBlock,
        List,
        NumberList,
        Link,
        Alignment,
    ],
    extraPlugins: [
        TemplatePreview
    ],
    toolbar: [
        "bold",
        "italic",
        "underline",
        "|",
        "fontfamily",
        "fontcolor",
        "|",
        "heading",
        "|",
        "fontbackgroundcolor",
        "fontsize",
        "|",
        "numberedList",
        "bulletedList",
        'outdent',
        'indent',
        "|",
        "removeformat",
        "imageupload",
        "indentBlock",
        "link",
        "alignment",
        "templatePreview"
    ],
    heading: {
        options: [
            { model: 'paragraph', view: 'p', title: 'Paragraph', class: 'ck-heading_paragraph' },
            { model: 'heading1', view: 'h1', title: 'Heading 1', class: 'ck-heading_heading1' },
            { model: 'heading2', view: 'h2', title: 'Heading 2', class: 'ck-heading_heading2' },
            { model: 'heading3', view: 'h3', title: 'Heading 3', class: 'ck-heading_heading3' },
            { model: 'heading4', view: 'h4', title: 'Heading 4', class: 'ck-heading_heading4' },
            { model: 'heading5', view: 'h5', title: 'Heading 5', class: 'ck-heading_heading5' },
            { model: 'heading6', view: 'h6', title: 'Heading 6', class: 'ck-heading_heading6' },
            { model: 'format', view: 'pre', title: 'Formatted', class: 'ck-format' },
            { model: 'address', view: 'address', title: 'Address', class: 'ck-address' },
        ],        
    },
    fontFamily: {
        options: [
            'default',
            'Arial, Helvetica, sans-serif',
            'Comic Sans MS, cursive',
            'Courier New, Courier, monospace',
            'Georgia, serif',
            'Lucida Sans Unicode, Lucida Grande, sans-serif',
            'Tahoma, Geneva, sans-serif',
            'Times New Roman, Times, serif',
            'Trebuchet MS, Helvetica, sans-serif',
            'Verdana, Geneva, sans-serif'
        ]
    },
    fontSize: {
        options: [
            'default',
            { title: '8', model: '8px' },
            { title: '9', model: '9px' },
            { title: '10', model: '10px' },
            { title: '11', model: '11px' },
            { title: '12', model: '12px' },
            { title: '14', model: '14px' },
            { title: '16', model: '16px' },
            { title: '18', model: '18px' },
            { title: '20', model: '20px' },
            { title: '22', model: '22px' },
            { title: '24', model: '24px' },
            { title: '26', model: '26px' },
            { title: '28', model: '28px' },
            { title: '36', model: '36px' },
            { title: '48', model: '48px' },
            { title: '72', model: '72px' },
        ]
    }
};
const CkEditor = () => {

    return (
        <ContentWrapper>
            <div className="row mx-auto mt-5">

                <Col sm={6}>
                    <h2>CKEditor Implemented By Rajesh</h2>
                    <CKEditor
                        editor={ClassicEditor}
                        config={editorConfiguration}
                        data="<p>Hello from CKEditor 5!</p>"
                        onInit={editor => {
                            // You can store the "editor" and use when it is needed.
                            console.log("Editor is ready to use!", editor);
                            editor.editing.view.change(writer => {
                                writer.setStyle(
                                    "height",
                                    "200px",
                                    editor.editing.view.document.getRoot()
                                );
                            });
                        }}
                        onChange={(event, editor) => {
                            const data = editor.getData();
                            console.log({ event, editor, data });
                        }}
                        onBlur={(event, editor) => {
                            console.log("Blur.", editor);
                        }}
                        onFocus={(event, editor) => {
                            console.log("Focus.", editor);
                        }}
                    />
                </Col>
            </div>
        </ContentWrapper>
    );

}

export default CkEditor;


if i use customize icon i am getting below error
![image](https://user-images.githubusercontent.com/67726510/91554157-922c4980-e8fc-11ea-8b62-e03abac06bf3.png)

My Image location
![image](https://user-images.githubusercontent.com/67726510/91554202-aa03cd80-e8fc-11ea-9cf8-d73821396a76.png)


Thanks in advance

**Comment by FilipTokarski** [comment]
If you want to create a custom plugin with a custom toolbar icon, the easiest and fastest way would be to use `svg` file and change one line in your `webpack.config.js` from:
```js
oneOf: [
            {
              test: /ckeditor5-[^/\\]+[/\\]theme[/\\]icons[/\\][^/\\]+\.svg$/,
              use: [ 'raw-loader' ]
            },
            ...
```
to:
```js
oneOf: [
            {
              test: /\.svg$/,
              use: [ 'raw-loader' ]
            },
            ...
```
AFAIR there is no way to use `png` files for custom toolbar icons, or did I miss something? cc @oleq

**Comment by Rajesh-Thiyagarajan** [comment]
> If you want to create a custom plugin with a custom toolbar icon, the easiest and fastest way would be to use `svg` file and change one line in your `webpack.config.js` from:
> 
> ```js
> oneOf: [
>             {
>               test: /ckeditor5-[^/\\]+[/\\]theme[/\\]icons[/\\][^/\\]+\.svg$/,
>               use: [ 'raw-loader' ]
>             },
>             ...
> ```
> 
> to:
> 
> ```js
> oneOf: [
>             {
>               test: /\.svg$/,
>               use: [ 'raw-loader' ]
>             },
>             ...
> ```
> 
> AFAIR there is no way to use `png` files for custom toolbar icons, or did I miss something? cc @oleq

Thanks for your reply!
As you told
![image](https://user-images.githubusercontent.com/67726510/91711158-6e167580-eb53-11ea-8365-dab7a13f777c.png)

svg icon used
webpack also changed
![image](https://user-images.githubusercontent.com/67726510/91711249-9b632380-eb53-11ea-8f24-58bddb05fd8f.png)

but still throws same error
![image](https://user-images.githubusercontent.com/67726510/91711311-b6359800-eb53-11ea-922f-5d95296efe58.png)

Please do the need full

**Comment by Rajesh-Thiyagarajan** [comment]
> If you want to create a custom plugin with a custom toolbar icon, the easiest and fastest way would be to use `svg` file and change one line in your `webpack.config.js` from:
> 
> ```js
> oneOf: [
>             {
>               test: /ckeditor5-[^/\\]+[/\\]theme[/\\]icons[/\\][^/\\]+\.svg$/,
>               use: [ 'raw-loader' ]
>             },
>             ...
> ```
> 
> to:
> 
> ```js
> oneOf: [
>             {
>               test: /\.svg$/,
>               use: [ 'raw-loader' ]
>             },
>             ...
> ```
> 
> AFAIR there is no way to use `png` files for custom toolbar icons, or did I miss something? cc @oleq

we need add in one more place like below code 
loader.exclude = [
    /\.(js|mjs|jsx|ts|tsx)$/,
    /\.html$/,
    /\.json$/,
    /ckeditor5-[^/\\]+[/\\]theme[/\\]icons[/\\][^/\\]+\.svg$/,
    /ckeditor5-[^/\\]+[/\\]theme[/\\].+\.css$/,
    /\.svg$/
  ];

Now its working fine thank you

**Comment by oleq** [comment]
> AFAIR there is no way to use `png` files for custom toolbar icons, or did I miss something? cc @oleq

You're right.

**Comment by featuriz** [comment]
This worked for me on `"@ckeditor/ckeditor5-core": "^38.0.1",`
```js
        editor.ui.componentFactory.add('timestamp', () => {
            const button = new ButtonView();

            button.set({
                label: 'Timestamp',
                icon: '<svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 512 512"><!--! Font Awesome Free 6.4.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M464 256A208 208 0 1 1 48 256a208 208 0 1 1 416 0zM0 256a256 256 0 1 0 512 0A256 256 0 1 0 0 256zM232 120V256c0 8 4 15.5 10.7 20l96 64c11 7.4 25.9 4.4 33.3-6.7s4.4-25.9-6.7-33.3L280 243.2V120c0-13.3-10.7-24-24-24s-24 10.7-24 24z"/></svg>',
            });

            return button;
        });
```
