### ISSUE TITLE
Paste from Libre Office is not working

### ISSUE THREAD

**Issue by Rajesh-Thiyagarajan** [ckeditor/ckeditor5-react#174]
Pasted Content

Recognition of Achievement
This letter acknowledges the invaluable input you, as a member of our Innovation Team, have provided in the “Implement Rich Text Editor” project covering:
    • Paste from Office feature,
    • Track changes feature,
    1. Comments
    2. Track changes feature,
    3. Comments feature.
The Management would like to hereby thank you for this great accomplishment that was delivered in a timely fashion, up to the highest company standards, and with great results:
Project Phase
Deadline
Status
Phase 1: Market research
2019-10-15
✓
Phase 2: Editor features implementation
2019-10-20
✓
Phase 3: Rollout to Production
2019-10-22
✓
The project that you participated in is of utmost importance to the future success of our platform. We are very proud to share that the CKEditor implementation was a huge success and brought congratulations from both the key Stakeholders and the Customers:
This new editor has totally changed our content creation experience!
— John F. Smith, CEO, The New Web
This letter recognizes that much of our success is directly attributable to your efforts. You deserve to be proud of your achievement. May your future efforts be equally successful and rewarding.
I am sure we will be seeing and hearing a great deal more about your accomplishments in the future. Keep up the good work!

Best regards,
The Management

Output
![image](https://user-images.githubusercontent.com/67726510/91882645-47d6ff80-ec51-11ea-9a0c-11cf0dfd7efc.png)

Expected Result is
With NumberList and BulletList 
Actual Result is
Without NumberList and BulletList is Not Coming

CkEditor Plugins
plugins: [
            PasteFromOffice,
            MSWordNormalizer,
            GoogleDocsNormalizer,
            Essentials,
            Bold,
            Italic,
            Underline,
            Paragraph,
            Heading,
            FontBackgroundColor,
            FontColor,
            FontFamily,
            FontSize,
            RemoveFormate,
            Image,
            ImageCaption,
            ImageResize,
            ImageStyle,
            ImageToolbar,
            ImageUpload,
            Indent,
            IndentBlock,
            List,
            ListUi,
            Link,
            Alignment,
            Table,
            TableToolbar,
            TableProperties,
            TableCellProperties,
        ],

**Comment by FilipTokarski** [comment]
Hi, currently we don't have full support for LibreOffice and there's an open [feature request](https://github.com/ckeditor/ckeditor5/issues/2520) for that. If you would like this feature to be implemented please add :+1: there. I'll close this ticket as a duplicate.
