### ISSUE TITLE
Changing height of the CKeditor

### ISSUE THREAD

**Issue by phkolarov** [ckeditor/ckeditor5-react#175]
Is there any way with some property to change the height of the editor? I'm searching way without CSS.
Thanks.

**Comment by Rajesh-Thiyagarajan** [comment]
> Is there any way with some property to change the height of the editor? I'm searching way without CSS.
> Thanks.

@phkolarov 
try the below code inside the onInit function
 editor.editing.view.change(writer => {
                                    writer.setStyle(
                                        'min-height',
                                        '200px',
                                        editor.editing.view.document.getRoot()
                                    );
                                });

**Comment by FilipTokarski** [comment]
Hi @phkolarov , did the above ☝️  solution resolve your problem?

**Comment by Mgsy** [comment]
I'm closing it due to a lack of activity.
