### ISSUE TITLE
How to add the value with html tag inside the ckeditor5 body

### ISSUE THREAD

**Issue by Rajesh-Thiyagarajan** [ckeditor/ckeditor5-react#176]
![image](https://user-images.githubusercontent.com/67726510/92353535-900d7c00-f0ae-11ea-8189-04f4f0e64214.png)

If the select the mail merge dropdown value
Expected Output
![image](https://user-images.githubusercontent.com/67726510/92353707-ea0e4180-f0ae-11ea-8488-ec56d3a00754.png)

Actual Output
![image](https://user-images.githubusercontent.com/67726510/92354050-92bca100-f0af-11ea-8a82-65bd007be2fc.png)

Code
Custom Plugin

class MailMerge extends Plugin {
        init() {
            const editor = this.editor;

            editor.ui.componentFactory.add("mailMerge", locale => {

                const dropdownView = createDropdown(locale);

                dropdownView.buttonView.set({
                    withText: true,
                    label: "Mail Merge",
                    tooltip: true
                });

                const items = new Collection();

                mailMerge.mail_merge.forEach(data => {
                    items.add({
                        type: "button",
                        model: new Model({
                            withText: true,
                            label: data.display_column_name,
                            value: data.mail_merge_name,
                            tooltip: true
                        })
                    });
                })

                addListToDropdown(dropdownView, items);

                dropdownView.on('execute', (eventInfo) => {
                    const { value } = eventInfo.source;

                    editor.model.change(writer => {

                        // const imageElement = writer.createElement('highlight');
                        // editor.model.insertElement(imageElement, writer.createPositionAt(editor.model.document.getRoot(), 'end'));
                        //Insert the mail merge text to the editor 
                        writer.insertText(value + " ", editor.model.document.selection.getLastPosition());
                        //Move the cursor to the last position of the element
                        writer.setSelection(writer.createPositionAt(editor.model.document.getRoot(), 'end'));

                    });
                   
                });

                return dropdownView;
            })
        }
    }

Mailmerge data
const mailMerge = {"mail_merge": [{ "display_column_name": "Prospects.First Name", "mail_merge_name": "{{Prospects.First Name}}" }, { "display_column_name": "Prospects.Last Name", "mail_merge_name": "{{Prospects.Last Name}}" }, { "display_column_name": "User.First Name", "mail_merge_name": "{{User.First Name}}" }, { "display_column_name": "User.Last Name", "mail_merge_name": "{{User.Last Name}}" }, { "display_column_name": "Prospects.Account Name", "mail_merge_name": "{{Prospects.Account Name}}" }] };

Extra Plugin Config
![image](https://user-images.githubusercontent.com/67726510/92354566-943a9900-f0b0-11ea-96fc-7f5e8fca415d.png)

Toolbar Configuration
![image](https://user-images.githubusercontent.com/67726510/92354652-b92f0c00-f0b0-11ea-8f86-b17726af13a5.png)

One more query 
I want to drag and drop the mail merge output is there possible way to do that ?

Thanks in advance

**Comment by FilipTokarski** [comment]
Hi, I'm not 100% sure if I understand your problem, but if you want to create an inline widget in CKEditor 5, [please see the tutorial in our docs](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-an-inline-widget.html).
If that's not helpful I'll need a more precise description of what you're trying to achieve.

**Comment by Rajesh-Thiyagarajan** [comment]
> Hi, I'm not 100% sure if I understand your problem, but if you want to create an inline widget in CKEditor 5, [please see the tutorial in our docs](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-an-inline-widget.html).
> If that's not helpful I'll need a more precise description of what you're trying to achieve.

we can close this issue fixed by go throughing the link which you sent.
