### ISSUE TITLE
How drag and drop Placeholder and edit the Placeholder in ckeditor5 as same as in ckedtior4

### ISSUE THREAD

**Issue by Rajesh-Thiyagarajan** [ckeditor/ckeditor5-react#177]
Dear Team

@Mgsy 
@Reinmar 
I have done placeholder by go throughing by following link.
https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-an-inline-widget.html

I have requirement to drag and drop the placeholder inside the ckeditor body and also i want to edit the placeholder as same like ckeditor4 below link
https://ckeditor.com/docs/ckeditor4/latest/examples/placeholder.html
while edit the placeholder
![image](https://user-images.githubusercontent.com/67726510/92446865-79d1ef80-f184-11ea-9089-2279e25439dd.png)

Thanks in advance

**Comment by FilipTokarski** [comment]
Hi, currently there is no drag&drop functionality in CKEditor 5, however we have a [feature request for this](https://github.com/ckeditor/ckeditor5/issues/2664). Same as it comes to editable inline widgets, there is a [feature request here](https://github.com/ckeditor/ckeditor5/issues/1729). If you would like those things to be implemented please add 👍  to bump their popularity.
I'll close this ticket as a duplicate.
