### ISSUE TITLE
How to block the file dialog open based on condition

### ISSUE THREAD

**Issue by Rajesh-Thiyagarajan** [ckeditor/ckeditor5-react#179]
Dear Team

I have create the custom plugin for upload files.
![image](https://user-images.githubusercontent.com/67726510/92505434-153d8180-f1d2-11ea-97f4-fab888271171.png)

**when i click on the upload attachment icon below dialog view getting open**
![image](https://user-images.githubusercontent.com/67726510/92505550-41590280-f1d2-11ea-868a-303508a9fe7e.png)

**In this case i would like to block the File dialog window based on condition**
Example
**If i uploaded the three attachments already. i need to show an alert otherwise the FileDialog should open**.

Just give me an example with like below condition, will do that as per condition
let a = 3;
if(a == 3)
 alert()
else
 file dialog should open

Custom Plugin Code

class UploadAttachment extends Plugin {
        init() {

            const editor = this.editor;

            editor.ui.componentFactory.add('uploadAttachment', locale => {

                const view = new FileDialogButtonView(locale);

                view.set({
                    acceptedType: '*',
                });

                view.buttonView.set({
                    label: 'Upload Attachment',
                    icon: UploadAttachmentIcon,
                    tooltip: true
                });

                view.on('done', (evt, file) => {

                   //This block will trigger when we select the file 
                });

                return view;
            });
        }
    }
Added to the toolbar
toolbar:['uploadAttachment']	
Added to extraPlugin
extraPlugins: [
            UploadAttachment
        ],

**Comment by Mgsy** [comment]
Hi! This repository is dedicated to CKEditor 5 react integration issues, as your question seems to be related to CKEditor 5 itself. Could you please open a new ticket in a proper repository (the main [CKEditor 5 repository](https://github.com/ckeditor/ckeditor5/issues))?
