### ISSUE TITLE
There's no control (classes, attrs, tagName) over the <div> on which the editable is enabled

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-react#18]

**Comment by Reinmar** [comment]
Please remember that we'll have to add such configuration to editor's config. Hence, I think it should work here too. So we shouldn't add another, React oriented mechanism here.

**Comment by pomek** [comment]
I'm not sure whether a configuration of that element should be provided together with editor's configuration.

Will we need an additional property? I don't have any idea how it would call.

**Comment by oleq** [comment]
I guess the same applies to https://github.com/ckeditor/ckeditor5-angular, right? 

cc @ma2ciek

**Comment by ma2ciek** [comment]
> I guess the same applies to ckeditor/ckeditor5-angular, right?

Right, I've just added the tagName, but the control over classes and attributes is missing.

**Comment by ma2ciek** [comment]
This feature got no attention in all integrations. IMO we can close all of these feature requests.
