### ISSUE TITLE
Placeholder get removed if we Press the Enter key on the placeholder

### ISSUE THREAD

**Issue by Rajesh-Thiyagarajan** [ckeditor/ckeditor5-react#181]
Dear Team

I have created the placeholder by following the below link.
https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-an-inline-widget.html

In the given demo **if i select the placeholder and press the enter key the placeholder in the ckeditor body** getting removed.Is this bug or not ?

**How to restrict the removing of placeholder.**

after Press the enter key in ckeditor5 docs website
![image](https://user-images.githubusercontent.com/67726510/92594155-61d79a00-f270-11ea-95b9-16d273933aa5.png)

Thanks in advance.

**Comment by FilipTokarski** [comment]
Hi, as the name says it's only a placeholder, so whatever you type there, it will disappear. It's a feature not a bug.  
As it comes to restricting removing, I'm not sure what is the use case here, so maybe you could explain and provide more information about how this feature should behave?

**Comment by Rajesh-Thiyagarajan** [comment]
> Hi, as the name says it's only a placeholder, so whatever you type there, it will disappear. It's a feature not a bug.
> As it comes to restricting removing, I'm not sure what is the use case here, so maybe you could explain and provide more information about how this feature should behave?

Thanks for you reply
In below link the ckeditor4 has opened the popup while press enter on placeholder
https://ckeditor.com/docs/ckeditor4/latest/examples/placeholder.html

But as of now inline edit is not available in ckeditor5. so in my case i would like to block deletion of placeholder while press **Enter** key

**Comment by FilipTokarski** [comment]
Editable inline widgets are not supporeted in CKEditor5. We have however a [feature request for this](https://github.com/ckeditor/ckeditor5/issues/1729), so feel free to add 👍   to the first comment to bump it's popularity.
