### ISSUE TITLE
How to load the Placeholder from server response

### ISSUE THREAD

**Issue by Rajesh-Thiyagarajan** [ckeditor/ckeditor5-react#185]
Hi Team

i have completed the placeholder by following link
https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-an-inline-widget.html

i have an requirement to load the placeholder from the server response

instead of below code i would to like to load the from server response.
![image](https://user-images.githubusercontent.com/67726510/94283850-8e9dd980-ff1f-11ea-916d-1b237253ed2a.png)

**dynamic server response**
[ 'date', 'first name', 'surname' , etc...]

And also i want to load the data from the server whenever placeholder expanding
![image](https://user-images.githubusercontent.com/67726510/94284075-e3415480-ff1f-11ea-9cbe-05e5372ae76c.png)

Thanks in advance

**Comment by Mgsy** [comment]
Hi! This repository is dedicated to CKEditor 5 react integration, while your question is related to CKEditor 5 itself. Please, open the issue in a proper repository (the [CKEditor 5 main repository](https://github.com/ckeditor/ckeditor5/issues))

**Comment by ahtashamabbasse** [comment]
@Rajesh-Thiyagarajan can you please provide the code snippet of how did you integrate it inside the ReactJs?

**Comment by Rajesh-Thiyagarajan** [comment]
`class Placeholder extends Plugin {
        static get requires() {
          return [PlaceholderEditing, PlaceholderUI];
        }
      }

      class PlaceholderCommand extends Command {
        execute({ value }) {
          const editor = this.editor;

      if (ref.current.attributes.class.value.includes('focusing')) {
        ref.current.value += value;
        ref.current.focus();
      } else {
        editor.model.change((writer) => {
          // Create a <placeholder> elment with the "name" attribute...
          const placeholder = writer.createElement('placeholder', {
            name: value,
          });
          // ... and insert it into the document.
          editor.model.insertContent(placeholder);
          //after inserting the mail merge value to focus the ckeditor body
          editor.editing.view.focus();
        });
      }
    }
    refresh() {
      const model = this.editor.model;
      const selection = model.document.selection;

      const isAllowed = model.schema.checkChild(
        selection.focus.parent,
        'placeholder'
      );
    
          this.isEnabled = isAllowed;
        }
      }
    
      class PlaceholderUI extends Plugin {
        init() {
      const editor = this.editor;
      const t = editor.t;
      const placeholderNames = editor.config.get('placeholderConfig.types');

      // The "placeholder" dropdown must be registered among the UI components of the editor
      // to be displayed in the toolbar.
      editor.ui.componentFactory.add('placeholder', (locale) => {
        const dropdownView = createDropdown(locale);

        // Populate the list in the dropdown with items.
        addListToDropdown(
          dropdownView,
          getDropdownItemsDefinitions(placeholderNames)
        );

        dropdownView.buttonView.set({
          // The t() function helps localize the editor. All strings enclosed in t() can be
          // translated and change when the language of the editor changes.
          label: t('Place holder'), //Placeholdername
          tooltip: true,
          withText: true,
        });

        // Disable the placeholder button when the command is disabled.
        const command = editor.commands.get('placeholder');
        dropdownView.bind('isEnabled').to(command);

        // Execute the command when the dropdown item is clicked (executed).
        this.listenTo(dropdownView, 'execute', (evt) => {
          editor.execute('placeholder', { value: evt.source.value });
        });

            return dropdownView;
          });
        }
      }

      function getDropdownItemsDefinitions(placeholderNames) {
        const itemDefinitions = new Collection();
    
        for (const json of placeholderNames) {
          const definition = {
            type: 'button',
            model: new Model({
              value: json.name, // server response name of the object
              label: json.value,// server response valueof the object
              withText: true,
            }),
          };
          // Add the item definition to the collection.
          itemDefinitions.add(definition);
        }
    
        return itemDefinitions;
      }

      class PlaceholderEditing extends Plugin {
        static get requires() {
          return [Widget];
        }
    
        init() {
          this._defineSchema();
          this._defineConverters();
    
          this.editor.commands.add(
            'placeholder',
            new PlaceholderCommand(this.editor)
          );

      this.editor.editing.mapper.on(
        'viewToModelPosition',
        viewToModelPositionOutsideModelElement(
          this.editor.model,
          (viewElement) => viewElement.hasClass('placeholder')
        )
      );

      this.editor.config.define('placeholderConfig', {
        types: serverresponse, //placeholder server response
      });
    }

    _defineSchema() {
      const schema = this.editor.model.schema;

      schema.register('placeholder', {
        // Allow wherever text is allowed:
        allowWhere: '$text',
        // The placeholder will act as an inline node:
        isInline: true,
        // The inline widget is self-contained so it cannot be split by the caret and it can be selected:
        isObject: true,
        // The placeholder can have many types, like date, name, surname, etc:
        allowAttributes: ['name'],
      });
    }

    _defineConverters() {
      const conversion = this.editor.conversion;

      conversion.for('upcast').elementToElement({
        view: {
          name: 'span',
          classes: ['placeholder'],
        },
        model: (viewElement, { writer: modelWriter }) => {
          // Extract the "name" from "{name}".
          const name = viewElement.getChild(0).data.slice(1, -1);

          return modelWriter.createElement('placeholder', { name });
        },
      });

      conversion.for('editingDowncast').elementToElement({
        model: 'placeholder',
        view: (modelItem, { writer: viewWriter }) => {
          const widgetElement = createPlaceholderView(modelItem, viewWriter);

          // Enable widget handling on a placeholder element inside the editing view.
          return toWidget(widgetElement, viewWriter);
        },
      });

      conversion.for('dataDowncast').elementToElement({
        model: 'placeholder',
        view: (modelItem, { writer: viewWriter }) =>
          createPlaceholderView(modelItem, viewWriter),
      });

      // Helper method for both downcast converters.
      function createPlaceholderView(modelItem, viewWriter) {
        const name = modelItem.getAttribute('name');

        const placeholderView = viewWriter.createContainerElement('span', {
          class: 'mr-2',
        });
        // Insert the placeholder name (as a text).
        const innerText = viewWriter.createText(name);
        viewWriter.insert(
          viewWriter.createPositionAt(placeholderView, 0),
              innerText
            );
            return placeholderView;
          }
        }
      }`


**Note : You have to load the placeholder from server before Ckeditor component load , then only you are able to achieve**
My placeholder response will be array of object.

Thanks

**Comment by ahtashamabbasse** [comment]
Thank you so much @Rajesh-Thiyagarajan for providing the code snippet I tried the same code according to the documentation, but getting the following errors on importing the Plugins. 

`import Plugin from '@ckeditor/ckeditor5-core/src/plugin';`

These are the thing which I'm importing.

```
import React, { useContext, useEffect } from 'react';
import { CKEditor } from '@ckeditor/ckeditor5-react';
import DecoupledEditor from '@ckeditor/ckeditor5-build-decoupled-document';
import './styles.scss';
import Plugin from '@ckeditor/ckeditor5-core/src/plugin';
import { OfferingDetailsContext } from '../offeringDetails.Context';
import { Spinner } from '../../../components/Snipper';
```


![image](https://user-images.githubusercontent.com/25702074/120147271-d3d98000-c1ff-11eb-8772-ae1a21f5cae8.png)

**Comment by Rajesh-Thiyagarajan** [comment]
> Thank you so much @Rajesh-Thiyagarajan for providing the code snippet I tried the same code according to the documentation, but getting the following errors on importing the Plugins.
> 
> `import Plugin from '@ckeditor/ckeditor5-core/src/plugin';`
> 
> These are the thing which I'm importing.
> 
> ```
> import React, { useContext, useEffect } from 'react';
> import { CKEditor } from '@ckeditor/ckeditor5-react';
> import DecoupledEditor from '@ckeditor/ckeditor5-build-decoupled-document';
> import './styles.scss';
> import Plugin from '@ckeditor/ckeditor5-core/src/plugin';
> import { OfferingDetailsContext } from '../offeringDetails.Context';
> import { Spinner } from '../../../components/Snipper';
> ```
> 
> ![image](https://user-images.githubusercontent.com/25702074/120147271-d3d98000-c1ff-11eb-8772-ae1a21f5cae8.png)

Yes , i am also faced this duplicate issue.
Your **yarn.lock ** will contains multiple versions of ckeditor, that's why it's throwing this error.
so delete your yarn.lock file
and give yarn install and yarn start.

**Comment by ahtashamabbasse** [comment]
I tried your guideline but still getting the same error, do you have few spare minutes so we can move to zoom call. The deadline is about to end and we need to launch this feature ASAP.

**Comment by Rajesh-Thiyagarajan** [comment]
can we have in skype ?

**Comment by ahtashamabbasse** [comment]
Yes share your skype username

**Comment by Rajesh-Thiyagarajan** [comment]
live:rajeshbehalf
Name : Rajesh
