### ISSUE TITLE
Why won't it let me import a plugin simply without needing to build from source??

### ISSUE THREAD

**Issue by pRoy24** [ckeditor/ckeditor5-react#187]
Like seriously....ES6 was released like 3 years ago ...hello !!!
Why can't I just import another toolbar plugin, why is react integration such a pain in the back?

**Comment by pRoy24** [comment]
ok so after banging my head even after following the exact steps in https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html for 6 billable hours, I figured out that just adding the package as a dev dependancy won't do. Even the version must match the exact versions of the other dev dependancies.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. I'm sorry to hear that you have so many problems with the editor, but I'm not quite sure I understand the purpose of this ticket though.
  
If you have  problems with [React integration](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html) and docs won't help, please provide a step-by-step description of the problem and share your editor configuration, so we could look into this.  
  
If you want to learn more about the internals, you can see the docs on [editor architecture](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/architecture/intro.html) and [custom builds](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/custom-builds.html).
  
But if that's not the case and you have some ideas on how to improve the existing solutions, please create a valid feature/improvement request and share your ideas there.
