### ISSUE TITLE
Review docs and release the 3.0 version

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/ckeditor5-react#188]
PR for docs is created in ckeditor/ckeditor5#8053.

The potential blocker was reported in #186.

**Comment by pomek** [comment]
https://github.com/ckeditor/ckeditor5-react/releases/tag/v3.0.0

**Comment by AnnaTomanek** [comment]
The new version of the React integration has been released, the docs are now on their way to our prod environment. Congratulations! :tada:
