### ISSUE TITLE
Support Document editor

### ISSUE THREAD

**Issue by weasteam** [ckeditor/ckeditor5-react#189]
It looks like the Classic editor is supported, but the Document editor is not supported.

Would you please add the support to Document editor?

https://ckeditor.com/docs/ckeditor5/latest/examples/builds/document-editor.html

**Comment by FilipTokarski** [comment]
Hi, please check the docs on React integration, espacially [this part](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#using-the-document-editor-build).

**Comment by weasteam** [comment]
woo, got it. Thank you so much.
