### ISSUE TITLE
return 'editor' for onReady function

### ISSUE THREAD

**Issue by weasteam** [ckeditor/ckeditor5-react#190]
```
				setTimeout( () => {
					if ( this.props.onReady ) {
						this.props.onReady( this.editor );
					}
				} );
```
The onReady function only returns the `this.editor`. `DecoupledEditor ` needs to append the toolbar from `editor` object. It would be great to also return the `editor`.

Update the above code to

```
				setTimeout( () => {
					if ( this.props.onReady ) {
						this.props.onReady( this.editor, editor );
					}
				} );
```

See more at https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/ui/document-editor.html

**Comment by FilipTokarski** [comment]
Hi, if you want to add a document editor in React, I answerd you in [the other ticket you created](https://github.com/ckeditor/ckeditor5-react/issues/189). Please do not add multiple tickets that concern the same issue. I'm closing this as a duplicate.
