### ISSUE TITLE
Inline style for a div element

### ISSUE THREAD

**Issue by myYensid** [ckeditor/ckeditor5-react#195]
Hi,

I need to show a div element with some custom styling in between the paragraphs. When ever the user double enter I need to show some divider.

Could you please let me know how to add a div with inline styling.

Also, can you share an example  where CKEditor works with svgs. 

Thanks,
Yensid

**Comment by FilipTokarski** [comment]
Hi, sorry for the late reply, this ticket somehow slipped our attention. CKEditor 5 has a custom data model and it's not possible to create `div` elemens out-of-the-box. It preserves only elements registered in [schema](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_schema-Schema.html)  by [converting](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_conversion_conversion-Conversion.html) elements between [view and model](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/architecture/editing-engine.html).  
To register a `div` element in [schema](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_schema-Schema.html) and add [conversion](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_conversion_conversion-Conversion.html) you can use the code below. However, keep in mind that this is a basic implementation which introduces `div` to the editor. You should handle all the behaviour of this element and attributes on your own.

```js
editor.model.schema.register( 'div', {
    inheritAllFrom: '$block'
} );
editor.conversion.elementToElement( {
    model: 'div',
    view: 'div'
} );
```
You can refer to docs and further adjust it to your particular needs. [Here you can read more about conversion](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/conversion/conversion-introduction.html).  
  
As it comes to svgs, I'm not sure I understand the question. Could you clarify?  
Meanwhile you can read some docs on [customizing icons](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/faq.html#how-to-customize-the-ckeditor-5-icons) and [svg icons](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/development-environment.html#svg-icons).
