### ISSUE TITLE
Why i do not import  ckeditor5-react package to my project. 

### ISSUE THREAD

**Issue by xiang510** [ckeditor/ckeditor5-react#198]
Hi, buddy. Someone  got seem this problem?

"webpack": "3.8.1"
"babel-loader": "^8.1.0",
webpack config: {
            test: /\.(js|jsx|mjs)$/,
            include: paths.appSrc,
            loader: require.resolve("babel-loader"),
            options: {
              // This is a feature of `babel-loader` for webpack (not Babel itself).
              // It enables caching results in ./node_modules/.cache/babel-loader/
              // directory for faster rebuilds.
              cacheDirectory: true,
            },
          },
![image](https://user-images.githubusercontent.com/19361229/99793337-78994780-2b63-11eb-8c5e-558cb97ed3f6.png)

**Comment by Mgsy** [comment]
Hi, it looks like there might be an issue with your webpack configuration. Did you follow our [React integration guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html)?

**Comment by xiang510** [comment]
Yes, I did. I tried a lot of times, but it's not loading successfully yet. I am confused.
My webpack version is  3.8.1, babel version is 7.X
`
{
"devDependencies": {
    "@babel/core": "^7.12.3",
    "@babel/plugin-transform-runtime": "^7.12.1",
    "@babel/preset-env": "^7.12.1",
    "@babel/preset-react": "^7.12.5",
    "@ckeditor/ckeditor5-dev-utils": "^23.6.1",
    "@ckeditor/ckeditor5-theme-lark": "^23.1.0",
    "babel-loader": "^8.0.0-beta.0",
    "babel-plugin-transform-runtime": "^6.23.0",
    "clean-webpack-plugin": "0.1.19",
    "css-loader": "^0.23.1",
    "file-loader": "^1.1.11",
    "html-webpack-plugin": "^2.30.1",
    "raw-loader": "^4.0.2",
    "style-loader": "^0.23.1",
    "webpack": "^3.8.1"
  },
  "dependencies": {
    "@ckeditor/ckeditor5-build-classic": "^23.1.0",
    "@ckeditor/ckeditor5-react": "^3.0.0",
    "babel-runtime": "^6.26.0",
    "react": "^16.13.1",
    "react-dom": "^16.13.1"
  }
}

`

**Comment by xiang510** [comment]
It`s running when I import like this.
![image](https://user-images.githubusercontent.com/19361229/99892741-06377d00-2cb3-11eb-8a29-3fd57a409a48.png)
 But I can`t import the file from the dist path. Is it the problem in the build step? It's not Webpack can`t resolve the min javascript file?

**Comment by xiang510** [comment]
Like this.
`
import { CKEditor } from './ckeditor/ckeditor5-react/src/';
import ClassicEditor from '@ckeditor/ckeditor5-build-classic';
`

**Comment by xiang510** [comment]
Yep, I found the reason.   If you get a similar problem, Attention your config file. 
Look at it.
`
{
            test: /\.(js|jsx|mjs)$/,
            include: [
              path.resolve(
                __dirname,
                "../node_modules/@ckeditor/ckeditor5-react"
              ),
              paths.appSrc,
            ],
            loader: require.resolve("babel-loader"),
            options: {
              cacheDirectory: true,
            },
          },
`

**Comment by jeffrey-fu** [comment]
> Yep, I found the reason. If you get a similar problem, Attention your config file.
> Look at it.
> `{ test: /\.(js|jsx|mjs)$/, include: [ path.resolve( __dirname, "../node_modules/@ckeditor/ckeditor5-react" ), paths.appSrc, ], loader: require.resolve("babel-loader"), options: { cacheDirectory: true, }, },`

nice！I'm following [React integration guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html) ,but got the same problem.
Why builded file also need babel-loader？

 I tried a lot of times. 

- try [source-map-loader](https://webpack.js.org/loaders/source-map-loader/) to handle dist file, but got **this.getOptions** is undefined

### My solution just use it (ckeditor is very nice 👍)

- webpack config: add [externals](https://webpack.js.org/configuration/externals/)
   
```javascript
externals: {
    'ckeditor': 'CKEditor',
    'inlineEditor': 'InlineEditor',
  }
```

- import dist file in `index.html`

```
<script src="/ckeditor5/ckeditor.js"></script>
<script src="/ckeditor5/inlineEditor.js"></script>
```
the `ckeditor.js` build file  from [@ckeditor/ckeditor5-react](https://unpkg.com/browse/@ckeditor/ckeditor5-react@3.0.2/dist/)
the `inlineEditor.js` build file  from [CKEditor 5 online builder](https://ckeditor.com/ckeditor-5/online-builder/)

- import CKEditor

```
import React from 'react';
import { CKEditor } from 'ckeditor';
import InlineEditor from 'inlineEditor';

export default function RichTextEditor() {
  return (
    <CKEditor
      editor={InlineEditor}
      config={{
        toolbar: {
          items: [
            'bold',
            'italic',
          ],
        },
      }}
      data="<p>Hello from CKEditor 5!</p>"
      onChange={(event, editor ) => {
          const data = editor.getData();
          console.log({ event, editor, data });
      }}
    />
  );
}
```

share my solution and hope it useful.😄
