### ISSUE TITLE
Registry returned 404 for GET on https://registry.npmjs.org/cke5-react

### ISSUE THREAD

**Issue by RaulEscobarRivas** [ckeditor/ckeditor5-react#2]
Hello, 

When trying to `npm install --save cke5-react @ckeditor/ckeditor5-build-classic` I get the following error:

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/cke5-react
npm ERR! 404
npm ERR! 404  'cke5-react' is not in the npm registry.

Could you review this?

Thanks in advance

**Comment by Reinmar** [comment]
This package wasn't published yet. And it will be called `ckeditor5-react` or `@ckeditor/ckeditor5-react`.

For now, you can play with the code in this repository. npm allows installing packages straight from git.

**Comment by RaulEscobarRivas** [comment]
Hello, 

after installing, when trying to reenact the code example provided by you guys, I keep getting this error:

 Module not found: Error: Can't resolve 'cke5-react' in '...........'


Any pointers?

thanks in advance

**Comment by Reinmar** [comment]
We're going to publish the first dev preview of this package in a couple of days. It will be called `@ckeditor/ckeditor5-react`. See #5.

**Comment by cola9k** [comment]
i can't !!! same here.

**Comment by pomek** [comment]
The first version has just been published. 

Now using `npm install @ckeditor/ckeditor5-react` will install the package in version `1.0.0-beta.1`.

The feedback is welcome.
