### ISSUE TITLE
[CKEditor] TypeError: t._clone is not a function

### ISSUE THREAD

**Issue by trungpham71198** [ckeditor/ckeditor5-react#207]
<img width="1329" alt="Screen Shot 2020-12-28 at 14 58 47" src="https://user-images.githubusercontent.com/58923438/103199388-55f60d80-491d-11eb-8001-de3228146dec.png">

<img width="470" alt="Screen Shot 2020-12-27 at 15 47 44" src="https://user-images.githubusercontent.com/58923438/103167117-def84080-485a-11eb-930d-57a09f9a5333.png">

<img width="472" alt="Screen Shot 2020-12-27 at 15 47 24" src="https://user-images.githubusercontent.com/58923438/103167119-e6b7e500-485a-11eb-9240-7c6c19d3a99f.png">

Can anyone help me fix this? Thank you.

**Comment by LukaszGudel** [comment]
Hello. I can see that you are following our [React integration guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html) but I can not recreate this error. Could you please provide steps to reproduce your issue?
