### ISSUE TITLE
plugins unavailable only for reactjs

### ISSUE THREAD

**Issue by JefterRocha** [ckeditor/ckeditor5-react#208]
i created my own custom build in the [online-builder](https://ckeditor.com/ckeditor-5/online-builder/) and works normally when viewing through `sample/index.html` (yarn start), however some plugins are not visible when using the custom build in ckeditor5-react. Here is my config and the error return in the browser.

config(same for React component and sample/index.html)
```
{
   ....
    toolbar: {
        items: [
             ....
            "subscript",
            "superscript",
            "|",
            "specialCharacters",
            "|",
            "horizontalLine",
            "pageBreak",
            "insertTable",
            "|",
            "exportPdf",
             ....
        ],
    },
    table: {
        contentToolbar: [
            "tableColumn",
            "tableRow",
            "mergeTableCells",
            "tableCellProperties",
            "tableProperties"
        ]
    },
    ....
}
```
warnings on the browser console
```
toolbarview-item-unavailable {name: "tableCellProperties"} ───────────────┐
                                                                          │ This repeats for each element listed below
Read more: https://ckeditor.com/...#error-toolbarview-item-unavailable ───┘ 
tableProperties
subscript
superscript
specialCharacters
horizontalLine
pageBreak
exportPdf
```

my React component

```
import { CKEditor } from "@ckeditor/ckeditor5-react";
import Editor from "ckeditor5/build/ckeditor" // added following #integrating-a-build-from-the-online-builder tutorial;

export function ContentEditor() {
    return <CKEditor
        config={myConfig}
        onReady={handleReady}
        onChange={handleChange}
        editor={Editor}
        data={data}
    />
}
```

**Comment by LukaszGudel** [comment]
Hello. It looks like some plugins are missing in your build. Please, make sure that those plugins are loaded. You can check it by looking at the editor object in browser console after logging it:

```javascript
 onReady = { editor => {
       console.log( 'Editor is ready to use!', editor );
       } }
```

List of plugins will be available in `plugins._availablePlugins`. 

If you have those plugins loaded but the issue still occurs then I would suggest checking Editor build import. Your Editor path is different than in [this guide.](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#integrating-a-build-from-the-online-builder)
