### ISSUE TITLE
config : {allowedContent,  extraAllowedContent } doesn't working 

### ISSUE THREAD

**Issue by MicroAsif** [ckeditor/ckeditor5-react#209]
I have some div and inline styling on html, I have configured the **allowedContent** **extraAllowedContent**  but seems like it's not working. any help will be great.

**Comment by FilipTokarski** [comment]
Hi, in order to look into this, we'll need more information about the issue. Please share your config and step-by-step description of what you did and what is wrong. It would be also very helpful if you could share some live demo of the editor.

**Comment by FilipTokarski** [comment]
Hi, CKEditor 5 has its own [data model](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/architecture/editing-engine.html) and if you want to specify your own elements, you need to register them in [schema](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/architecture/editing-engine.html#schema). See also [FAQ on allowedContent](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/faq.html#why-does-the-editor-filter-out-my-content-styles-classes-elements-where-is-configallowedcontent-true).
