### ISSUE TITLE
Adding CKEditor 5 plugins in React Application

### ISSUE THREAD

**Issue by rashmithadas** [ckeditor/ckeditor5-react#210]
Hi, 
When I  am trying to add some CKEditor5 plugins like , Table or Link, fontColor  plugins its giving the below errors after installing the plugins-

#### ./node_modules/@ckeditor/ckeditor5-core/src/plugincollection.js
Attempted import error: 'logError' is not exported from '@ckeditor/ckeditor5-utils/src/ckeditorerror'.

#### ./node_modules/@ckeditor/ckeditor5-core/src/editor/editor.js
Module not found: Can't resolve '@ckeditor/ckeditor5-engine/src/view/stylesmap' in 'D:\Editor1\Working-Editor\React-Editor\node_modules\@ckeditor\ckeditor5-core\src\editor'

Note : followed the official docs to install the plugins but not a luck to work
https://ckeditor.com/docs/ckeditor5/latest/features/link.html 

Anyone have any idea or any solution is most appreciate.

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. Did you also follow the guide about [React integration](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html)?
