### ISSUE TITLE
How to implement online build inside ckeditor

### ISSUE THREAD

**Issue by harshsbais** [ckeditor/ckeditor5-react#215]
I made an online build to add few more plugins and Base64Image uploader. 
I wrote the code like this:-
`import Editor from 'ckeditor5-custom-build/build/ckeditor';`
`import { CKEditor } from '@ckeditor/ckeditor5-react';`
`<CKEditor
                                editor={Editor}
                                name="content"
                                data={content}
                                onChange={(event, editor) => {
                                    settingQuestion(event, editor);
                                }}
                            />`

But I am getting this error
CKEditorError: ckeditor-duplicated-modules

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. First, please make sure you followed the docs on [adding build from Online BUilder to React](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#integrating-a-build-from-the-online-builder). If this doesn't help, we'll need more information to reproduce the issue ( precise steps, your editor configuration, package.json, etc. ).

**Comment by harshsbais** [comment]
hey thanks for the help, was facing some issues in implementing using online build so used local build to solve the issue.
the editor is working fine but can you please tell me how to deploy it on aws since I added the build using 
`npm install --save <LOCAL DIRECTORY>/ckeditor5-build-classic` but I did not upload the build so aws is showing error in logs

**Comment by harshsbais** [comment]
was able to do it thanks for the help
