### ISSUE TITLE
Trying to integrate a custom build into my React app I get websocketgateway-missing-token.

### ISSUE THREAD

**Issue by davesag** [ckeditor/ckeditor5-react#216]
Trying to integrate a custom build into my React app I get `websocketgateway-missing-token` Error.

Noob question: I have an editor key, have generated a developer token and have generated editor token url, editor upload url, and web socket url, but I can't find anywhere in the docs that shows how to use those values?  Do they go in the context config somehow? Do I supply them as props to each editor? How do I use these values?

**Comment by Mgsy** [comment]
Hi! `tokenUrl`, `uploadUrl` and `webSocketUrl` are a part of the Cloud Services configuration, so these values should be passed to the `cloudServices` configuration object in your editor (it could be done in your custom build configuration). See more details [here](https://ckeditor.com/docs/ckeditor5/latest/api/module_cloud-services_cloudservices-CloudServicesConfig.html). Additionally, please see our [real-time collaboration integration guide](https://ckeditor.com/docs/ckeditor5/latest/features/collaboration/real-time-collaboration/real-time-collaboration-integration.html) to learn more about the basic concepts. You might also find useful our [CKEditor 5 + React + RTC integration example](https://github.com/ckeditor/ckeditor5-collaboration-samples/tree/master/real-time-collaboration-for-react).

Apart from that, note that real-time collaboration is our commercial feature and this repository is dedicated to the open-source part of the project, so in case of any further questions about premium features, reach us through our [support channel](https://ckeditor.com/contact/). Our dedicated support team will be happy to help you.

**Comment by davesag** [comment]
> Hi! `tokenUrl`, `uploadUrl` and `webSocketUrl` are a part of the Cloud Services configuration, so these values should be passed to the `cloudServices` configuration object in your editor (it could be done in your custom build configuration). See more details [here](https://ckeditor.com/docs/ckeditor5/latest/api/module_cloud-services_cloudservices-CloudServicesConfig.html). Additionally, please see our [real-time collaboration integration guide](https://ckeditor.com/docs/ckeditor5/latest/features/collaboration/real-time-collaboration/real-time-collaboration-integration.html) to learn more about the basic concepts. You might also find useful our [CKEditor 5 + React + RTC integration example](https://github.com/ckeditor/ckeditor5-collaboration-samples/tree/master/real-time-collaboration-for-react).
> 
> Apart from that, note that real-time collaboration is our commercial feature and this repository is dedicated to the open-source part of the project, so in case of any further questions about premium features, reach us through our [support channel](https://ckeditor.com/contact/). Our dedicated support team will be happy to help you.

Thanks I'm still not able to get this working so have contacted your support channel.
