### ISSUE TITLE
how to use Alignment

### ISSUE THREAD

**Issue by zilkenberg22** [ckeditor/ckeditor5-react#217]
import React, { Component } from "react";

import ClassicEditor from "@ckeditor/ckeditor5-editor-classic/src/classiceditor";
import CKEditor from "@ckeditor/ckeditor5-react";
import Essentials from "@ckeditor/ckeditor5-essentials/src/essentials";
import Bold from "@ckeditor/ckeditor5-basic-styles/src/bold";
import Italic from "@ckeditor/ckeditor5-basic-styles/src/italic";
import Paragraph from "@ckeditor/ckeditor5-paragraph/src/paragraph";
import Alignment from "@ckeditor/ckeditor5-alignment/src/alignment";

const editorConfiguration = {
    plugins: [Essentials, Bold, Italic, Paragraph, Alignment],
    toolbar: ["bold", "italic"],
};

class App extends Component {
    render() {
        return (
` <div className="App">`
               ` <h2>Using CKEditor 5 from source in React</h2>`
                `<CKEditor`
                    `editor={ClassicEditor}`
                    `config={editorConfiguration}`
                    `data="<p>Hello from CKEditor 5!</p>"`
                  `  onChange={(event, editor) => {`
                      `  const data = editor.getData();`
                       ` console.log({ event, editor, data });`
                  `  }}`
                `/>`
           ` </div>`
        );
    }
}

export default App;

![Screenshot from 2021-02-18 16-40-54](https://user-images.githubusercontent.com/33345651/108329463-2ae6b680-7208-11eb-9132-b84461f3cc7a.png)

HOW TO FIX

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. First, please make sure that you follow docs on [integrating editor in React from source](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#integrating-ckeditor-5-built-from-source) and that your webpack configuration is correct. 
[Duplicated modules error](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-duplicated-modules) may also suggest that some of the editor plugins that you import ( maybe Alignment in this case? ) have different version. The current one is `25.0.0` and I suggest to keep them all up to date.  
  
If that does not help, we'll need more information about this issue ( steps to reproduce, `package.json` content, webpack configuration, etc. ).

**Comment by zilkenberg22** [comment]
@FilipTokarski [https://codesandbox.io/s/ckeditor-5-react-alignment-kwm8k?file=/src/views/Test.js](url)  check this

**Comment by FilipTokarski** [comment]
You're importing editor build instead editor class, hence the error. There are also some dependencies and webpack file missing. As I said before, please make sure you follow the docs on [building editor from source in React](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#integrating-ckeditor-5-built-from-source).  
If you're still not sure why it works this way and what's the difference between build and class, check docs on [installing plugins](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html).
