### ISSUE TITLE
Providing own header in CKFinder

### ISSUE THREAD

**Issue by aXenDeveloper** [ckeditor/ckeditor5-react#218]
Hi,
I have this code:
```
<CKEditor
    editor={ClassicEditor}
    onChange={(event, editor) => {
        setInputDesc(editor.getData());
    }}
   config={{
       ckfinder: {
           uploadUrl: `http://localhost:8000/upload-image`
       }
}}
/>
```
It's works, but without no headers.
My link with API for uploading files requires a CSRF key, which I can provide with the header.

I'm trying this config:
```
ckfinder: {
    uploadUrl: `http://localhost:8000/upload-image`,
    headers: {
        CSRF_key: 'key'
    }
}
```
But I have a error 401 (Unauthorized).

How can I properly add a header to a request?

**Comment by FilipTokarski** [comment]
Hi, unfortunately there is no default way to add headers to CKFinder.  Apart from that, CKFinder has its own [CSRF protection](https://ckeditor.com/docs/ckeditor5/latest/api/module_adapter-ckfinder_utils.html#static-function-getCsrfToken). Please see [this discussion](https://github.com/ckeditor/ckeditor5/issues/887) for more details.

**Comment by aXenDeveloper** [comment]
I understand. Thanks for the reply!
