### ISSUE TITLE
The tooltip language is not english by default and the language is not changing when I provided 'en' in editorConfig

### ISSUE THREAD

**Issue by mohananagavenkat** [ckeditor/ckeditor5-react#221]
I am trying to integrate the CK editor in one of my react projects. The config is as follows

```js
const editorConfiguration = {
 defaultLanguage: 'en',
 language: 'en'
  toolbar:  [
      'heading', 'MathType', 'ChemType',
      '|',
      'bold',
      'italic',
      'link',
      'bulletedList',
      'numberedList',
      'imageUpload',
      'mediaEmbed',
      'insertTable',
      'blockQuote',
      'undo',
      'redo',
    ],
}
```

But the tooltip text is loading in different language than 'en'. 

Attaching the screenshot for the same

<img width="1680" alt="Screenshot 2021-02-27 at 3 55 46 PM" src="https://user-images.githubusercontent.com/30862450/109384680-7b4eca00-7914-11eb-986b-406e104df028.png">

**Comment by FilipTokarski** [comment]
Hi, did you follow [docs on localization in React component](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#localization)?
