### ISSUE TITLE
How do I save and retrieve text and image data content from ckeditor 5  to firebase databse using react js.  

### ISSUE THREAD

**Issue by dhirajverma** [ckeditor/ckeditor5-react#222]

**Comment by FilipTokarski** [comment]
Hi, as it comes to retrieving data from CKEditor, please check docs on [interacting with the editor](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/basic-api.html#interacting-with-the-editor). You might also be interested in [simple upload adapter](https://ckeditor.com/docs/ckeditor5/latest/features/image-upload/simple-upload-adapter.html), which you can use with any backend that you want.
 
As it comes to Firebase, I'm affraid it's not related strictly to CKEditor, but your React application in general. Hence I cannot provide the proper answer for this.
