### ISSUE TITLE
DecoupledEditor how to display the page effect?

### ISSUE THREAD

**Issue by andrew2558** [ckeditor/ckeditor5-react#226]
DecoupledEditor how to display the page effect, just like the official website, my display and ClassicEditor the same

official website:
![image](https://user-images.githubusercontent.com/25080605/111595998-aa67a580-8807-11eb-8ad3-5a41b8bd0fdb.png)

my editor:
![image](https://user-images.githubusercontent.com/25080605/111596455-25c95700-8808-11eb-9e60-5cd25cb17de9.png)

my code:
```
return (
    <div>
      <div id="toolbar-container"></div>
      <CKEditor
        editor={DecoupledEditor}
        data="<p>Content</p>"
        config={editorConfiguration}
        onReady={(editor) => {
          const toolbarContainer = document.querySelector("#toolbar-container");
          toolbarContainer.appendChild(editor.ui.view.toolbar.element);
          window.editor = editor;
          console.log("Editor is ready to use!", editor);
        }}
        onChange={(event, editor) => {
          const data = editor.getData();
          console.log({ event, editor, data });
        }}
        onBlur={(event, editor) => {
          console.log("Blur.", editor);
          console.log(editor.getData());
        }}
        onFocus={(event, editor) => {
          console.log("Focus.", editor);
        }}
      />
    </div>
  );
```

**Comment by FilipTokarski** [comment]
Hi, please check docs on using [decoupled editor in React](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#using-the-document-editor-build) and also you'll need to apply [document editor styles](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/ui/document-editor.html#styles).

**Comment by andrew2558** [comment]
thank you very much @FilipTokarski
