### ISSUE TITLE
Add (partial) TypeScript typings

### ISSUE THREAD

**Issue by neongreen** [ckeditor/ckeditor5-react#231]
Today I spent quite a while tracking down a bug — it turned out that the ckeditor5-react component does not support the `style` property. Even a partial TS declaration file (just a list of component properties) would have prevented this bug for me and saved some time.

**Comment by ma2ciek** [comment]
Hi @neongreen,

After a short discussion within the team, we decided that it's a good idea to include these TS declaration files that could document the API. I'm not sure when will it happen, but we'll track this issue.

**Comment by djakaitis** [comment]
Is there any update on the implementation of TS declarations?

**Comment by pomek** [comment]
Closing as done. See: https://github.com/ckeditor/ckeditor5-react/releases/tag/v6.0.0.
