### ISSUE TITLE
Clearing textarea after submitting?

### ISSUE THREAD

**Issue by ManuC84** [ckeditor/ckeditor5-react#232]
Sorry if this is a dumb question, but how can I clear the textarea after the user submits the form? I know I can access editor.getData() from within onChange prop in the editor but how can I access it from my handleSubmit function? I'm using the classic editor in React.

**Comment by pomek** [comment]
You can store the editor as a property using `onReady` callback:

```jsx
class AppComponent extends React.Component {
	constructor( state ) {
		super( state );
	
		// An editor instance after its initialization.
		this.editor = null;
	}

	render() {
		return ( <CKEditor editor={ ClassicEditor } onReady={ editor => {
			// From now, `this.editor` can be used anywhere inside the `<App />` component.
			this.editor = editor;
		} /> );
	}
}
```

**Comment by Bahajons** [comment]
i
