### ISSUE TITLE
Change the UI language

### ISSUE THREAD

**Issue by lucre74** [ckeditor/ckeditor5-react#233]
Linking the UI language to a react state does not function. Is there a way to dynamically change the UI language upon user request?

The attached code illustrates the situation: 
1. The uiLanguage is set in the constructor. 
2. The user can switch languages (en/fr)
3. Expected: the interface (toolbar tooltips) reflects the language chosen by the user.

It appears that the language switch has no effect. The tooltips are always in the language set in the constructor (either en or fr depending on the commented line).

Is there way to change (dynamically) the ui language?

Kind regards,

Luc.

```javascript
import React, { Component } from 'react';
import { CKEditor } from '@ckeditor/ckeditor5-react';
import Editor from 'ckeditor5-custom-build/build/ckeditor';
import 'ckeditor5-custom-build/build/translations/fr';
// the build has en language built in.

class App extends Component {
  constructor(props) 
  {
    super(props);
    this.state = {
                  description: "<b>J.S. BACH : BWV 89</b> Was zoll ich aus dir machen, Ephraim ?</p><p><b>J.S. BACH : BWV 115</b> Mache dich, mein Geist, bereit</p>",
                  uiLanguage: "fr"
//                  uiLanguage: "en"
                  };
    this.toggleLanguage = this.toggleLanguage.bind(this);
  }

  toggleLanguage(evt) {
    if (this.state.uiLanguage === "en") this.setState({uiLanguage: "fr"});
    else this.setState({uiLanguage: "en"});
  }

  render() {
    return (
    <React.Fragment>
      <div onClick={this.toggleLanguage}>Language: {this.state.uiLanguage}</div>
      <h1>Test</h1>

      <CKEditor editor={ Editor }
                id="cke1"
                data={this.state.description}
                config= {
                  {language: {ui: this.state.uiLanguage, content: "fr" },
                   toolbar: ['bold', 'italic', 'link', 'bulletedList', '|', 'undo', 'redo'],
                  }}
                onChange={ ( event, editor ) => {
                   this.setState({description: editor.getData()});
                } }
              />
     </React.Fragment>
     );
  }

}

export default App;
```

**Comment by FilipTokarski** [comment]
Hi, unfortunately currently there's no way to dynamically set the UI language. We have a [feature request for this](https://github.com/ckeditor/ckeditor5/issues/9498), so feel free to add there anything you find important and also don't forget to add 👍  to bump its popularity.

**Comment by arizakevin** [comment]
A hack is to add a `key` property to the `CKEditor` component and update it when the language is changed, you could try just setting the `key` property to be the same as the selected language (`uiLanguage` in your case). Like:

```javascript
// ...
<CKEditor editor={ Editor }
    key={uiLanguage}
    {/* Rest of your code... */}
```

That will trigger a re-render of the `CKEditor` component with the settings for the language set in your `uiLanguage` state variable.
