### ISSUE TITLE
React-Native: Render Error --> ELEMENT TYPE IS INVALID: EXPECTED A STRING (FOR BUILT-IN COMPONENTS) OR CLASS/FUNCTION (FOR COMPOSITE COMPONENTS)

### ISSUE THREAD

**Issue by 95edson** [ckeditor/ckeditor5-react#238]
const [arrayData, setArrayData] = useState([]);

useEffect(() => {
    const response = database().ref(url);

    const listener = response.on('value', snapshot => {
      const fetchedTasks = [];
        snapshot.forEach(childSnapshot => {
            const key = childSnapshot.key;
            const data = childSnapshot.val();
            fetchedTasks.push({ id: key, ...data });
        });
        **setArrayData(fetchedTasks);** //The app crash here
    });
    return () => response.off('value', listener);
  }, [database()]);
  return {arrayData};
};

**Comment by FilipTokarski** [comment]
Hi, currently there is no official CKEditor integration for React Native, so unfortunately we cannot guarantee it will work properly in such environment. We have an open [feature request](https://github.com/ckeditor/ckeditor5-react/issues/35) for this, so please feel free to add there anything you find important and also add 👍  to increase its popularity.
For the time being, I'll close this ticket as a duplicate.
