### ISSUE TITLE
Cannot find module error in Meteor 2.2

### ISSUE THREAD

**Issue by icellan** [ckeditor/ckeditor5-react#239]
Initializing CKEditor in Meteor 2.2 through npm fails with error.

![Screenshot 2021-05-10 at 20 02 00](https://user-images.githubusercontent.com/4411176/117703992-9b2f2380-b1ca-11eb-8ebf-caaba54e7384.png)

Code used.

```javascript
import React from 'react';
import { CKEditor } from '@ckeditor/ckeditor5-react';
import InlineEditor from '@ckeditor/ckeditor5-editor-inline/src/inlineeditor';
import Essentials from '@ckeditor/ckeditor5-essentials/src/essentials';
import Bold from '@ckeditor/ckeditor5-basic-styles/src/bold';
import Italic from '@ckeditor/ckeditor5-basic-styles/src/italic';
import Paragraph from '@ckeditor/ckeditor5-paragraph/src/paragraph';

export default function ({ text }) {
  return (
      <CKEditor
        editor={ InlineEditor }
        config={ {
          plugins: [ Bold, Italic, Essentials, Paragraph ],
          toolbar: [ 'bold', 'italic', '|' , 'link' ]
        } }
        placeholder="Write your text here"
        data={text || ''}
      />
  )
}
```

Package.json

```json
  "dependencies": {
    "@babel/runtime": "^7.11.2",
    "@ckeditor/ckeditor5-basic-styles": "^27.1.0",
    "@ckeditor/ckeditor5-core": "^27.1.0",
    "@ckeditor/ckeditor5-editor-inline": "^27.1.0",
    "@ckeditor/ckeditor5-essentials": "^27.1.0",
    "@ckeditor/ckeditor5-paragraph": "^27.1.0",
    "@ckeditor/ckeditor5-react": "^3.0.2",
    "....|
 }
```

I cannot find anyone with a similar problem, so raising here.

**Comment by FilipTokarski** [comment]
Hi, please make sure, that you follow the [docs on React integration](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#integrating-ckeditor-5-built-from-source), especially the part with Webpack config. I remember some cases when regexp path in Webpack config was too strict and it didn't load all necessary svg files.
  
As it comes to Meteor itself, please keep in mind that there still might be some problems, as we do not have 100% integration with all JS frameworks. So, although you are using it with React here, it still might cause some issues that are new to us too.
