### ISSUE TITLE
insert html video tag

### ISSUE THREAD

**Issue by mrzslr** [ckeditor/ckeditor5-react#250]
Hey there, I'd like to know how it is possible to insert a video tag, btw I can add the image tag but for video, it's not inserted in editor data.

**Comment by pushpendra2312** [comment]
can you tell me how you added image tag in editor

**Comment by mrzslr** [comment]
**Solved**
My Solution:
I used [CKEditor5 Decoupled Editor](https://ckeditor.com/docs/ckeditor5/latest/api/editor-decoupled.html) with a custom build that I made with [Online Builder](https://ckeditor.com/ckeditor-5/online-builder/). The two plugins which are important for media embedding are `mediaEmbed` and `htmlEmbed`. you may ask why I using `htmlEmbed`, It was because I needed to insert a custom video tag inside my document. It will be rejected by the CKEditor content policies and reasons. you can read further in [General Html Support](https://ckeditor.com/docs/ckeditor5/latest/features/general-html-support.html#enabling-all-html-features) and `allowedContent` configuration, but be aware of policies and editor restrictions.

for the last part you can use and read also about:
```js 
const videoString =`<video>...</video>`
editor.execute("insertHtmlEmbed");
editor.execute("updateHtmlEmbed", videoString);
```

**Comment by pushpendra2312** [comment]
Thanks
