### ISSUE TITLE
Image resize and image toolbar not working

### ISSUE THREAD

**Issue by E-PressSend** [ckeditor/ckeditor5-react#252]
Hi there, 

I'm using a custom build of CKEditor5, generated using https://ckeditor.com/ckeditor-5/online-builder/, where I included the following plugins:

```
Editor.builtinPlugins = [
	Alignment,
	Autoformat,
	Base64UploadAdapter,
	BlockQuote,
	Bold,
	CloudServices,
	Essentials,
	Heading,
	Image,
	ImageCaption,
	ImageResize,
	ImageStyle,
	ImageToolbar,
	ImageUpload,
	Indent,
	Italic,
	Link,
	LinkImage,
	List,
	MediaEmbed,
	Paragraph,
	PasteFromOffice,
	Table,
	TableToolbar,
	TextTransformation
];
```

and this is the code to render the CKEditor component in react:
```
import { CKEditor } from '@ckeditor/ckeditor5-react';
import Editor from 'ckeditor5-custom-build/build/ckeditor';
...
...
<CKEditor
		editor={Editor}
		data={fieldProps.field.value}
		config={editorConfiguration}
		onChange={(event, editor) => {
			const data = editor.getData();
			fieldProps.form.setFieldValue('content', data);
		}}
	/>
)}
```

This is CKEditor config object:

```
const editorConfiguration = {
	toolbar: [
		'heading',
		'|',
		'bold',
		'italic',
		'link',
		'bulletedList',
		'numberedList',
		'alignment',
		'|',
		'outdent',
		'indent',
		'|',
		'imageUpload',
		'blockQuote',
		'insertTable',
		'mediaEmbed',
		'undo',
		'redo'
	],
	image: {
		resizeOptions: [
			{
				name: 'resizeImage:original',
				value: null,
				label: 'Original'
			},
			{
				name: 'resizeImage:40',
				value: '40',
				label: '40%'
			},
			{
				name: 'resizeImage:60',
				value: '60',
				label: '60%'
			}
		],
		toolbar: [
			'resizeImage'
		]
	},
	table: {
		contentToolbar: [
			'tableColumn',
			'tableRow',
			'mergeTableCells'
		]
	},
};
```

Everything seems to be working fine exept for the two features mentioned above: Image Toolbar and Image Resize.

The Image Toolbar is not appearing when the image is selected and the I'm not able to resize the image using the handlers (dragging the corners)

In the browser console I don't see any error or warning.

At the same time the **sample** in the custom build seems to be working fine, so it must be something with my react code.

Any idea where the issue can be?

Thanks

**Comment by FilipTokarski** [comment]
Hi, I used your image configuration in a React app and it worked for me, so it doesn't seem to be the problem in the editor. I'm afraid in this case I can only advise to double check if there are any other components or styles that could interfere with the image feature.

**Comment by E-PressSend** [comment]
thanks @FilipTokarski 
any suggestion on which style could be the problem or how I could debug it?

**Comment by E-PressSend** [comment]
all sorted, I put the React component on a simple page and it works.

It seems that FluentUI Panels and CKEditor don't like each other.

Cheers
