### ISSUE TITLE
how can i use ckeditor5 with typescript in react?

### ISSUE THREAD

**Issue by abhig02** [ckeditor/ckeditor5-react#253]
🆕 Feature request

## 💻 Version of CKEditor
CKEditor5

**Comment by ujjwalchadha8** [comment]
Hello @ma2ciek! I am looking for the types too and in my case for the balloon editor. This is blocking our further development with CKEditor. I see that this issue was recently reopened and triaged. When can we expect the types to be released?

**Comment by roydukkey** [comment]
@arasrezaei Do you know if `@ckeditor/ckeditor5-react` supports ref?

**Comment by arasrezaei** [comment]
> @arasrezaei Do you know if `@ckeditor/ckeditor5-react` supports ref?
<CKEditor onReady={editor=> CKRef.current = editor}  />

**Comment by ptmkenny** [comment]
@nyatalieee As noted in the linked thread above, CKEditor5 is being migrated to TypeScript: https://github.com/ckeditor/ckeditor5/issues/11704

**Comment by andrelcb** [comment]
> Olá.
> 
> ```
> declare module '@ckeditor/ckeditor5-react' {
>     import ClassicEditor from '@ckeditor/ckeditor5-build-classic';
>     import Event from '@ckeditor/ckeditor5-utils/src/eventinfo'
>     import { EditorConfig } from '@ckeditor/ckeditor5-core/src/editor/editorconfig'
>     import * as React from 'react';
>     const CKEditor: React.FunctionComponent<{
>         disabled?: boolean;
>         editor: typeof ClassicEditor;
>         data?: string;
>         id?: string;
>         config?: EditorConfig;
>         onReady?: (editor: ClassicEditor) => void;
>         onChange?: (event: Event, editor: ClassicEditor) => void;
>         onBlur?: (event: Event, editor: ClassicEditor) => void;
>         onFocus?: (event: Event, editor: ClassicEditor) => void;
>         onError?: (event: Event, editor: ClassicEditor) => void;
>     }>
>     export { CKEditor };
> }
> ```
> 
> certifique-se de instalar os tipos básicos de ckeditor.

JSX element type 'CKEditor' has no construction or call signatures.


i get this error

**Comment by pomek** [comment]
Starting from version 6.0.0 (https://github.com/ckeditor/ckeditor5-react/releases/tag/v6.0.0), the CKEditor React component is migrated to TypeScript. The component publishes its declarations, so a TS compiler should not complain anymore.

**Comment by frimmy** [comment]
was still getting this error after upgrading to v6 -- can this issue be re-opened?

**Comment by Witoso** [comment]
@frimmy could you be a little bit more specific about which error you have in mind?

**Comment by frimmy** [comment]
> > Olá.
> > ```
> > declare module '@ckeditor/ckeditor5-react' {
> >     import ClassicEditor from '@ckeditor/ckeditor5-build-classic';
> >     import Event from '@ckeditor/ckeditor5-utils/src/eventinfo'
> >     import { EditorConfig } from '@ckeditor/ckeditor5-core/src/editor/editorconfig'
> >     import * as React from 'react';
> >     const CKEditor: React.FunctionComponent<{
> >         disabled?: boolean;
> >         editor: typeof ClassicEditor;
> >         data?: string;
> >         id?: string;
> >         config?: EditorConfig;
> >         onReady?: (editor: ClassicEditor) => void;
> >         onChange?: (event: Event, editor: ClassicEditor) => void;
> >         onBlur?: (event: Event, editor: ClassicEditor) => void;
> >         onFocus?: (event: Event, editor: ClassicEditor) => void;
> >         onError?: (event: Event, editor: ClassicEditor) => void;
> >     }>
> >     export { CKEditor };
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > certifique-se de instalar os tipos básicos de ckeditor.
> 
> JSX element type 'CKEditor' has no construction or call signatures.
> 
> i get this error

the same error reported by @andrelcb - `JSX element type 'CKEditor' has no construction or call signatures`

**Comment by Witoso** [comment]
As CKEditor ships the typings you shouldn't do: `declare module '@ckeditor/ckeditor5-react'` if you use it with TypeScript. Those module augmentations are no longer needed. Check our [demo](https://github.com/ckeditor/ckeditor5-react/tree/master/demo-react-18/src).
