### ISSUE TITLE
External stylesheet is not getting load in CKEditor

### ISSUE THREAD

**Issue by ravisoftnweb** [ckeditor/ckeditor5-react#254]
I am trying to add html which contains <link> for CSS reference something like this, 
<link href="https://s3.ap-south-1.amazonaws.com/thalamus.media/waiting-room-slide-preset-assets/css/happy-birthday.css" rel="stylesheet" />

But it is not getting load i am getting png files from amazon s3 I can show you the whole code of react in codepen example of Javascript is loading the same. 

Kindly have a look into it.

```
<CKEditor
 
 config={ {
 plugins: [ Paragraph, Bold, Italic, Essentials ],
 toolbar: [ 'bold', 'italic' ]
 } }
 editor={InlineEditor}
 data={`<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><link href="https://s3.ap-south-1.amazonaws.com/thalamus.media/waiting-room-slide-preset-assets/fonts/stylesheet.css" rel="stylesheet" /><link href="https://s3.ap-south-1.amazonaws.com/thalamus.media/waiting-room-slide-preset-assets/css/happy-birthday.css" rel="stylesheet" /><title>Happy Birthday</title></head><body><div class="main"><div class="happy-birthday-page"><div class="happy-birthday-card"><div class="birthday-person"> <img src="https://s3.ap-south-1.amazonaws.com/thalamus.media/waiting-room-slide-preset-assets/images/48629069-portrait-of-happy-doctor.png" alt="medical-team-persion"></div><div class="birthday-wish"><h1 class="title"> Happy Birthday, <span>Dr. Harper!</span></h1><p>May you enjoy the finest things in life. Cheers to another year!</p></div></div><div class="birthday-bg"> <img src="https://s3.ap-south-1.amazonaws.com/thalamus.media/waiting-room-slide-preset-assets/images/51325570-chocolate-cupcake-with-a-sparkler.png" alt="birthday-bg"></div></div></div></body></html>`}
 onReady={ editor => {
 // You can store the "editor" and use when it is needed.
 console.log( 'Editor is ready to use!', editor );
  } }
 onChange={ ( event, editor ) => {
 const data = editor.getData();
 console.log( { event, editor, data } );
 } }
 onBlur={ ( event, editor ) => {
 console.log( 'Blur.', editor );
 } }
 onFocus={ ( event, editor ) => {
 console.log( 'Focus.', editor );
 } }
 onError={( error, d ) => { console.log("errror===>", error, d)} }
 />
  
```

**Comment by FilipTokarski** [comment]
The `data` property is only for the content that goes _inside_ the editor (the editable element), so it's not gonna work this way. You would probably need to [load the styles as external](https://stackoverflow.com/questions/51060111/how-to-import-a-stylesheet-from-external-source-in-react).
  
Also, please keep in mind that by default the editor will strip any custom css classes from the content/images. You can read more about it in [FAQ section](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/faq.html#why-does-the-editor-filter-out-my-content-styles-classes-elements-where-is-configallowedcontent-true) and [docs on adding class to block elements](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/conversion/conversion-extending-output.html#adding-a-css-class-to-block-elements). You might also be interested in enabling [attributes with general HTML support feature](https://ckeditor.com/docs/ckeditor5/latest/features/general-html-support.html).

**Comment by ravisoftnweb** [comment]
Ok Thanks for your quick response @FilipTokarski .
