### ISSUE TITLE
Online Builder build is failing since v28.0.0

### ISSUE THREAD

**Issue by thorstenKoch** [ckeditor/ckeditor5-react#255]
I use the output of your online builder to make a custom build for our application (in a separate project).
This worked fine with version 27.1.0 of CKEditor

Now i have updated to 28.0.0 (and 29.0.0) and the build fails with:

> webpack_1         | 
> webpack_1         | <--- Last few GCs --->
> webpack_1         | 
> webpack_1         | [8:0x52002f0]    81552 ms: Scavenge 971.3 (1002.0) -> 970.9 (1007.5) MB, 5.2 / 0.0 ms  (average mu = 0.350, current mu = 0.175) allocation failure 
> webpack_1         | [8:0x52002f0]    81589 ms: Scavenge 974.1 (1007.5) -> 973.2 (1007.5) MB, 6.9 / 0.0 ms  (average mu = 0.350, current mu = 0.175) allocation failure 
> webpack_1         | [8:0x52002f0]    81663 ms: Scavenge 975.0 (1007.5) -> 974.3 (1017.8) MB, 63.6 / 0.0 ms  (average mu = 0.350, current mu = 0.175) allocation failure 
> webpack_1         | 
> webpack_1         | 
> webpack_1         | <--- JS stacktrace --->
> webpack_1         | 
> webpack_1         | FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
> webpack_1         |  1: 0xb200e0 node::Abort() [webpack]
> webpack_1         |  2: 0xa3c157 node::FatalError(char const*, char const*) [webpack]
> webpack_1         |  3: 0xd083ae v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [webpack]
> webpack_1         |  4: 0xd08727 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [webpack]
> webpack_1         |  5: 0xee9785  [webpack]
> webpack_1         |  6: 0xef84b5 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [webpack]
> webpack_1         |  7: 0xefb5ac v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [webpack]
> webpack_1         |  8: 0xec000c v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [webpack]
> webpack_1         |  9: 0x123695b v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [webpack]
> webpack_1         | 10: 0x1640839  [webpack]
> webpack_1         | Aborted
> ckeditor_webpack_1 exited with code 134
> 

### Environment

**./.docker/webpack/Dockerfile**

```
FROM node:16.3.0

RUN apt-get update && \
    apt-get upgrade -y && \
	apt-get install -y git

RUN npm install
RUN npm install -g webpack webpack-cli @angular/cli
```

**./docker-compose.yaml**

```
version: '3.5'

services:
  webpack:
    build:
      context: .
      dockerfile: ./.docker/webpack/Dockerfile
    volumes:
      - ./:/ckeditor:cached
    command:
      - /bin/sh
      - -c
      - |
        cd /ckeditor/packages/ckeditor5-build
        webpack --watch --mode production

```

Node: 16.3.0
NPM: 7.15.1

I use those Plugins:
```

import ClassicEditor from '@ckeditor/ckeditor5-editor-classic/src/classiceditor.js';
import Alignment from '@ckeditor/ckeditor5-alignment/src/alignment.js';
import Autoformat from '@ckeditor/ckeditor5-autoformat/src/autoformat.js';
import Base64UploadAdapter from '@ckeditor/ckeditor5-upload/src/adapters/base64uploadadapter.js';
import BlockQuote from '@ckeditor/ckeditor5-block-quote/src/blockquote.js';
import Bold from '@ckeditor/ckeditor5-basic-styles/src/bold.js';
import CloudServices from '@ckeditor/ckeditor5-cloud-services/src/cloudservices.js';
import Essentials from '@ckeditor/ckeditor5-essentials/src/essentials.js';
import Heading from '@ckeditor/ckeditor5-heading/src/heading.js';
import Image from '@ckeditor/ckeditor5-image/src/image.js';
import ImageCaption from '@ckeditor/ckeditor5-image/src/imagecaption.js';
import ImageResize from '@ckeditor/ckeditor5-image/src/imageresize.js';
import ImageStyle from '@ckeditor/ckeditor5-image/src/imagestyle.js';
import ImageToolbar from '@ckeditor/ckeditor5-image/src/imagetoolbar.js';
import ImageUpload from '@ckeditor/ckeditor5-image/src/imageupload.js';
import Indent from '@ckeditor/ckeditor5-indent/src/indent.js';
import IndentBlock from '@ckeditor/ckeditor5-indent/src/indentblock.js';
import Italic from '@ckeditor/ckeditor5-basic-styles/src/italic.js';
import Link from '@ckeditor/ckeditor5-link/src/link.js';
import List from '@ckeditor/ckeditor5-list/src/list.js';
import ListStyle from '@ckeditor/ckeditor5-list/src/liststyle.js';
import MediaEmbed from '@ckeditor/ckeditor5-media-embed/src/mediaembed.js';
import MediaEmbedToolbar from '@ckeditor/ckeditor5-media-embed/src/mediaembedtoolbar.js';
import Mention from '@ckeditor/ckeditor5-mention/src/mention.js';
import Paragraph from '@ckeditor/ckeditor5-paragraph/src/paragraph.js';
import PresenceList from '@ckeditor/ckeditor5-real-time-collaboration/src/presencelist.js';
import RealTimeCollaborativeComments from '@ckeditor/ckeditor5-real-time-collaboration/src/realtimecollaborativecomments.js';
import RealTimeCollaborativeEditing from '@ckeditor/ckeditor5-real-time-collaboration/src/realtimecollaborativeediting.js';
import RealTimeCollaborativeTrackChanges from '@ckeditor/ckeditor5-real-time-collaboration/src/realtimecollaborativetrackchanges.js';
import RemoveFormat from '@ckeditor/ckeditor5-remove-format/src/removeformat.js';
import Table from '@ckeditor/ckeditor5-table/src/table.js';
import TableCellProperties from '@ckeditor/ckeditor5-table/src/tablecellproperties';
import TableProperties from '@ckeditor/ckeditor5-table/src/tableproperties';
import TableToolbar from '@ckeditor/ckeditor5-table/src/tabletoolbar.js';
import TextTransformation from '@ckeditor/ckeditor5-typing/src/texttransformation.js';
import Title from '@ckeditor/ckeditor5-heading/src/title.js';
import Underline from '@ckeditor/ckeditor5-basic-styles/src/underline.js';
import WordCount from '@ckeditor/ckeditor5-word-count/src/wordcount.js';

```

All those plugins will result in error above. If i only have some of them activated, the build is working.
I change the deactivated plugins, seems that the error does not be dedicated to a special plugin, more to the amount of plugins loaded.

Another hint:

If i use my native shell (macOS BigSur 11.3.1) with the same node and npm versions, the build works.

Any clue on my docker setup? Can i somehow enlarge that  heap limit for my `webpack --watch --build` command

Another thing: When i build that in my local environment and use the build in an index.html, then i will get this javascript error (even without any plugin imported):

> ckeditorerror.js:64 Uncaught CKEditorError: ckeditor-duplicated-modules
> Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-duplicated-modules

**Comment by pomek** [comment]
> Any clue on my docker setup? Can i somehow enlarge that heap limit for my webpack --watch --build command

Try to use `NODE_OPTIONS="--max-old-space-size=4096" webpack --watch --mode production`. But make sure that your docker instance has available at least 4 GB of RAM.

**Comment by thorstenKoch** [comment]
> > Any clue on my docker setup? Can i somehow enlarge that heap limit for my webpack --watch --build command
> 
> Try to use `NODE_OPTIONS="--max-old-space-size=4096" webpack --watch --mode production`. But make sure that your docker instance has available at least 4 GB of RAM.

Thank you @pomek for your fast reply. That was the first step of resolving my issue. Once i did that, the docker container just exited with

> webpack_1         | Killed
> ckeditor_webpack_1 exited with code 137

Resarching for exit code 137 brought me to that [page](https://betterprogramming.pub/understanding-docker-container-exit-codes-5ee79a1d58f6), where it stated that 

> docker kill can be initiated manually by the user or by the host machine. If initiated by host machine, then it is generally due to being out of memory.

Somewhere else it stated, that docker host will just kill the process, if it consumes too much memory. I went to the docker preferences of my host and in the resources tab the memory limit was limited to 2G. I changed it to 4G and the build did not fail.

So if you encounter a JavaScript heap out of memory you have to do two things:

1. Allow docker containers to consume more RAM in your docker host's preferences.
2. Change your scripts in packages.json to 

```
  "scripts": {
    "build": "NODE_OPTIONS=\"--max-old-space-size=4096\" webpack --mode production",
    "watch": "NODE_OPTIONS=\"--max-old-space-size=4096\" webpack --watch --mode production"
  }

```

SOLVED, thank you!!!

And by the way: SORRY, that problem was not related to the ckeditor5-react package, it was related to the classic editor :-)
