### ISSUE TITLE
"widget toolbar no items" {toolbarId: 'mediaEmbed'}

### ISSUE THREAD

**Issue by albertovalerio** [ckeditor/ckeditor5-react#267]
I got this warning in console when component is rendered

<img width="1671" alt="Screenshot 2021-10-25 at 19 00 13" src="https://user-images.githubusercontent.com/48770314/138850753-f3bdb0f4-4e89-48b9-92ce-3078cd926056.png">

This is the error reference on official doc

[https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-widget-toolbar-no-items](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-widget-toolbar-no-items)

And this is my component

```
export const EditorField = (props) => {

    const {name,method,placeholder,isSimplified} = props

    const link = {
        decorators: {
            toggleDownloadable: {
                mode: 'manual',
                label: 'Downloadable',
                attributes: {
                    download: 'file'
                }
            },
            openInNewTab: {
                mode: 'manual',
                label: 'Open in a new tab',
                defaultValue: true,
                attributes: {
                    target: '_blank',
                    rel: 'noopener noreferrer'
                }
            }
        }
    }
    const image = {
        toolbar: [
            'imageTextAlternative',
            'imageStyle:inline',
            'imageStyle:block',
            'imageStyle:side',
            'linkImage'
        ]
    }
    const table = {
        contentToolbar: [
            'tableColumn',
            'tableRow',
            'mergeTableCells',
            'tableCellProperties',
            'tableProperties'
        ]
    }
    const toolbar = isSimplified ? {
        items: [
            'bold','italic','underline','strikethrough','|',
            'link','|',
            'specialCharacters','|',
            'undo','redo'
        ], shouldNotGroupWhenFull: true
    } : {
        items: [
            'heading','|',
            'bold','italic','underline','strikethrough','|',
            'fontColor','fontBackgroundColor','|',
            'bulletedList','numberedList','|',
            'link','imageUpload','insertTable','mediaEmbed','|',
            'specialCharacters','blockQuote','horizontalLine','|',
            'undo','redo'
        ], shouldNotGroupWhenFull: true
    }

    return (
        <CKEditor
            config={ {
                toolbar,
                language: 'it',
                placeholder,
                link,
                image,
                table,
            } }
            editor={ Editor }
            data={request[name] || ''}
            onChange={ (event, editor) => {
                const data = editor.getData()
                dispatch(setValue({method,name,value:data}))
            } }
        />
    )
}
```

**Comment by albertovalerio** [comment]
It was suggested to me this solution on Stackoverflow, it works and does not affect the editor's functionalities.

> Add this to your config:
> `removePlugins: ["MediaEmbedToolbar"],`
> At the moment, this plugin doesn't do anything:
> [https://github.com/ckeditor/ckeditor5/issues/9824](https://github.com/ckeditor/ckeditor5/issues/9824)

**Comment by TukuToi** [comment]
This is weid.
That thing is included by _default_ in the creditor builds.

This shouldn't be closed, I think, since it still happens.
Also the DOC link they provide in the debug note points to https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-widget-toolbar-no-items
This doc says, that the error refers to whatever tool with ID as in `toolbarId : String`
The ID there is `mediaEmbed`
And that is not a "does nothing" tool, it is well documented here actually https://ckeditor.com/docs/ckeditor5/latest/features/media-embed.html

And that is used to embed videos.
Nonetheless if we remove `MediaEmbedToolbar` plugin the error disappears, _and the embed tool still works_

Being this the default behaviour, I would expect it to be fixed. Here it was stated that "it does nothing", but that does not seem true to me:
https://github.com/ckeditor/ckeditor5/issues/9824

**Comment by benzon** [comment]
dos not look like it will be fixed, it's what more then half a year since you reopened it, and more then a year ago the bug was reported.

Facing the same issue currently so something is wrong i guess.

**Comment by Mohsen-graphyy** [comment]
Hi, I fixed this problem by adding this config :
`{  removePlugins: ['MediaEmbedToolbar']  }`
It works for me and I no longer get this warning.
