### ISSUE TITLE
TypeError: this.props.editor.create is not a function

### ISSUE THREAD

**Issue by bambier** [ckeditor/ckeditor5-react#280]
## 📝 Provide detailed reproduction steps (if any)
 Im Using react app after I download my custom  build from [CKEditor 5 online builder](https://ckeditor.com/ckeditor-5/online-builder/) then I follow [these](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#integrating-a-build-from-the-online-builder) steps, I got this err on console 

```
TypeError: this.props.editor.create is not a function
    at Rr._createEditor (bundle.js:5640:34)
    at Pr._creator (bundle.js:5624:176)
    at bundle.js:5363:187 {phase: 'initialization', willEditorRestart: false}
```

### ✔️ Expected result

render editor

### ❌ Actual result

render null or not thing

### ❓ Possible solution

I think it cant extends custom class in to base class...

## 📃 Other details

* Browser: chrome
* OS: ubuntu
* First affected CKEditor version: lastest
* Installed CKEditor plugins: custom build

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by kolserdav** [comment]
+1

**Comment by kolserdav** [comment]
I imported 1 dynamically and had the same problem:
```typescript
import('../../dynamic/ClassicEditor').then((d) => {
  ClassicEditor = d;
});
```
The problem was that when importing, I used a non-default value:
```typescript
import('../../dynamic/ClassicEditor').then((d) => {
  ClassicEditor = d.default; // Adding a default solved the problem
});
```

**Comment by jechazelle** [comment]
@nimaes80 @kolserdav did you find a solution ?

**Comment by kolserdav** [comment]
> @nimaes80 @kolserdav did you find a solution ?

Yes

>The problem was that when importing, I used a non-default value:...

**Comment by winniexueyao** [comment]
@kolserdav could you share your solution? I have the same problem

**Comment by kolserdav** [comment]
@winniexueyao  it was over here https://github.com/ckeditor/ckeditor5-react/issues/280#issuecomment-1280128790
