### ISSUE TITLE
[Feature Request] Add support for React 18

### ISSUE THREAD

**Issue by ptmkenny** [ckeditor/ckeditor5-react#297]
As of yesterday, [React 18 was officially released](https://reactjs.org/blog/2022/03/29/react-v18.html).  This release includes major changes to the way concurrency is handled.

Over the long term, it would be great for CKEditor to support these new features related to concurrency.

In the short term, it would be great to have a CKEditor editor release that allows installation alongside React 18.

**Comment by pomek** [comment]
Hi, @ptmkenny. Thanks for reporting the issue. We're aware of the release of React 18, and we would like to adjust the `<CKEditor>` component to be compatible with the latest React too. However, I can't promise any ETA for it as we're closing the current iteration and preparing for the release. We will focus on it in the future iteration. I hope it isn't a big problem for you now.

You can find more details about the upcoming release in our iteration roadmap posts - https://github.com/ckeditor/ckeditor5/issues/11387.

**Comment by michalstrzelecki** [comment]
I simply can not upgrade entire app to react 18 because of this package.
```bash npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.13.1 || ^17.0.0" from @ckeditor/ckeditor5-react@4.0.0
npm ERR! node_modules/@ckeditor/ckeditor5-react
npm ERR!   @ckeditor/ckeditor5-react@"^4.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.```

**Comment by ptmkenny** [comment]
@pomek Thanks for the prompt response.  It's great you have a published roadmap-- I wish every project had one.

**Comment by pomek** [comment]
PR with "support" for React 18 is on review - https://github.com/ckeditor/ckeditor5-react/pull/299.

**Comment by pomek** [comment]
And, the new version of the `<CKEditor>` component is live too - https://github.com/ckeditor/ckeditor5-react/releases/tag/v4.0.1. It supports React 18.
