### ISSUE TITLE
React 17 will remove `componentWillReceiveProps()` function that is used in component

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5-react#3]
As in title, the following method won't work with the future version:

https://github.com/ckeditor/ckeditor5-react/blob/346a586fbee5b33a5251506e755474a93f8dcc3d/src/ckeditor.js#L17-L22

https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html

**Comment by ma2ciek** [comment]
Yeah. `componentDidUpdate` should be used instead.

**Comment by johnunclesam** [comment]
If I remove this in code it works very good in my app.

We still need it (https://github.com/ckeditor/ckeditor5-react/issues/12)?

**Comment by pomek** [comment]
As @ghost mentioned, removing this method does not impact on the component or editor.

**Comment by ma2ciek** [comment]
So what happens when your component is gets new props?
