### ISSUE TITLE
how can I add custom baseurl for image in ckeditor data

### ISSUE THREAD

**Issue by topskishan** [ckeditor/ckeditor5-react#305]
![Screenshot from 2022-05-04 11-17-55](https://user-images.githubusercontent.com/101639816/166628774-abcb908b-5472-4591-b6b8-68d88f814079.png)

i want to add custom origin url before the image path in img src , shown in inspect element.
![Screenshot from 2022-05-05 14-59-37](https://user-images.githubusercontent.com/101639816/166896965-63102b83-896f-4352-930b-c7977ac9779c.png)

i want to change this baseURI value from this http://tops.plm.com:8015/react-app/  to
 http://tops.plm.com:8015/

**Comment by pomek** [comment]
Hi, @topskishan,

It seems that you can resolve your issue by creating an alias for an HTTP server. On the back-end side, you could create a redirect for JPG files to search for them in a proper directory.

However, if it does not fit, you can always create a [post-fixer](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_document-Document.html#function-registerPostFixer) function where you can iterate over all images in the editor and align the `[src]` attribute.

PS: Perhaps the [`<base>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base) element could help too.

**Comment by topskishan** [comment]
hii @pomek , thanx for your reply
          i am not using image upload feature of ckeditor5 . i just have my old database data which having the image src in it. so i just not to change manually baseurl for image element
          as you have suggested [post-fixer ] , but i am not  much clear about that function to implement .
          can you help me out for that post-fixer by suggesting example or any implemented url or by manually chane setup baseurl for image tag

**Comment by pomek** [comment]
@topskishan, please, take a look at the code snippet below:

```js
function FixImageSource( editor ) {
	this.init = function () {
		editor.model.document.registerPostFixer( writer => {
				let changed = false;

				for ( const entry of editor.model.document.differ.getChanges() ) {
					if ( entry.type !== 'insert' && entry.type !== 'attribute' ) {
						continue;
					}

					const range = entry.type === 'insert' ?
						writer.createRange( entry.position, entry.position.getShiftedBy( entry.length ) ) :
						entry.range;

					// Filter out all nodes that do not represent an image.
					const items = [ ...range.getItems() ].filter( item => {
						return item.is( 'element', 'imageBlock' ) || item.is( 'element', 'imageInline' );
					} );

					// Then, for each image, replace its source.
					for ( const image of items ) {
						// Make sure to add "an exit condition". Otherwise, you will finish with end-less loop.
						if ( image.getAttribute( 'src' ) !== 'https://via.placeholder.com/640x360.png' ) {
							// Make sure to update the `srcset` attribute if you use responsive images.
							writer.setAttribute( 'src', 'https://via.placeholder.com/640x360.png', image );

							// Make sure to return `true` if this post-fixer updated any element.
							changed = true;
						}
					}
				}

				return changed;
			}
		)
		;
	};
}
```

It is an example plugin that registers a post fixer that updates all images in the editor. I believe it should help you achieve your goals.

**Comment by topskishan** [comment]
> @topskishan, please, take a look at the code snippet below:
> 
> ```js
> function FixImageSource( editor ) {
> 	this.init = function () {
> 		editor.model.document.registerPostFixer( writer => {
> 				let changed = false;
> 
> 				for ( const entry of editor.model.document.differ.getChanges() ) {
> 					if ( entry.type !== 'insert' && entry.type !== 'attribute' ) {
> 						continue;
> 					}
> 
> 					const range = entry.type === 'insert' ?
> 						writer.createRange( entry.position, entry.position.getShiftedBy( entry.length ) ) :
> 						entry.range;
> 
> 					// Filter out all nodes that do not represent an image.
> 					const items = [ ...range.getItems() ].filter( item => {
> 						return item.is( 'element', 'imageBlock' ) || item.is( 'element', 'imageInline' );
> 					} );
> 
> 					// Then, for each image, replace its source.
> 					for ( const image of items ) {
> 						// Make sure to add "an exit condition". Otherwise, you will finish with end-less loop.
> 						if ( image.getAttribute( 'src' ) !== 'https://via.placeholder.com/640x360.png' ) {
> 							// Make sure to update the `srcset` attribute if you use responsive images.
> 							writer.setAttribute( 'src', 'https://via.placeholder.com/640x360.png', image );
> 
> 							// Make sure to return `true` if this post-fixer updated any element.
> 							changed = true;
> 						}
> 					}
> 				}
> 
> 				return changed;
> 			}
> 		)
> 		;
> 	};
> }
> ```
> 
> It is an example plugin that registers a post fixer that updates all images in the editor. I believe it should help you achieve your goals.

**Comment by topskishan** [comment]
thanx @pomek its worked while rendering of image but when i add the data to database , the baseurl is getting added as many times i add ckeditor data with the image src. the below link was the ckediotr src from database
 [](**http://tops.plm.com:8015/http://tops.plm.com:8015/**development-order/tops/order-61cab22926954413d37d4746/images/dev-order_1647940414902.png)
i just wanted the add baseurl while rendering of data, not at the time of saving data .
is there any possible way for that?

**Comment by topskishan** [comment]
thanx @pomek , your answer helped me solving my  issue.

**Comment by chungdicai** [comment]
It's useful thanks for solving my issue too
