### ISSUE TITLE
Duplicated editor after show and hide the component using react 18

### ISSUE THREAD

**Issue by michalstrzelecki** [ckeditor/ckeditor5-react#306]
![obraz](https://user-images.githubusercontent.com/3853055/166743101-142f0b7f-c1d0-4a09-bdcd-cbe64b066450.png)
If component is hidden (not in the dom, not rendered) and shown again then it will render twice.

**Comment by zengdukan** [comment]
I have the same issue, also with react 18.

**Comment by zengdukan** [comment]
I find with react and react-dom 16.13.1, it is ok.

**Comment by pomek** [comment]
Hey guys,

Thanks for reporting the issue. We're currently focused on other topics. Hence it's hard to say when we will fix the problem. I don't want to promise anything, but we will try to take a look at that in the next week.

However, we will appreciate if you could share steps that allow reproducing the problem,

**Comment by FilipTokarski** [comment]
I can confirm this, the steps I followed:
- create new app with `npx create-react-app`
- install ckeditor component `npm install --save @ckeditor/ckeditor5-react`
- create editor build in online builder, unzip and move to the project folder
- add ckeditor as a dependency with `yarn add file:./ckeditor5`
- update component's code [like in the docs](https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/frameworks/react.html#integrating-a-build-from-the-online-builder)
- run `npm run start`

Result - there are two editors on the page.

**Comment by dev-ankitkumar** [comment]
this is a react 18 bug when we use   <React.StrictMode> it render twice componenents and when we remove <React.strictMode it work fine

**Comment by michalstrzelecki** [comment]
yeak, but it should destroy the instance / unmount after component is not visible

**Comment by pomek** [comment]
I close this issue as DUP of https://github.com/ckeditor/ckeditor5-react/issues/294. We fixed the issue and it should not occur in the latest version of the `<CKEDitor>` React component => https://github.com/ckeditor/ckeditor5-react/releases/tag/v5.0.1.
