### ISSUE TITLE
React 18 > Online build > Not instantiate

### ISSUE THREAD

**Issue by michaelpeterlee** [ckeditor/ckeditor5-react#307]
BuildId: `idnha5iejjnc-9xibuqutzukq`.

PROBLEM:
CKEditor no-longer instantiates/renders after upgrading to React 18.
We have always lazy loaded both  `CKEditor` and our online build, not sure if that has any bearing.

ERROR:
```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```

**Comment by FilipTokarski** [comment]
Hi, I checked it and was able to initialize the editor from online builder + React 18 (however I stumbled upon https://github.com/ckeditor/ckeditor5-react/issues/306). Maybe your custom integration/loading has some impact on this?

**Comment by michaelpeterlee** [comment]
We downgraded to React 17 and now still suffer the issue. Will let you know the outcome once we solve.

**Comment by michaelpeterlee** [comment]
`<CKEditor />` returns a React element with `type: undefined`.

Q. Any ideas why it would do that?

**Comment by michaelpeterlee** [comment]
We referenced `CKEditor` from the parent React.Component `this` scope; `<this.CKEditor />. 

Solved by de-referencing from the component `this` scope. 

No idea why it presents as an artefact all of a sudden.
