### ISSUE TITLE
the editor unloads when using ReactStrictMode mode in Nextjs

### ISSUE THREAD

**Issue by mahdithedev** [ckeditor/ckeditor5-react#313]
hello so for the past few days I have been trying to integrate the editor with Nextjs I use the following code for initializing the component 

```js

  const editorRef = useRef()
  const [ editorLoaded, setEditorLoaded ] = useState( false )
  const { CKEditor, CustomEditor } = editorRef.current || {}

  useEffect( () => {
    editorRef.current = {
      CKEditor: require( '@ckeditor/ckeditor5-react' ).CKEditor,
      CustomEditor: require('ckeditor5-custom-build')
    }
    setEditorLoaded( true )
  }, [] )

  

  // const router = useRouter();

  // // if user is not logged in
  // if(!data) {
  //   router.push('/login');
  // }

    return (
      <div className='w-full h-full' >
      <h1>Ckeditor5 Nextjs</h1>
      {
        editorLoaded ?
        <CKEditor className="mt-3 wrap-ckeditor" editor={CustomEditor} />
        :
        "loading..."
      }
      

    </div>
    )
```
if `reactStrictMode` is set to `true` in the `next.config.js` the component loads and then unloads after a few hundred milliseconds

https://user-images.githubusercontent.com/79410826/172867940-28629ec0-8404-4952-a753-1a4500806643.mp4

**Comment by pomek** [comment]
Could you prepare a minimal setup that allows reproducing the issue?

**Comment by mahdithedev** [comment]
@pomek you can clone https://github.com/mahdithedev/ckeditor5-bug to reproduce this bug I am on Chrome 102.0.5005.63 (Official Build) (64-bit)

**Comment by pomek** [comment]
Recently, we released a new version (https://github.com/ckeditor/ckeditor5-react/releases/tag/v5.0.3) that brings a fix for the invalid rendering of the `CKEditor` component in the strict mode. Could you (@mahdithedev) check if the issue is still valid?

**Comment by mahdithedev** [comment]
I will check as soon as possible.
Any guide on how to update the Editor?

**Comment by mahdithedev** [comment]
The issue is resolved.
