### ISSUE TITLE
bullets are not appearing within editor window

### ISSUE THREAD

**Issue by tista-chatterjee** [ckeditor/ckeditor5-react#314]
![20220613_110917](https://user-images.githubusercontent.com/91665085/173336770-a9d5d77e-1f7d-4155-a2be-9f1f34dd5511.jpg)
![20220613_110936](https://user-images.githubusercontent.com/91665085/173336799-8000dbcf-9e89-4009-846c-0e56b921b90f.jpg)
![20220613_110939](https://user-images.githubusercontent.com/91665085/173336810-f1c231e2-eb5d-4f99-8709-6e8bf927ac32.jpg)

We are using ckeditor5-react in our spfx solution.we have included list and list properties plugin while building our creditor modules still we are facing this issue. once saved bullets are appearing but in the edit mode i.e within creditor bullers are outside the creditor window. Please help us with this issue.

**Comment by lslowikowska** [comment]
Hi @tista-chatterjee, thank you for submitting your report. Note that the official support channel is available at support@cksource.com. Please send your report to the mentioned email address and provide your support token number with as much information to reproduce the problem on our side as possible. Based on that, our support team will analyze your issue and will try to help you out.
