### ISSUE TITLE
custom upload adapter: how to accept heic or heif image file?

### ISSUE THREAD

**Issue by tkmin** [ckeditor/ckeditor5-react#328]
What I know is that no browser support .heic or .heif file well.
So I managed to convert heic file to supporting image file types (gif, jpeg, etc) at client side.
From that I was able to upload .heic file via input tag which accepts image/*, .heic and .heif
(<input type="file" accept="image/\*, .heic, .heif />)
but not with my custom upload adapter

what I tried was
change image upload input's accept like this code below
```
<CKEditor
     ...
    onReady={(editor: any) => {
      const fileInput = document.querySelector('.ck-file-dialog-button')?.lastChild as HTMLInputElement;
      fileInput.accept = 'image/*, .heic, .heif';
    }}
   ...
/>
```

I checked that input's accept changed,
but nothing happens when I upload .heic or .heif image file while other types of files works well.

what should I do to my upload adapter to upload .heic file?
below code is my custom upload adapter

```
function uploadAdapter(loader: any) {
    return {
      upload: () => {
        return new Promise((resolve, reject) => {
          loader.file.then((imageFile: File) => {
            const uploadUrl = `/api/v1/store/room/${roomId}/detail-image`;
            const formData = new FormData();

            compressImageFile({
              imageFile,
              maxWidth: 1500,
              quality: imageFile.size > 5000000 ? 0.5 : 0.8,
              onSuccess: compressed => {
                if (compressed.size > 5000000) {
                  oversizeAlert();
                  reject();
                } else {
                  formData.append('upload', compressed);
                  postImage(uploadUrl, formData, resolve, reject);
                }
              },
              onError: err => {
                console.log(err.message);
                reject(errMsg);
              },
            });
          });
        });
      },
    };
  }

  function uploadPlugin(editor: any) {
    editor.plugins.get('FileRepository').createUploadAdapter = (loader: any) => {
      return uploadAdapter(loader);
    };
  }

...

const editorConfig = {
    extraPlugins: [uploadPlugin],
    ...
}

...

<CKEditor
          editor={Editor}
          config={editorConfig}
....
/>
```

----

just noticed,
when uploading hei(c|f) file,
Safari browser automatically convert(?) it to jpeg format,
so described issue above is not happening on Safari browser
but it happens on Chrome browser

**Comment by pomek** [comment]
Could you try to modify the editor configuration according to https://ckeditor.com/docs/ckeditor5/latest/api/module_image_imageupload-ImageUploadConfig.html#member-types?

```jsx
<CKEditor
     ...
    config={ {
		image: {
			upload: {
				types: [ /* ... */ ]
			}
		}
	} }
   ...
/>
```

**Comment by tkmin** [comment]
> Could you try to modify the editor configuration according to https://ckeditor.com/docs/ckeditor5/latest/api/module_image_imageupload-ImageUploadConfig.html#member-types?
> 
> ```js
> <CKEditor
>      ...
>     config={ {
> 		image: {
> 			upload: {
> 				types: [ /* ... */ ]
> 			}
> 		}
> 	} }
>    ...
> />
> ```

That was exactly what I tried before I try this below
```
<CKEditor
     ...
    onReady={(editor: any) => {
      const fileInput = document.querySelector('.ck-file-dialog-button')?.lastChild as HTMLInputElement;
      fileInput.accept = 'image/*, .heic, .heif';
    }}
   ...
/>
```

because
when I input string array like ['jpeg', 'webp', 'heic'] to image.upload.types
output of input tag's accept string was like this -> 'image/jpeg, image/webp, image/heic'

To file input to accept .heic or .heif file,
input tag's accept suppose to be look like this
`accept='.heic, .heif'`

and, on PC chrome,
when uploading file via plain input tag like <input type="file" accept="image/*, .heic, .heic" />
file was able to be uploaded if I convert uploaded .heic file to other format(eg. jpeg)

but even if I manually change ckeditor's file input's accept string like that
all formats of image file could be uploaded except .heic and .heif file format

**Comment by tkmin** [comment]
nevermind that,
I decide not to accept .heic / .heif file.
since Apple made their own independent file type,
they convert heic file to jpeg automatically when uploading image via iOS safari engine based browsers
but for pc browsers and others,
Apple should take all the responsibility for their own format of file.
I hate Apple.

**Comment by pomek** [comment]
Thanks for the update.

However, I am sure you reported a valid use case, and I wouldn't close the issue as long as we don't know how to resolve the mentioned problem.

We will try to reproduce the problem and, if so, prepare a working solution. Unfortunately, I can't promise any ETA.
