### ISSUE TITLE
ckeditorerror.ts:148 widget-toolbar-no-items toolbarId:"image"

### ISSUE THREAD

**Issue by irtaza9** [ckeditor/ckeditor5-react#329]
**I'm getting this warring again and again, this warring is redirecting me to the official [error page](https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-widget-toolbar-no-items) of CKEDITOR but still I do not understand how to tackle and adjust this warring. Actually I customized the toolbar and removed the unnecessarily options from the toolbar.** 

### Code snippet

```
import { CKEditor } from "@ckeditor/ckeditor5-react";
import ClassicEditor from "@ckeditor/ckeditor5-build-classic";

ClassicEditor.defaultConfig = {
  toolbar: {
    items: [
      "heading",
      "|",
      "bold",
      "italic",
      "|",
      "bulletedList",
      "numberedList",
      "|",
      "undo",
      "redo",
    ],
  },
  language: "en",
};
```

```
<CKEditor
                  name="problemStatement"
                  editor={ClassicEditor}
                  onChange={(event, editor) => {
                    const data = editor.getData();
                    ProblemStatment = data;
                  }}
                />
```

![Screenshot 2022-10-05 163307](https://user-images.githubusercontent.com/98938307/194051226-d2bfde15-f990-410c-ae96-bf9ad46304c9.png)

**Comment by pomek** [comment]
The warning means that [`WidgetToolbarRepository`](https://ckeditor.com/docs/ckeditor5/latest/api/module_widget_widgettoolbarrepository-WidgetToolbarRepository.html) received an empty array in the configuration.

You can fix the issue by adding the configuration for the image toolbar (`image.toolbar = [ ... ]`) or [removing](https://ckeditor.com/docs/ckeditor5/latest/api/module_core_editor_editorconfig-EditorConfig.html#member-removePlugins) the [`ImageToolbar`](https://ckeditor.com/docs/ckeditor5/latest/api/module_image_imagetoolbar-ImageToolbar.html) plugin.

- **(1) Configuration**

```
ClassicEditor.defaultConfig = {
  toolbar: {
    items: [
      "heading",
      "|",
      "bold",
      "italic",
      "|",
      "bulletedList",
      "numberedList",
      "|",
      "undo",
      "redo",
    ],
  },
  image: {
    toolbar: [ /* ... */ ]
  },
  language: "en",
};
```

- **(2) Remove plugins**

```
ClassicEditor.defaultConfig = {
  toolbar: {
    items: [
      "heading",
      "|",
      "bold",
      "italic",
      "|",
      "bulletedList",
      "numberedList",
      "|",
      "undo",
      "redo",
    ],
  },
  removePlugins: [
    'ImageToolbar'
  ]
  language: "en",
};
```

**Comment by irtaza9** [comment]
Thank you @pomek for sharing the information. I'm happy to share that the warring that was showing in my console is gone as I use the **Second configuration in my file**. But the first process was not up to the mark. Again Thank you for giving the priority to this request.
