### ISSUE TITLE
Error: Item with the given id was not registered in getWatchdog()

### ISSUE THREAD

**Issue by EvaGarzonBeltran** [ckeditor/ckeditor5-react#330]
### 📝 Provide detailed reproduction steps (if any)
1. I'm trying to implement the ClassicEditor with the component for React and the Context:

```
import React from "react";
import { CKEditor, CKEditorContext } from "@ckeditor/ckeditor5-react";
import Context from "@ckeditor/ckeditor5-core/src/context";
import ClassicEditor from "@ckeditor/ckeditor5-editor-classic/src/classiceditor";
import Essentials from "@ckeditor/ckeditor5-essentials/src/essentials";
import PropTypes from 'prop-types'

const EditorTest = ({ id, data, onChange, onBlur }) => {
  return (
    <CKEditorContext context={Context}>
      <CKEditor
        id={id}
        editor={ClassicEditor}
        config={{
          plugins: [Essentials],
        }}
        data={data}
        onChange={(e, editor) => {
          const data = editor.getData();
          onChange(data);
        }}
        onBlur={() => {
          onBlur && onBlur();
        }}
      />
    </CKEditorContext>
  );
};

EditorTest.propTypes = {
  id: PropTypes.string,
  data: PropTypes.string,
  onChange: PropTypes.func.isRequired,
  onBlur: PropTypes.func,
};
export default EditorTest;
```

2. This is package.json:

```
{
    "name": "my-package",
    "version": "1.0.4",
    "description": "",
    "main": "build/index.js",
    "babel": {
      "presets": [
        "@babel/preset-react"
      ]
    },
    "peerDependencies": {
      "react": "^18.2.0"
    },
    "dependencies": {
      "@ckeditor/ckeditor5-core": "^35.2.0",
      "@ckeditor/ckeditor5-dev-utils": "^31.1.0",
      "@ckeditor/ckeditor5-dev-webpack-plugin": "^31.1.0",
      "@ckeditor/ckeditor5-editor-classic": "^35.2.0",
      "@ckeditor/ckeditor5-essentials": "^35.2.0",
      "@ckeditor/ckeditor5-react": "^5.0.2",
      "@ckeditor/ckeditor5-theme-lark": "^35.2.0",
      "@ckeditor/ckeditor5-typing": "^35.2.0",
      "@ckeditor/ckeditor5-ui": "^35.2.0",
      "@ckeditor/ckeditor5-utils": "^35.2.0",
      "css-loader": "^6.7.1",
      "postcss-loader": "^7.0.1",
      "raw-loader": "^4.0.2",
      "react": "^18.2.0",
      "style-loader": "^3.3.1"
    },
    "scripts": {
      "start": "webpack --mode development --watch",
      "prepublish": "webpack --mode development"
    },
    "author": {
      "name": "user"
    },
    "devDependencies": {
      "@babel/core": "^7.19.3",
      "@babel/preset-env": "^7.19.3",
      "@babel/preset-react": "^7.18.6",
      "babel-cli": "^6.26.0",
      "babel-core": "^6.26.3",
      "babel-loader": "^8.2.5",
      "babel-plugin-transform-object-rest-spread": "^6.26.0",
      "babel-plugin-transform-react-jsx": "^6.24.1",
      "babel-preset-env": "^1.7.0",
      "source-map-loader": "^4.0.0",
      "webpack": "^5.74.0",
      "webpack-cli": "^4.10.0"
    }
  }
```
### ✔️ Expected result
The editor should work fine

### ❌ Actual result
Sometimes when the page is refreshed, the editor stops working and this error appears in the console:
Error: Item with the given id was not registered
![194312673-9436ab68-29dc-4869-b3ba-2ba50bf5abf9](https://user-images.githubusercontent.com/14995642/195110020-c80d3d50-6c71-4d65-84cc-19f70606494f.jpg)

The reference to the error is to this [line](https://github.com/ckeditor/ckeditor5/blob/69b04dedcff4f2a4fd4531f9435963f2c16c5916/packages/ckeditor5-watchdog/src/contextwatchdog.js#L426) of the file ckeditor5-watchdog/src/contextwatchdog.js

This doesn't always happen. I'd say it's random, but I haven't found an error pattern.

### 📃 Other details

- Browser: Chrome (105.0.5195.52) and Firefox (105.0) for Linux
- OS: Ubuntu

**Comment by mabryl** [comment]
Hi EvaGarzonBeltran,

Thank you for bringing this issue to our attention. I tried recreating this issue on my end but, unfortunately, I wasn't able to reproduce it. I understand that it appears randomly, but without precise steps needed to recreate this issue, it will be tricky to debug.  
  
It would be greatly appreciated if you could provide us with a more detailed path to recreating this issue.  
  
For example, would you be able to determine what is the origin of the id that can be seen in your error message?

Feel free to reach out if you have further questions.

**Comment by EvaGarzonBeltran** [comment]
I stopped using context because it was not necessary for my component and I could not investigate more. But I can tell you, for example, that the id was automatically generated. That id wasn’t in my code

**Comment by mabryl** [comment]
Thanks for letting us know. I did some more testing on my end and and this time I was able to reproduce your issue with `getWatchdog()` when trying to use Context, so it's possible that we have a bug somewhere.

We'll be debugging this further and I'll make sure to update this thread if we find anything out.

Thanks for using our products and for your help in investigating this issue.

**Comment by amitShimon1983** [comment]
Hey, happy to join that conversation. unfortunately, we have the same bug as the author with the same setup how can we recover after that error?

**Comment by mabryl** [comment]
Hi @EvaGarzonBeltran, @amitShimon1983,

Thanks for reaching out and for bringing this issue to our attention.

Our team had a closer look at this case recently and we believe we managed to fix it. Check [this thread](https://github.com/ckeditor/ckeditor5-react/issues/339) for more info.

Hence, I'll close this issue now but if it persists for you, feel free to reopen it :)
