### ISSUE TITLE
how to set the editor readonly?

### ISSUE THREAD

**Issue by zhangwei900808** [ckeditor/ckeditor5-react#332]
how to set the editor readonly?

**Comment by pomek** [comment]
You can specify the `disabled` property on `<CKEditor>` element. You can find a list of all component properties in the [React rich text editor component](https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/frameworks/react.html#component-properties) guide.

**Comment by zhangwei900808** [comment]
@pomek yes It's Worked! very thks
