### ISSUE TITLE
React production build freezes when using document lists

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5-react#345]
### Steps:
1. Create a React app with editor containing document lists plugin (using `yarn add file` approach)
2. Build the app using `yarn build`
3. Open the app and try either:
    - initializing it with list in the content
    - setting data with list in the content
    - pasting list into the editor, from another CKEditor

### Result:
The app freezes completely, whole page/browser tab becomes unresponsive.

### Other:
- Everything works fine in the development mode. **Only after building the app for production the problem occurs.**
- Happens when adding editor build with [`yarn add file` approach](https://ckeditor.com/docs/ckeditor5/latest/installation/frameworks/react.html#integrating-a-build-from-the-online-builder). I tired [building the editor from source](https://ckeditor.com/docs/ckeditor5/latest/installation/frameworks/react.html#integrating-ckeditor-5-built-from-source) and it worked fine then.

**Comment by psmyrek** [comment]
From ckeditor/ckeditor5#12946:

> In short, `create-react-app` uses by default very loose `browserslist` rules for production environment, that cause the generated (minified) code of the application targets the ES5. This in turn causes that the Babel (probably) does not handle properly the inline destructuring inside a `for of` loop with a generator.

Workaround before the fix is released: change the `browserslist` for production environment to e.g. `defaults` in `package.json` in your React app.

```
"browserslist": {
  "production": [
    "defaults"
  ],
  "development": [
    "last 1 chrome version",
    "last 1 firefox version",
    "last 1 safari version"
  ]
}
```
