### ISSUE TITLE
Problem while using generalHTMLSupport & sourceEditing plugin

### ISSUE THREAD

**Issue by shalapatil** [ckeditor/ckeditor5-react#375]
Hello, 
I was facing similar problem like https://github.com/ckeditor/ckeditor5-react/issues/155 for generalHTMLSupport and sourceEditing plugin
But when I add these two in plugins, I get `Cannot read properties of undefined (reading 'generalHTMLSupport')` 

I am using custom ckeditor5 with react. 

config is defined as 
`const CKEDITOR_BASE_CONFIG_FOR_PRESETS = {
 plugins: [
 window.CKEditor5.autoformat.Autoformat,
  window.CKEditor5.basicStyles.Bold,
  ..........
 window.Ckeditor5.generalHTMLSupport.GeneralHTMLSupport,`],
toolbar: {.....}`

Any help will be really appreciated. 
Thanks

_Originally posted by @shalapatil in https://github.com/ckeditor/ckeditor5-react/issues/155#issuecomment-1540231361_

**Comment by shalapatil** [comment]
I am following second approach (custom build) from this - https://www.thirdrocktechkno.com/blog/how-to-integrate-ckeditor5-in-strapi/
I have not imported it 
because,
If I import it like following 
`import GeneralHtmlSupport from '@ckeditor/ckeditor5-html-support/src/generalhtmlsupport';`
it gives "ckeditor-duplicated-modules error". 

if I don't import then I get - "Cannot read properties of undefined (reading 'generalHTMLSupport')" error

**Comment by Witoso** [comment]
It's a third-party integration, and I cannot help here a lot. As far as I can see those plugins are already added to this package, so I'm not sure why you need to load them. Consult maybe the developer of https://github.com/nshenderov/strapi-plugin-ckeditor/tree/master.

**Comment by shalapatil** [comment]
Okay, Thank you so much @Witoso  !

**Comment by shalapatil** [comment]
Hello, 
I am using custom build created by ckeditor team only
I have cloned https://github.com/ckeditor/strapi-plugin-ckeditor this and added my custom plugins there. 
I have posted same question on  that repo as well but not getting any response from there.
