### ISSUE TITLE
ReOpening: https://github.com/ckeditor/ckeditor5-react/issues/375

### ISSUE THREAD

**Issue by shalapatil** [ckeditor/ckeditor5-react#384]
Hello,
this is regarding my prev question: https://github.com/ckeditor/ckeditor5-react/issues/375
I am using custom build created by ckeditor team only
I have cloned https://github.com/ckeditor/strapi-plugin-ckeditor this and added my custom plugins there.
I have posted same question on that repo as well but not getting any response from there.

**Comment by martnpaneq** [comment]
Hi @shalapatil.

Could you please provide us with a repository containing your code so we can reproduce the issue?

**Comment by corymharper** [comment]
@martnpaneq I've just opened up #391 with a fairly detailed description and reproduction instructions.

**Comment by Witoso** [comment]
@shalapatil we will handle your issue in the strapi repo (https://github.com/ckeditor/strapi-plugin-ckeditor/issues/64). And I will close this one.
@corymharper it looks like you commented on the wrong issue The link you posted is not related to this case.
