### ISSUE TITLE
how to prevent data overriding which contains tbody element with id has been lost from ckeditor5 source editing tool reactjs

### ISSUE THREAD

**Issue by bharath07v** [ckeditor/ckeditor5-react#385]
how to prevent data overriding which contains tbody element with id has been lost from ckeditor5 source editing tool reactjs

**Comment by Witoso** [comment]
Sorry, it's impossible to understand what setup you have, where's the problem, and what plugins you use. Please file an issue with specific information, as well as the expected vs actual result (bug issue template may help here).
