### ISSUE TITLE
Check props.data in the componentDidUpdate() lifecycle

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/ckeditor5-react#39]
Follow-up of the https://github.com/ckeditor/ckeditor5-react/issues/37 and https://github.com/ckeditor/ckeditor5-react/issues/37#issuecomment-422707443

https://github.com/ckeditor/ckeditor5-react/blob/383b25d35beb54788f91185ea6c30615b56bb2b6/src/ckeditor.jsx#L18-L22

As @pomek proposed, we should check if the `this.props.data` is equal to `undefined` to prevent an infinite update loop.

**Comment by ma2ciek** [comment]
Not sure if this should be marked as a bug or as an enhancement 😄

**Comment by pomek** [comment]
Mhm, I proposed aborting the update editor's data if `this.props.data` does not exist:

```js
// Aborts updating the editor's data if "data" property wasn't specified.
if ( !( 'data' in this.props ) ) { 
  return; 
}
```

**Comment by pomek** [comment]
And of course, it's a bug that occurs in very specified environments.
