### ISSUE TITLE
CKEditor cannot be used as a JSX component.

### ISSUE THREAD

**Issue by 2Who** [ckeditor/ckeditor5-react#394]
Hello,
i am trying to use the CKEditor 5 in my React Typescript project.
It uses the code from the office guide [https://ckeditor.com/docs/ckeditor5/latest/installation/integrations/react.html](https://ckeditor.com/docs/ckeditor5/latest/installation/integrations/react.html)
Since i am working with typescript the file is App.tsx, which throws the error: 

> 'CKEditor' cannot be used as a JSX component.
>   Its type 'typeof CKEditor' is not a valid JSX element type.
>     Types of construct signatures are incompatible.
>       Type 'new <TEditor extends Editor>(props: Props<TEditor>) => CKEditor<TEditor>' is not assignable to type 'new (props: any) => Component<any, any, any>'.
>         Type 'CKEditor<Editor>' is missing the following properties from type 'Component<any, any, any>': context, setState, forceUpdate, props, and 2 more.ts(2786)

But when i change the type of my file from App.tsx => App.jsx the error vanishes.
How can i use the CKEditor 5 with React and Typescript with .tsx?

This is how my code looks:
```
import ClassicEditor from '@ckeditor/ckeditor5-build-classic';
import { CKEditor } from '@ckeditor/ckeditor5-react';
import * as React from 'react';

function App() {
    return (
        <div className='App'>
            <CKEditor
                editor={ClassicEditor}
                data="<p>Hello from CKEditor 5!</p>" />
        </div>
    );
}

export default App;
```

**Comment by Witoso** [comment]
[Please check the TS setup in our demo](https://github.com/ckeditor/ckeditor5-react/tree/master/demo-react-18). It may be related to `tsconfig` or some configuration setup on your side.

**Comment by 2Who** [comment]
Thank you for the hint. Adding the other configurations solved the problem.
