### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'getAttribute')

### ISSUE THREAD

**Issue by 2Who** [ckeditor/ckeditor5-react#395]
Hello,

i am trying to replicate the guide from [https://ckeditor.com/docs/ckeditor5/latest/framework/tutorials/implementing-an-inline-widget.html](https://ckeditor.com/docs/ckeditor5/latest/framework/tutorials/implementing-an-inline-widget.html) in React with Typescript, but i get the following error when running the project:
![image](https://github.com/ckeditor/ckeditor5-react/assets/46811902/e7ed8a84-c096-4c55-ae9c-e6af9e4f3077)

My code: [https://github.com/2Who/ckeditor-test](https://github.com/2Who/ckeditor-test)

I have been searching the other issues and the internet, but to no prevail.
What do i overlook?

Thank you for your help in andvance!
Regards Niklas

**Comment by Witoso** [comment]
Hey! I only gave a quick look at the `package.json` and I don't see all dependencies from the tutorial installed into your project. Could you make sure you have all the required packages?

**Comment by 2Who** [comment]
Hey Witoso, I added all the packages listes in the guide to the project and made sure, that everyone is installed.
Sadly the error still occures.
<img width="300" alt="image" src="https://github.com/ckeditor/ckeditor5-react/assets/46811902/6018dae6-e8e6-4759-933f-79f540681f85">

**Comment by Witoso** [comment]
In this case, we would need to take a look at the code as this is a very generic error. If you can, please share it with us, and we will try to take a look.

**Comment by 2Who** [comment]
My code is here on GitHub: [https://github.com/2Who/ckeditor-test](https://github.com/2Who/ckeditor-test)

**Comment by 2Who** [comment]
I did a bit more testing and the error seems to appear, when I try using the ckeditor5-editor-classic in a React App instead of the ckeditor5-build-classic. But since I am building a plugin to change the editor i cannot use the build.

**Comment by yhchoi9999** [comment]
I have the same problem too. Did you solve it?

**Comment by Witoso** [comment]
@2Who I'm a bit unsure how you created the package and how webpack works in it. Did you eject the React?Please read the guide on how to set up React, and choose one of the options from [the customizing the builds](https://ckeditor.com/docs/ckeditor5/latest/installation/integrations/react.html#customizing-the-builds).

**Comment by 2Who** [comment]
Hi @Witoso ,
after ejecting React and modifing the webpack.config.js adding plugins to the React Version of the ckeditor finally worked.
It seems like these steps are mandatory to manually configure the webpack.config.js, even though it seems weird that you need to manually configure the webpack,config.js for the ckeditor to work properly.
Anyways, thank you for giving a broad hint, since I didn't considered it necessary when i first tried it.

With best regards,
Niklas

**Comment by Witoso** [comment]
I'm glad you found the solution, have fun with our editor!
