### ISSUE TITLE
ERR! 404 Not Found: cke5-react@latest

### ISSUE THREAD

**Issue by BenEdgeContra** [ckeditor/ckeditor5-react#4]
npm install --save cke5-react @ckeditor/ckeditor5-build-classic throws error

**Comment by pomek** [comment]
It throws because the package wasn't published yet. See #2.

**Comment by Reinmar** [comment]
We're going to publish the first dev preview of this package in a couple of days. It will be called `@ckeditor/ckeditor5-react`. See #5.

**Comment by pomek** [comment]
The first version has just been published. 

Now using `npm install @ckeditor/ckeditor5-react` will install the package in version `1.0.0-beta.1`.

The feedback is welcome.
