### ISSUE TITLE
Not installing pkg in NodeJS version 20.9.0

### ISSUE THREAD

**Issue by keyurDevani5061** [ckeditor/ckeditor5-react#426]
I am updating my node js version 18 to 20 and my next js project version 13 to 14, but in my previous version, this npm package was running successfully when I updated my next js and node. At the moment, I am using Next Js version 14.0.3 and Node js version is 20.9.0., and I am unable to install this package.

**Comment by Witoso** [comment]
Could you share what errors do you see?

**Comment by keyurDevani5061** [comment]
![ck-edittor](https://github.com/ckeditor/ckeditor5-react/assets/119301800/9fce7137-ff6a-4995-a588-b872bcfd7154)
i am getting this type of error please check it

**Comment by Witoso** [comment]
You're using a wrong package name, it should be `@ckeditor/ckeditor5-react`.

**Comment by keyurDevani5061** [comment]
Thanks  its worked :)
