### ISSUE TITLE
Custom Installation setup via Online builder integrations with next-js does not work types in relation to 'create' property missing in '{ Editor: typeof Editor; EditorWatchdog: typeof EditorWatchdog; }', assistance needed!

### ISSUE THREAD

**Issue by jasmeet2021** [ckeditor/ckeditor5-react#433]
Errors:

`editor={Editor} `

Property 'create' is missing in type '{ Editor: typeof Editor; EditorWatchdog: typeof EditorWatchdog; }' but required in type '{ create(...args: any): Promise<Editor>; }'

`const data = editor.getData();`

Property 'getData' does not exist on type 'Editor'.

Code:

```
'use client';

import React from 'react';
import { CKEditor } from "@ckeditor/ckeditor5-react";
import Editor from "ckeditor5-custom-build";

const editorConfiguration = {
    toolbar: [
        'heading',
        '|',
        'bold',
        'italic',
        'link',
        'bulletedList',
        'numberedList',
        '|',
        'outdent',
        'indent',
        '|',
        'imageUpload',
        'blockQuote',
        'insertTable',
        'mediaEmbed',
        'undo',
        'redo'
    ]
};

function CustomEditor( props: any ) {
        return (
            <CKEditor
                editor={ Editor }
                config={ editorConfiguration }
                data={ props.initialData }
                onChange={ (event, editor ) => {
                    const data = editor.getData();
                    console.log( { event, editor, data } );
                } }
            />
        )
}

export default CustomEditor;
```

dependencies:

"@ckeditor/ckeditor5-react": "^6.2.0",
"ckeditor5-custom-build": "file:ckeditor5-40.1.0-6j2qd56wfdru",

**Comment by jasmeet2021** [comment]
Shifted to https://github.com/ckeditor/ckeditor5/issues/15437

**Comment by andrewlewinphsa** [comment]
I just came across this issue, the custom plugin's ckeditor.d.ts still needs the base class to be in the node modules. For example @ckeditor/ckeditor5-editor-decoupled or @ckeditor/ckeditor5-editor-classic. Depending on your setup. Without the base class installed, the create method will not be evaluated.
