### ISSUE TITLE
Add current timestamp to project name for builds on BrowserStack

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5-react#44]
ATM, every build has the same name: `ckeditor5 react`. Recently we upgraded a name of builds by adding a current timestamp as a suffix. This patch should be applied to this repo as well (https://github.com/ckeditor/ckeditor5-dev/pull/432).

cc: @oleq, @ma2ciek

**Comment by pomek** [comment]
Fixed in Vue in: https://github.com/ckeditor/ckeditor5-vue/pull/2/commits/01e7211f977bbcce0b5b61471b603d637980acf4.

**Comment by pomek** [comment]
@ma2ciek, could you handle it?

**Comment by Reinmar** [comment]
Isn't it done?

**Comment by pomek** [comment]
See #45.
