### ISSUE TITLE
How can I add the 'Source Editing' feature to CKEditor?

### ISSUE THREAD

**Issue by Forzali** [ckeditor/ckeditor5-react#451]
Hello, I'm encountering a 'duplicate-modules' error while trying to add the 'Source Editing' plugin to the CKEditor component. I've struggled to resolve this issue, but couldn't find informative resources online. Can you assist me in resolving this error and guide me on how to properly use the 'Source Editing' feature?

**Comment by Witoso** [comment]
Hi! Could you share a bit more info how you're adding a plugin and to which build? It's possible that you're trying to extend [a predefined build](https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/predefined-builds.html), which is not possible, and [a custom build](https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/quick-start-other.html) needs to be prepared. We are working on new installation methods which should resolve this issue once and for all: ckeditor/ckeditor5#15502

**Comment by Forzali** [comment]
Hello, I would like to explain step by step how I am trying to add the "Source Editing" feature to my React project. Here's a detailed breakdown:

1. Imported the packages in my code:

> import ClassicEditor from "@ckeditor/ckeditor5-build-classic";
import { CKEditor } from "@ckeditor/ckeditor5-react";
import { SourceEditing } from "@ckeditor/ckeditor5-source-editing";

2. Attempted to use the CKEditor component with Source Editing:

```
<CKEditor
  editor={ClassicEditor}
  data={""}
  config={{ plugins: [SourceEditing] }}
/>
```

**Issue**
I encountered the "ckeditor-duplicated-modules" error, and I'm having difficulty resolving it. I'm seeking assistance to understand where I might be going wrong and how to fix this issue.

![Screenshot 2024-01-31 at 12 39 56](https://github.com/ckeditor/ckeditor5-react/assets/63608913/e7b7d3e2-d88b-48da-a5e6-1b18d77aa992)
<img width="1479" alt="Screenshot 2024-01-31 at 12 42 52" src="https://github.com/ckeditor/ckeditor5-react/assets/63608913/0ef7f6c4-d41d-4b15-8843-234ed2cd9216">

Thank you for your help!

**Comment by Witoso** [comment]
So as I thought, you're adding a plugin to a predefined build which is not possible. [A custom build needs to be created.](https://ckeditor.com/docs/ckeditor5/latest/installation/integrations/react.html#customizing-the-builds).
