### ISSUE TITLE
Cannot use AI Assistant: CKEditorError: aiadapter-text-adapter-not-set

### ISSUE THREAD

**Issue by mike-niemand** [ckeditor/ckeditor5-react#453]
I create a custom build using the online tool adding only AIAssistant.

I add the build using 'npm file:./ckeditor5'

I embed it in the page as follows:

```
import { CKEditor } from "@ckeditor/ckeditor5-react";
import Editor from 'ckeditor5-custom-build/build/ckeditor';
```

and then

```
<CKEditor 
    editor={Editor} 
    data={data}
    config={{
        licenseKey: 'xxxxx',
        ai: {
            openAI: {
               requestHeaders: {
                    Authorization: 'Bearer xxxx'
               }
            }
        }
    }}                        
    onReady={editor => {
        //console.log('Editor is ready to use!', editor);
    }}
/>
```

But it always throws: _CKEditorError: aiadapter-text-adapter-not-set_

How do you set the adapter when you can't use plugins on custom builds?

**Comment by mike-niemand** [comment]
If I use a plugin on a custom build I get the duplicated modules issue. :(

**Comment by Witoso** [comment]
Hi @mike-niemand!

Regarding the error `CKEditorError: aiadapter-text-adapter-not-set`, make sure that in the plugins list you have [some adapter defined](https://ckeditor.com/docs/ckeditor5/latest/features/ai-assistant/ai-assistant-integration.html#making-connection), for example: `OpenAITextAdapter`.

> If I use a plugin on a custom build I get the duplicated modules issue. :(

Make sure you add a plugin in the custom build folder and file (`src/ckeditor.ts`), and you ran the build. Adding plugins to already built code may result in error. We are fixing this in https://github.com/ckeditor/ckeditor5/issues/15502.

**Comment by mike-niemand** [comment]
Cheers Witoso,

Got it sorted as follows:

1) Created a custom build with AIAssistant included
2) Edited the build ckeditor.ts to include 'OpenAITextAdapter '

```import { AIAssistant, OpenAITextAdapter } from '@ckeditor/ckeditor5-ai';```

3) Included 'OpenAITestAdapter' in the builtinPlugins section:

```
public static override builtinPlugins = [
		AIAssistant,
                OpenAITextAdapter,
		Autoformat,
		...
```

4) Rebuilt all
