### ISSUE TITLE
How can I preview the entire content in the editor at once with an isolated independent preview button to generate a preview in a separate section while keeping the security & sanitization in check.

### ISSUE THREAD

**Issue by jasmeet2021** [ckeditor/ckeditor5-react#464]
**I have a requirement of previewing the entire content in the editor area via  an independent html preview button which when clicked shows the preview of the editors entire content in a separate preview section with keeping the security & sanitizations in check**

I am using Nextjs with CKeditor-5-40.1.0 custom build.

To give more context I want to achieve the "preview editor data" button feature of previewing the content editor's like  this https://ckeditor.com/docs/ckeditor5/latest/features/html/html-embed.html#demo

![image](https://github.com/ckeditor/ckeditor5/assets/92725379/8f84f947-32b0-4eb8-9b63-458ccac292ac)

**Comment by Witoso** [comment]
Duplicate: ckeditor/ckeditor5#16139
