### ISSUE TITLE
React 19 support

### ISSUE THREAD

**Issue by DawidKossowski** [ckeditor/ckeditor5-react#478]
The integration is incompatible with the new React 19 version causing errors in RTC and multi-root. We need to rewrite / enhance parts of the integration to keep it compatible.

**Comment by Mati365** [comment]
Comment by @Acrophost 

> There seems to be an issue with our multi-root integration.
> After following the guide available in our documentation (https://ckeditor.com/docs/ckeditor5/latest/installation/integrations/react/react-multiroot.html) the roots are not initializing. The toolbar shows, but the only button that is available to press is undo button - it generates a bunch of errors when clicked
>
> https://github.com/cksource/qa-internal/assets/66953380/642d68f8-605a-48d9-96b2-02c1ece4dcd1
>
> I also checked collaboration samples for React with React 19 beta. The real-time collaboration samples throw an error and stop at white screen (including `real-time-collaboration-comments-outside-of-editor-for-react`, `real-time-collaboration-editor-multi-root-for-react` and `real-time-collaboration-revision-history-for-react`
> ```js
> Uncaught TypeError: S.render is not a function
>    at index.js:16:2203048
>    at index.js:16:2203115
>    at index.js:16:2203119
> ```
> `revision-history-for-react` and `track-changes-for-react` seem to be working correctly.

**Comment by Mati365** [comment]
@dufipl Please reopen https://github.com/cksource/qa-internal/issues/424, according to call that we made few days ago with @filipsobol (and others) we will merge it after merging new installation methods. It means that there were a lot of merge conflicts and it'll be required to test it again.

**Comment by Mati365** [comment]
@DawidKossowski as it's released in https://github.com/ckeditor/ckeditor5-react/releases/tag/v9.0.0 this issue might be closed.
