### ISSUE TITLE
Cannot integrate CKEditor 5 with React

### ISSUE THREAD

**Issue by eleumasc** [ckeditor/ckeditor5-react#48]
I am desperately trying to integrate CKEditor 5 with React, but it doesn't work. I have strictly followed the docs: I am aware of the Babel bug, I have tried to create the React app with both the versions 1 and 2 of create-react-app, I have tried to replace some parts of the ejected configuration (as specified in the relative issue https://github.com/facebook/create-react-app/issues/5387), but none of these attempts have made my app work. The error is always the same: `TypeError: Cannot read property '0' of undefined`. I also noticed that in the WebPack configuration file Tenser is used as minification tool, not Uglify.

```
> node -v
8.12.0
> npm -v
6.4.1
```

**Comment by Reinmar** [comment]
> I also noticed that in the WebPack configuration file Tenser is used as minification tool, not Uglify.

You mean, in a config file ejected from CRA2? Perhaps they switched to Tenser sooner than Webpack managed to do so.

@ma2ciek, where did they discuss those recent performance issues and switching to Tenser? I can't find the link now :(

**Comment by Reinmar** [comment]
> @ma2ciek, where did they discuss those recent performance issues and switching to Tenser? I can't find the link now :(

Got it: https://github.com/facebook/react/issues/13987

**Comment by Reinmar** [comment]
Although, it seems that at least for that bug, they just disabled one option of Uglify: 

https://github.com/instructure/canvas-lms/commit/4d0f3aaf569437f1eb4bb052c4f12ef88e16ea54

**Comment by pomek** [comment]
@eleumasc, could you share your webpack configuration? It the error still appears, it may mean that something is wrong with webpack.

**Comment by eleumasc** [comment]
Here it is: [config.zip](https://github.com/ckeditor/ckeditor5-react/files/2576160/config.zip)

**Comment by pomek** [comment]
Are you working on a Windows or Unix operating system? I am asking because your configuration works fine for me. If you're working on Windows, you should use the following RegExp for CKEditor 5 Builds:

```js
/@ckeditor[\\/]ckeditor5-build-.*/
```

**Comment by eleumasc** [comment]
Effectively I am working on Windows, and now it works! I can't  believe that the same WebPack configuration doesn't work equally on Windows like on Linux.
Anyway, very thanks!

**Comment by Baste111** [comment]
Hello .. I also used that configuration but CKEditor 5 with React still wont' work 

here's my config:

```
{
            test: /\.(js|mjs)$/,
            exclude: [/@ckeditor[\\/]ckeditor5-build-.*/],
            loader: require.resolve('babel-loader'),
            options: {
              babelrc: false,
              configFile: false,
              compact: false,
              presets: [
                [
                  require.resolve('babel-preset-react-app/dependencies'),
                  { helpers: true },
                ],
              ],
              cacheDirectory: true,
              // Don't waste time on Gzipping the cache
              cacheCompression: false,

              // If an error happens in a package, it's possible to be
              // because it was compiled. Thus, we don't want the browser
              // debugger to show the original code. Instead, the code
              // being evaluated would be much more helpful.
              sourceMaps: false,
            },
          },
```
