### ISSUE TITLE
Allow other events (e.g. onBlur) on editable container

### ISSUE THREAD

**Issue by wparrott-touchnet** [ckeditor/ckeditor5-react#49]
In our application, we validate form fields after the user has entered data by hooking onto the `onBlur` event. However, this behavior doesn't work with the current implementation of the CKEditor React component.

It'd be nice if we could pass extra props (`data-*` attributes, event handlers, etc) to the editor component and have them rendered along with the existing properties.

**Comment by wparrott-touchnet** [comment]
I realize there is a fair bit of overlap between this and #18, but thought that DOM events are a specific enough use case to create a separate ticket.

**Comment by pomek** [comment]
At this moment, you can use `onInit` callback to register events related to the editor:

```js
onInit( editor ) { 
    const viewDocument = editor.editing.view.document;
    
    viewDocument.on( 'focus', evt => {
		console.log( 'focus', evt );
	} );

	viewDocument.on( 'blur', evt => {
		console.log( 'blur', evt );
	} );
}
```

But maybe it has some sense to support those properties out-of-the-box. So a user could pass `onFocus` callback via config and the component could handle it.

**Comment by pomek** [comment]
At this moment, you can use `onInit` callback to register events related to the editor:

```js
onInit( editor ) { 
    const viewDocument = editor.editing.view.document;
    
    viewDocument.on( 'focus', evt => {
        console.log( 'focus', evt );
    } );

    viewDocument.on( 'blur', evt => {
        console.log( 'blur', evt );
    } );
}
```

But maybe it has some sense to support those properties out-of-the-box. So a user could pass `onFocus` callback via config and the component could handle it.

**Comment by wparrott-touchnet** [comment]
That will certainly work for what we need to do for now. I think it's still worth discussing whether to allow more things to be passed directly into the editor, but this reduces the urgency for me personally (based on current projects at my employer).

**Comment by pomek** [comment]
I agree.

**Comment by ma2ciek** [comment]
IMO we can provide this functionality as we do in other integrations (Angular and Vue). It simplifies some use cases without any knowledge about the editor and its details. I even don't know where we have a section about events like `focus`, `blur` in the https://ckeditor.com/docs/ckeditor5.

**Comment by pomek** [comment]
So in the React component, we miss `onBlur` and `onFocus` properties. Did I miss anything?

**Comment by ma2ciek** [comment]
We should have at least `onReady` / `onInit`, `onChange`, `onBlur` and `onFocus` IMO.

**Comment by pomek** [comment]
`onInit` and `onChange` are already available. The next two will be added soon.

**Comment by pomek** [comment]
@wparrott-touchnet, we've just released a new version of the `<CKEditor>` component (https://github.com/ckeditor/ckeditor5-react/releases/tag/v1.1.0) which gives a support for properties `onBlur` and `onFocus`.
