### ISSUE TITLE
Change the name to @ckeditor/ckeditor5-react and publish first dev preview

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-react#5]
People started landing here and reporting that this pkg is missing (#2, #4), so let's publish something.

TODO:

* [x] Review the README.
* [x] Write clearly that this is a developers' preview and that we need your feedback.
* [x] Change the name to `@ckeditor/ckeditor5-react` and update the docs.
* [x] https://github.com/ckeditor/ckeditor5-react/issues/5#issuecomment-394964843 - RegExps on Windows
* [x] https://github.com/ckeditor/ckeditor5-react/issues/9 - Check linter
* [ ] Publish!

**Comment by Reinmar** [comment]
Doh... without the following PRs: https://github.com/ckeditor/ckeditor5-editor-classic/pull/73, https://github.com/ckeditor/ckeditor5-editor-inline/pull/38, https://github.com/ckeditor/ckeditor5-editor-balloon/pull/19 releasing `@ckeditor/ckeditor5-react` does not make sense ;/ 

So, it's going to take us more than a week before we have to wait for the editors to be out (planned ~19.06).

**Comment by pomek** [comment]
I pushed a branch ([#t/5](https://github.com/ckeditor/ckeditor5-react/tree/t/5)) which contains some fixes for this repository (cleaned up package.json, added license file, etc.). 

It requires to attach our changelog generator and finally review the README and package.json.

Because we won't release the package now, I will back to the issue in the future.

**Comment by pomek** [comment]
TODO: Validate (and fix) the regexp on Windows environments.

**Comment by ma2ciek** [comment]
I'd suggest minifying the build and add a proper header to that file like we have in other builds.

**Comment by RaulEscobarRivas** [comment]
may I suggest changing the folder structure ? as you actually have to get the resource from the src file: 
```import CKEditor5 from 'cke5-react/src/ckeditor';```

maybe add an index.js in the package root folder ? or just get rid of the src folder and have the source file at the same level of the root ?

**Comment by pomek** [comment]
We will compile and minify the source file. The same we do with the [builds](https://github.com/ckeditor/ckeditor5-build-classic/tree/master/build). We want to also set up the build file as the main package file in [`package.json`](https://github.com/ckeditor/ckeditor5-build-classic/blob/7e54c8d9f365a983d00fcf0da2102d761f37f7b6/package.json#L27) so:

```js
import CKEditor5 from '@ckeditor/ckeditor5-react';
``` 

will be enough.

**Comment by cola9k** [comment]
Dear @Reinmar 
I tried to install @ckeditor / ckeditor5-react, but it did not work.
Will react no longer work with the Cke5 version?

**Comment by Reinmar** [comment]
As mentioned in the readme:

> NOTE: This package is not yet published on npm. It's a developer's preview available only through GitHub.
> 
> See https://github.com/ckeditor/ckeditor5-react/issues/5 for more information.

**Comment by Reinmar** [comment]
Some status update – we wanted to release this pkg ASAP, but it's blocked by breaking changes in `ckeditor5-core`. We couldn't release these changes last week due to their breaking nature, so the whole thing got delayed by ~3 weeks.

**Comment by tgroshon** [comment]
Looks like all the needed editor PRs except https://github.com/ckeditor/ckeditor5-editor-balloon/pull/19 have been merged!

How we doing now?

**Comment by Reinmar** [comment]
I'm on it. The release window is next week. That will unblock the React integration.

**Comment by RobrechtM** [comment]
What's the ETA for a stable npm package?

**Comment by Reinmar** [comment]
We have a delay with the release of CKEditor 5. It was meant to be this week but we didn't manage to make it and it will be out next week.

Then, we still need minimum a week to release the ckeditor5-react package. That's the minimum it may take.

**Comment by pomek** [comment]
The package should be published tomorrow or on Thursday.

**Comment by pomek** [comment]
The first version has just been published. 

Now using `npm install @ckeditor/ckeditor5-react` will install the package in version `1.0.0-beta.1`.

The feedback is welcome.
