### ISSUE TITLE
Containers not being created

### ISSUE THREAD

**Issue by phlfvry** [ckeditor/ckeditor5-react#50]
The toolbar and editable are directly rendered into the DOM without any containers. It would be helpful if these containers were automatically created to better match the styling documentation which assumes that these containers exist already.

**Comment by pomek** [comment]
If you're saying about `DecoupledEditor`, it's by design – see https://ckeditor.com/docs/ckeditor5/latest/api/module_editor-decoupled_decouplededitor-DecoupledEditor.html.

**Comment by pomek** [comment]
Would be good if you will explain what you exactly mean because I am not sure whether I understood correctly.

**Comment by phlfvry** [comment]
Sorry my first message was unclear. I was referring to the fact that the `.ck-toolbar` and `.ck-editor__editable` are not wrapped with `div`'s by default upon rendering. 

The example for the Document editor build on the CKEditor website shows an editor instance styled in a way that makes it look and feel as if you're using a word processing application instead of just typing into a text box. `.ck-toolbar` and `.ck-editor_editable` need to be children of container `div`s styled with CSS to achieve this experience. I assumed the Document editor build would look like a word processor application out-of-the-box but that was not the case.

> This type of an editor is dedicated to integrations which require a customized UI with an open structure, _allowing developers to specify the exact location of the interface_.

This sentence, especially the last fragment, allowed me to understand why the Document editor build doesn't come styled and the toolbar and editable elements don't come wrapped: it has to be done manually.

So with that, I'll be closing this issue. Thanks for pointing me in the right direction! @pomek
