### ISSUE TITLE
Next.js images not exported to pdf document

### ISSUE THREAD

**Issue by AlexanderPershin** [ckeditor/ckeditor5-react#509]
Hello. I'm trying to create pdf document from html. This initial html created inside template string from object. Images added to this template string like so:
`<img src="/icons/bookmark.svg" />`
Here `/icons/bookmark.svg` is in Next.js `public` directory. These icons displayed correctly in the editor itself, but when I'm trying to export to pdf it contains broken images
Is there a way to fix this bug?

---

These icons are actually extracted from `bootstrap icons` pack, so if there is a way to integrate `bootstrap icons` instead of Next.js images then this will also work

**Comment by Witoso** [comment]
Hey, the PDF is generated on the server, the images' links need to be [absolute](https://ckeditor.com/docs/ckeditor5/latest/features/converters/export-pdf.html#images), they won't be accessible otherwise.

**Comment by AlexanderPershin** [comment]
> Hey, the PDF is generated on the server, the images' links need to be [absolute](https://ckeditor.com/docs/ckeditor5/latest/features/converters/export-pdf.html#images), they won't be accessible otherwise.

Got it. For now ended up converting all the icons to dataurl to embed them into loaded html data. Thanks for the response
