### ISSUE TITLE
Toolbar doesn't work properly when rendering two editors on the same page.

### ISSUE THREAD

**Issue by zelongc** [ckeditor/ckeditor5-react#54]
hi, I met this issue:

When I try to render/import two ck-editor elements on the same page. the Font Size control options changed to ['full size Image', 'Side image', 'Enter image caption', 'Left aligned image', 'Centered image'] instead of the expected ['tiny', 'small', 'default'....]

I tried to reproduce it in JSFiddle hope it could be of help:
https://jsfiddle.net/dchmn7pz/4/

I am importing 
```
<script src="https://cdn.ckeditor.com/ckeditor5/11.1.1/decoupled-document/ckeditor.js"></script>
<script src="https://cdn.ckeditor.com/ckeditor5/11.1.1/inline/ckeditor.js"></script>
```
on the top of the script. In this case, the options of Font Size Control is showing image control options..

When I remove 
```
<script src="https://cdn.ckeditor.com/ckeditor5/11.1.1/inline/ckeditor.js"></script>
```

and leave ```<script src="https://cdn.ckeditor.com/ckeditor5/11.1.1/decoupled-document/ckeditor.js"></script>```  alone. The problem disappeared.

I am wondering if I did something wrong here or this is expected?

Thanks in advance!

**Comment by pomek** [comment]
Hi,

I am not sure that I understood your issue correctly but on the attached demo, everything seems to work.

![image](https://user-images.githubusercontent.com/2270764/48997827-7e651980-f151-11e8-922c-cd7cb3d2996a.png)

Could you write step by step how to reproduce the issue?

PS: You shouldn't load two builds on the same page. Read more about it here – https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/advanced-setup.html#scenario-3-using-two-different-editors. This page contains a solution how to use two and more editors on the same page.

**Comment by zelongc** [comment]
Hi, thanks very much for the reply. 

I just updated the JsFiddle, then it is showing the editor with problem status:

![ckeditor-broken-ui](https://user-images.githubusercontent.com/20151147/49003727-a63a9880-f1b6-11e8-8a02-55d51f0a40d5.PNG)

Apparently I did something against what CKEditor suggests in the document you provided above (You are absolutely right in your PS bit).

What I did was, I imported two built-in editor in a single page. like this:

```
<script src="https://cdn.ckeditor.com/ckeditor5/11.1.1/decoupled-document/ckeditor.js"></script>
<script src="https://cdn.ckeditor.com/ckeditor5/11.1.1/inline/ckeditor.js"></script>
```

This is against what CKEditor document suggested: 
> Do not load two builds on one page. This is a mistake which leads to:
>
> Code duplication. Both builds share up to 99% of the code, including CSS and SVGs. By loading them twice you make your page unnecessarily heavy.
> Duplicated CSS may lead to conflicts and, thus, broken UI of the editors.
> Translation repository gets duplicated entries which may cause loading incorrect strings with translations.

So to anyone who is meeting the issue as I did and looking into this thread. Please go check 
the link @pomek post above. It solves your problem!

**Comment by pomek** [comment]
Glad that I could help you.
