### ISSUE TITLE
onChangeInitializedEditors isn't fired during startup

### ISSUE THREAD

**Issue by glynam1** [ckeditor/ckeditor5-react#552]
I have a component like
```   return (
      <>
          <CKEditorContext
            context={DecoupledEditor.Context}
            contextWatchdog={DecoupledEditor.ContextWatchdog}
            config={contextConfig}
            onReady={(context: any, watchdog: any) => {
              console.log(context)
            } }
            onChangeInitializedEditors={ editors => {
              console.log( editors );
            }}
            onError={(error: any, details: any) => {
              console.log(error)
              console.log(details);
            }}
          >
            {document.sections.map((section) => (
              <SectionedContentEditor
                key={`sectionEditor${section.position}`}
                section={section}
                handleAutoSave={handleAutoSave}
              />
            ))}
          </CKEditorContext>
      </>
```

and child

```        
<CKEditor
          editor={DecoupledEditor}
          config={config}
          contextItemMetadata={{
            name: `Section${section.position}`,
          }}
          onError={(error: any, details: any) => {
            console.log(error)
            console.log(details);
          }}
        />
```

When using Ckeditor v43.3.0 and ckeditor-react v9.1.0 (or even latest)

This event does not fire. I have tried debugging it and the callback is set up but then the callback from the editor never seems to be fired.

Any insight?

**Comment by glynam1** [comment]
To add to this, I've added onReady to the child CKeditor instance, and that callback fires.

**Comment by Mati365** [comment]
@glynam1 Hi! Can you prepare minimal stackblitz demo with your setup? 🙏 It will help me with debugging this. I checked it today with `ClassicEditor` and it was working correctly so it may be related to specific configuration.

**Comment by glynam1** [comment]
Hi @Mati365 ,

As requested here is a stackblitz with the issue reproduced. 

This seems to be an issue in react 17, and it fires in react 18

https://stackblitz.com/edit/ckeditor5-react-tm7c7h?file=package.json,src%2FApp.tsx,src%2Fmain.tsx

**Comment by Mati365** [comment]
Thank you, I'll check that! @glynam1

**Comment by Mati365** [comment]
I proposed fix https://github.com/ckeditor/ckeditor5-react/pull/555
