### ISSUE TITLE
Any documentation on how to include and configure additional languages?

### ISSUE THREAD

**Issue by piuccio** [ckeditor/ckeditor5-react#58]
I got it working, but it would be nice to add the steps on the documentation page

```js
import CKEditor from '@ckeditor/ckeditor5-react';
import ClassicEditor from '@ckeditor/ckeditor5-build-classic';
import '@ckeditor/ckeditor5-build-classic/build/translations/ja';

<CKEditor
  editor={ClassicEditor}
  config={{
    language: 'ja',
  }}
/>
```

**Comment by ma2ciek** [comment]
We have this in the Angular docs already so it would be nice to have them too for the React component as well.

**Comment by srikarsingh** [comment]
I tried to set height and width for through the config attribute in react js but the editor is still remains same. config is not applied

**Comment by pomek** [comment]
See the [EditorConfig](https://ckeditor.com/docs/ckeditor5/latest/api/module_core_editor_editorconfig-EditorConfig.html) object to learn about all available configuration options. There aren't height nor width options. The editor's width/height could be modified using CSS. Please, take a look on this comment – https://github.com/ckeditor/ckeditor5-react/issues/65#issuecomment-465972026 – and the comment below in attached link.

**Comment by srikarsingh** [comment]
Thank you for the answer

**Comment by mocy111** [comment]
it's has work for me !!  
Thank you !!!!!!!
