### ISSUE TITLE
ImageToolbar not showing

### ISSUE THREAD

**Issue by nsoeth** [ckeditor/ckeditor5-react#67]
Hi,

I implemented the CKEditor in React the following way:

```
    <CKEditor
            editor={DecoupledEditor}
            onInit={(editor: any): void => {
              editor.plugins.get('FileRepository').createUploadAdapter = (loader: any): UploadAdapter => {
                return new UploadAdapter({ loader, top: this.props.top });
              };
              editor.ui.view.editable.element.parentElement.insertBefore(
                editor.ui.view.toolbar.element,
                editor.ui.view.editable.element
              );
            }}
            onChange={(event: any, editor: { getData: () => string; }): void => {
              const data = editor.getData();
              this.onInputChange(data);
            }}
            config={{
              image: {
                toolbar: ['imageStyle:alignLeft', 'imageStyle:full', 'imageStyle:alignRight', '|', 'imageTextAlternative']
              }
            }}
            data={this.state.body}
          />
```

It works fine so far but the image toolbar is missing. Did I configure something wrong or is it not supported yet? my imports are the following:

```
import CKEditor from '@ckeditor/ckeditor5-react';
import { UploadAdapter } from './UploadAdapter/UploadAdapter'; //my own adapter
import DecoupledEditor from '@ckeditor/ckeditor5-build-decoupled-document';
```

**Comment by pomek** [comment]
Just to be sure. After clicking an image in the editor, the toolbar does not appear? 

![image](https://user-images.githubusercontent.com/2270764/53326561-31c2e300-38e6-11e9-8352-9a2c9f4d5d10.png)

**Comment by nsoeth** [comment]
Yes, that is correct
![capture2](https://user-images.githubusercontent.com/20333484/53326743-954d1080-38e6-11e9-813f-dd9f4eaeb30e.JPG)

**Comment by pomek** [comment]
I was trying to reproduce your issue but everything works fine for me. Does your console print anything? 

Could you put the entries below as a value for `config.image`?

```js
{
	styles: [
		'full',
		'alignLeft',
		'alignRight'
	],
	toolbar: [
		'imageStyle:alignLeft',
		'imageStyle:full',
		'imageStyle:alignRight',
		'|',
		'imageTextAlternative'
	]
},
```

If it does not help, try to remove the entire `config.image` property. Decoupled Editor has defined the same values by default. If it still does not help, I will be trying to reproduce the issue in order to help you.

**Comment by nsoeth** [comment]
Got it. My fault. User it in an office ui fabric modal, which has a higher z-index. Adding
```
.ck-rounded-corners .ck.ck-balloon-panel {
    z-index: 1000001;
  }
```

to my css displays the toolbar. It is not working yet (nothing's done on click) but I'll try to fix it. Works outside of the modal, though. Thank you.
