### ISSUE TITLE
Module parse failed: Unexpected token (36:9). You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by ghost** [ckeditor/ckeditor5-react#7]
I'm using this in package.json:

```json
...
"cke5-react": "github:ckeditor/ckeditor5-react",
"@ckeditor/ckeditor5-build-classic": "10.1.0",
...
```

in my code this:

```js
...
import CKEditor from "cke5-react/src/ckeditor";
import ClassicEditorBuild from "@ckeditor/ckeditor5-build-classic";
...
```

but it says:

```log
./node_modules/cke5-react/src/ckeditor.js
Module parse failed: Unexpected token (36:9)
You may need an appropriate loader to handle this file type.
|       // Render <div> element which will be replaced by CKEditor.
|       render() {
|               return <div ref={ ref => ( this.domContainer = ref ) }></div>;
|       }
|
```
**Why?**

**Comment by pomek** [comment]
You need to attach JSX loader for the specific component file in your Webpack configuration.

**Comment by johnunclesam** [comment]
I'm using `create-react-app` without ejecting.

**Comment by johnunclesam** [comment]
If I copy the code in a component in my project everything works!

**Comment by pomek** [comment]
Could you install the package using the [`#t/5`](https://github.com/ckeditor/ckeditor5-react/tree/t/5) branch?

It contains a lot of improvements required for the #5. The issue that you described shouldn't occur anymore.

**Comment by johnunclesam** [comment]
Yes it works with that branch. But the problem now is `componentWillReceiveProps( newProps ) {` which freeze my component at startup.
