### ISSUE TITLE
Cannot read property 'getAttribute' of null

### ISSUE THREAD

**Issue by sirajalam049** [ckeditor/ckeditor5-react#81]
I am following [this](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/quick-start.html#creating-a-simple-plugin) tutorial to create a custom plugin for `code snippet`. 

I've created the app using `create-react-app` command. 
I've read [this](https://github.com/ckeditor/ckeditor5-react/issues/42) issue and its solution couldn't work for me.

**Comment by Mgsy** [comment]
Hello, could you paste the entire error message from your console? Additionally, please share with us your webpack config.

**Comment by pomek** [comment]
If you are using `CRA@2`, try to follow the steps listed in this instruction – https://github.com/ckeditor/ckeditor5/blob/7aaa7241a01f7ff38d19ddb2061c9a60c7b6bc60/docs/builds/guides/frameworks/react.md#create-react-app2.

**Comment by pomek** [comment]
Omg, GitHub…  Sorry for closing/reopening.

The attached link above is a part of PR (https://github.com/ckeditor/ckeditor5/pull/1605) that improves the React Integration guide in our documentation.

**Comment by sirajalam049** [comment]
Thank You @pomek , that documentation for CRA@2 helped me, but it is not loading the css.
My editor is looking like this

![image](https://user-images.githubusercontent.com/22110988/54945925-ffe08300-4f5c-11e9-929c-f9c7845a7da1.png)

**Comment by pomek** [comment]
Could you check the style of the dropdown element? You can use the browser's inspector to check it out. It seems like something is overwriting our CSS.

**Comment by sirajalam049** [comment]
Nothing seems overridden here by something else. All the css are provided by CK.
![image](https://user-images.githubusercontent.com/22110988/55111234-f17e9c80-50ff-11e9-961f-68e1e8bdac45.png)

**Comment by pomek** [comment]
Weird. Could you write step by step what you did? I'll try to reproduce the issue on our side.

**Comment by sirajalam049** [comment]
OK, let me create a minimal react app to show what I've done

**Comment by sirajalam049** [comment]
I have created the app.
Steps that I followed is,
1. `npx create-react-app app-name --typescript`
2. installed the CKEditor packages as given in the package.json
3. Added a custom plugin named `CKEditorCodeSnippetPlugin` in the root directory.
4. Edited the `webpack.config.js` as per the documentation you mentioned above.
Still getting the results as attached above
https://github.com/sirajalam049/ckeditor-integartion-minimal-project

**Comment by pomek** [comment]
AFAICS, you try to add [the `CKEditorCodeSnippetPlugin` plugin](https://github.com/sirajalam049/ckeditor-integartion-minimal-project/blob/67a70316944b4c5af694c45711a07e7303b0e9c6/src/CKEditorCodeSnippetPlugin.ts) to [ready-to-use build](https://github.com/sirajalam049/ckeditor-integartion-minimal-project/blob/67a70316944b4c5af694c45711a07e7303b0e9c6/src/App.tsx#L5) which won't work and is not the correct way how to add plugins to the editor. See: https://github.com/ckeditor/ckeditor5/issues/1047#issuecomment-393068327.
