### ISSUE TITLE
How do I apply to my project?, before build

### ISSUE THREAD

**Issue by SinYooDong** [ckeditor/ckeditor5-react#84]
hi,

How do I put an additional plug-in and a builed version into my project?

Our team member put it in node_modules/@coeditor. Is there any better way?

I've been looking for a similar issue for two hours and I've given up.

i use next.js

thank you

**Comment by Mgsy** [comment]
Hello, did you follow our [installing plugins guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html)?

**Comment by SinYooDong** [comment]
Thank you, I missed the corresponding document.

I'll follow the instructions.
