### ISSUE TITLE
CKFinder: Cannot read property 'modal' of undefined

### ISSUE THREAD

**Issue by nsoeth** [ckeditor/ckeditor5-react#86]
I use CKFinder5 with React and cannot user the CKFinder. My Code:

```
import * as CKEditor from '@ckeditor/ckeditor5-react';
import * as DecoupledEditor from '@ckeditor/ckeditor5-build-decoupled-document';

[...]

<CKEditor
  editor={DecoupledEditor}
  onInit={(editor: any): void => {	
	editor.ui.view.editable.element.parentElement.insertBefore(
	  editor.ui.view.toolbar.element,
	  editor.ui.view.editable.element
	);
  }}
  onChange={(event: any, editor: { getData(): string; }): void => {
	const data = editor.getData();
	this.onInputChange('body')(data);
  }}
  config={{
	toolbar: ['heading', '|', 'fontSize', 'fontFamily', '|', 'bold', 'italic', 'underline', 'strikethrough', 'link', '|', 'alignment:left', 'alignment:center', 'alignment:right', '|', 'numberedList', 'bulletedList', '|', 'ckfinder', 'insertTable', '|', 'undo', 'redo'],
	ckfinder: {
	  uploadUrl: '/'
	}
  }}
  data={this.state.body}
/>
```

When I click the ckfinder button in my toolbar, the console throws the following error:
`Uncaught TypeError: Cannot read property 'modal' of undefined`

It seems like the error is thrown here:
`window.CKFinder[e](n)`

Any ideas? The rest is working fine.

**Comment by jodator** [comment]
Have you added `ckfinder.js` to a webpage? Check the [CKFinder for CKEditor5 integration feature guide](https://ckeditor.com/docs/ckeditor5/latest/features/image-upload/ckfinder.html#configuring-the-full-integration).

**Comment by nsoeth** [comment]
No since the plugin is already enabed by the decoupled editor, I thought it would be initialized automatically. I'll try implementing it in my webpack-entry.

**Comment by jodator** [comment]
@nsoeth The `ckfinder.js` is the CKFinder application code - it can be [downloaded from our page](https://ckeditor.com/ckfinder/download/) as CKFinder 3 can be used as a standalone product.

**Comment by nsoeth** [comment]
Thanks for clarification. It didn't work though, still the same error.

**Comment by Mgsy** [comment]
I'm able to reproduce it. In CKEditor 5 builds integrated with React, clicking on the CKFinder icon throws the error in the console.

**Comment by pomek** [comment]
And does it work without React? Are you able to check it out?

**Comment by Mgsy** [comment]
>And does it work without React? Are you able to check it out?

Sorry, I forgot to mention - it doesn't occur without React.

**Comment by pomek** [comment]
Without TypeScript (pure JS / JSX), everything seems to work:

![image](https://user-images.githubusercontent.com/2270764/56017624-28f46800-5d00-11e9-9d3b-707df6bbd0e2.png)

I added the following code before ending `</head>` tag in the main `index.html` file:

```html
<script src="https://ckeditor.com/apps/ckfinder/3.4.5/ckfinder.js"></script>
<style>
  #ckf-modal {
    z-index: 10101 !important;
  }

  .ckf-file-preview-root {
    z-index: 10110 !important;
  }
</style>
```

Then I used ready-to-use `@ckeditor/ckeditor5-build-decoupled-document` from NPM (`v12.1.0`). Yesterday we released a new version of the build (and the rest of our packages). Maybe that's why everything works.

**Comment by pomek** [comment]
`@ckeditor/ckeditor5-build-decoupled-document@12.0.0` works as well.

**Comment by pomek** [comment]
Moving CKFinder asset at the end of the body tag does not change anything. It still works. 

```html
<body>
  <noscript>You need to enable JavaScript to run this app.</noscript>
  <div id="root"></div>
  <!--
    This HTML file is a template.
    If you open it directly in the browser, you will see an empty page.

    You can add webfonts, meta tags, or analytics to this file.
    The build step will place the bundled scripts into the <body> tag.

    To begin the development, run `npm start` or `yarn start`.
    To create a production bundle, use `npm run build` or `yarn build`.
  -->
  <script src="https://ckeditor.com/apps/ckfinder/3.4.5/ckfinder.js"></script>
</body>
```

**Comment by Mgsy** [comment]
I've reviewed it once again and I was able to successfully integrate CKFinder with CKEditor 5 + React. Make sure that your packages are updated.

Quick steps:
1. Create an app with `create-react-app`.
1. `npm install --save @ckeditor/ckeditor5-react @ckeditor/ckeditor5-build-decoupled-document`.
1. Paste your code to the component.
1. Add `<script src="https://ckeditor.com/apps/ckfinder/3.4.5/ckfinder.js"></script>` to your page.
1. `yarn start`.

**Comment by veselllov** [comment]
![image](https://user-images.githubusercontent.com/14116422/122097167-0ac2af00-ce18-11eb-8b43-fcb1993fe70f.png)

Similar problem has in Vue

**Comment by TukuToi** [comment]
There is no need for custom built plugins. Just build a CKFinder instance with https://ckeditor.com/ckeditor-5/online-builder/ and include CKFinder. The very demo in the package generated will have the precise same issue.

**Comment by Stephen-Almendinger** [comment]
Can confirm that this is still an issue. I pulled up what I built with the online builder and ran the sample. The CKFinder is broken with the same error messaging about the modal.

**Comment by SupportG** [comment]
Has anyone solved this problem? 
1. I create bundle https://ckeditor.com/ckeditor-5/online-builder/
2. And run sample/index.html  

![image](https://user-images.githubusercontent.com/7991213/205475785-4d1b0244-7298-49c0-bd18-4fb983456dd8.png)

**Comment by peng093** [comment]
It's almost 2023 and the problem hasn't been solved yet

**Comment by SupportG** [comment]
> 
I solved the problem
https://ckeditor.com/docs/ckeditor5/latest/installation/frameworks/vuejs-v3.html#integrating-a-build-from-the-online-builder

**Comment by SupportG** [comment]
> It's almost 2023 and the problem hasn't been solved yet



> It's almost 2023 and the problem hasn't been solved yet

I solved the problem
https://ckeditor.com/docs/ckeditor5/latest/installation/frameworks/vuejs-v3.html#integrating-a-build-from-the-online-builder
