### ISSUE TITLE
Refactor ckeditor.js (eslint warning and other).

### ISSUE THREAD

**Issue by ghost** [ckeditor/ckeditor5-react#9]
Because of https://github.com/ckeditor/ckeditor5-react/issues/7 I copied all the code from `ckeditor.js` in my project (in a new component file).

I'm using `create-react-app` and eslint. So the errors:

- [eslint] componentWillReceiveProps is deprecated since React 16.3.0, use UNSAFE_componentWillReceiveProps instead, see https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops (react/no-deprecated)

- [eslint] shouldComponentUpdate should be placed after UNSAFE_componentWillReceiveProps (react/sort-comp)

- [eslint] shouldComponentUpdate should be placed after componentDidMount (react/sort-comp)

- [eslint] render should be placed after _destroyEditor (react/sort-comp)

- [eslint] Default prop types declarations should be sorted alphabetically (react/jsx-sort-default-props)

- [eslint] Must use destructuring props assignment (react/destructuring-assignment)

**What is still a problem** (and I don't know how to fix):

- [eslint] UNSAFE_componentWillReceiveProps is unsafe for use in async rendering, see https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html (react/no-unsafe)

- Unexpected console statement. (no-console) (62, 9)

- JSX props should not use arrow functions (react/jsx-no-bind) (68, 17)

- Prop type `object` is forbidden (react/forbid-prop-types) (74, 3)

- propType "onChange" is not required, but has no corresponding defaultProp declaration. (react/require-default-props) (77, 3)

- propType "onInit" is not required, but has no corresponding defaultProp declaration. (react/require-default-props) (78, 3)

**I opened a PR**: https://github.com/ckeditor/ckeditor5-react/pull/8

**Comment by pomek** [comment]
These issues aren't (on even weren't) valid. I'm using `create-react-app` to reproduce issues reported by the community and linter never shows me any error.
