### ISSUE TITLE
placeholder config dynamic variable

### ISSUE THREAD

**Issue by desaifly** [ckeditor/ckeditor5-react#92]
Hi,

I am trying to pass the placeholder text from a json file and it does not show. Following is a just of the code.

```
let placeHolderConfigValue = { placeholder: Settings ? Settings.DefaultPlaceHolderValue : ''}
<CKEditor ref={localEditor => this.localEditor = localEditor} data={value ? value : null}
config={placeHolderConfigValue }
/>
```
Settings represents the json file.

The following code works:
let placeHolderConfigValue = { placeholder: 'Test Place Holder'}

The difference I get from two diffrent placeHolderConfigValue is as follows:
The First One: {placeholder: "Place Holder from JSON File"}
The Second One: {placeholder: 'Test Place Holder'}

The the difference is " vs '. I did some research on javascript and apparently there is no difference between ' and ". (https://stackoverflow.com/questions/944081/what-is-the-difference-between-and-in-javascript)

What am I missing?

**Comment by Mgsy** [comment]
Hello, I've just created a JSON file with a default placeholder value and successfully loaded it to the editor. Please, make sure that your JSON data is correct and you import the file properly.
