### ISSUE TITLE
Custom new a plugins not working (ckeditor5-react) .

### ISSUE THREAD

**Issue by sunkid1995** [ckeditor/ckeditor5-react#94]
Hi, I am having a problem, when I create a new plugin with (ckeditor5-react)

 ```jsx
import React from 'react';
import propTypes from 'prop-types';

// Constants
import {
  highlightConfigOptions,
  imageConfigOptions,
  toolbarConfigOptions
} from '../../../../constants/CKeditorConfig';

import CKEditor from '@ckeditor/ckeditor5-react';
import ClassicEditor from '@ckeditor/ckeditor5-editor-classic/src/classiceditor';
import EssentialsPlugin from '@ckeditor/ckeditor5-essentials/src/essentials';
import AutoformatPlugin from '@ckeditor/ckeditor5-autoformat/src/autoformat';
import BoldPlugin from '@ckeditor/ckeditor5-basic-styles/src/bold';
import ItalicPlugin from '@ckeditor/ckeditor5-basic-styles/src/italic';
import BlockQuotePlugin from '@ckeditor/ckeditor5-block-quote/src/blockquote';
import HeadingPlugin from '@ckeditor/ckeditor5-heading/src/heading';
import ImagePlugin from '@ckeditor/ckeditor5-image/src/image';
import ImageCaptionPlugin from '@ckeditor/ckeditor5-image/src/imagecaption';
import ImageStylePlugin from '@ckeditor/ckeditor5-image/src/imagestyle';
import ImageToolbarPlugin from '@ckeditor/ckeditor5-image/src/imagetoolbar';
import ImageUploadPlugin from '@ckeditor/ckeditor5-image/src/imageupload';
import LinkPlugin from '@ckeditor/ckeditor5-link/src/link';
import ListPlugin from '@ckeditor/ckeditor5-list/src/list';
import Highlight from '@ckeditor/ckeditor5-highlight/src/highlight';
import Alignment from '@ckeditor/ckeditor5-alignment/src/alignment';

// Component
import CKeditorUploadAdapter from '../../../Adapter/CKeditorUploadAdapter';

const editorConfiguration = {
  plugins: [
    EssentialsPlugin,
    AutoformatPlugin,
    BoldPlugin,
    ItalicPlugin,
    BlockQuotePlugin,
    HeadingPlugin,
    ImagePlugin,
    ImageCaptionPlugin,
    ImageStylePlugin,
    ImageToolbarPlugin,
    ImageUploadPlugin,
    LinkPlugin,
    ListPlugin,
    Highlight,
    Alignment,

    // custom
    InserImage
  ],

  toolbar: toolbarConfigOptions,
  image: imageConfigOptions,
  highlight: highlightConfigOptions,
};

export default class Editor extends React.Component {
  static propTypes = {
    handleChangeContent: propTypes.func.isRequired,
    content: propTypes.string,
  }

  static defaulProps = {
    content: '',
  }

  constructor(props) {
    super(props);
    this.state = {
      content: null,
    };

    this._handleChangeContent = props.handleChangeContent.bind(this);
  }

  UNSAFE_componentWillReceiveProps = nextProps => {
    const { content } = this.props;
    const { content: nextContent } = nextProps;
    if (content !== nextContent) this.setState({ content: nextContent });
  }

  handleChangeContentEditor = (event, editor) => {
    let content = editor.getData();
    this.setState({ content }, () => {
      this._handleChangeContent(content);
    });
  }

  handleOnInit = (editor) => {
    editor.plugins.get('FileRepository').createUploadAdapter = (loader) => {
      return new CKeditorUploadAdapter(loader);
    };
  }

  render () {
    const { content } = this.state;
    return (
      <div>
        <CKEditor
          editor={ClassicEditor}
          config={editorConfiguration}
          data={content || ''}
          onChange={this.handleChangeContentEditor}
          onInit={this.handleOnInit}
        />
        <style jsx>
          {`
            :global(.ck.ck-editor__main>.ck-editor__editable) {
              min-height: 200px !important;
              max-height: 750px !important;
              overflow: auto;
            }

            :global(.ck.ck-content > :last-child) {
              margin-bottom: 5px;
            }

            :global(.ck.ck-content > p:last-of-type) {
              margin-bottom: 5px;
            }
          `}
        </style>
      </div>
    );
  }
}

class InserImage extends Plugin {
  init() {
    console.log('init plugins InserImage');
  }
}
```

<img width="1670" alt="Screen Shot 2019-05-30 at 17 39 46" src="https://user-images.githubusercontent.com/45057159/58628435-df89c780-8303-11e9-9f7d-e6f8068ccd5d.png">

Any feedback here is very meaningful to me, thanks you

**Comment by pomek** [comment]
From the code above, `Plugin` is undefined (missing `import Plugin from '@ckeditor/ckeditor5-core/src/plugin';`)

**Comment by sunkid1995** [comment]
> From the code above, `Plugin` is undefined (missing `import Plugin from '@ckeditor/ckeditor5-core/src/plugin';`)

Thank you, i edit it.
I will notification for you when it success.

**Comment by sunkid1995** [comment]
Thank you, it woked.

**Comment by pomek** [comment]
Sounds good.

**Comment by sunkid1995** [comment]
> Sounds good.

Hello, It work perfect. But i have a question, 
i want add multiple image ? 

` 
import React from 'react';
import _ from 'lodash';
import ReactDOM from 'react-dom';
import { Provider } from 'react-redux';
import { store } from '../../../redux/store';

// custom plugin
import Plugin from '@ckeditor/ckeditor5-core/src/plugin';
import ButtonView from '@ckeditor/ckeditor5-ui/src/button/buttonview';
import imageIcon from '@ckeditor/ckeditor5-core/theme/icons/image.svg';
import CustomInsertImage from '../../Dashboard/posts/createPost/CustomInsertImage';


class InsertImage extends Plugin {
  init() {
    const editor = this.editor;
    let modal = true;

    editor.ui.componentFactory.add('insertImage', locale => {
      const view = new ButtonView( locale );

      view.set({
        label: 'Insert image',
        icon: imageIcon,
        tooltip: true
      });

      view.on('execute', () => {

        const renderElement = () => {
          return (
            <Provider store={store}>
              <CustomInsertImage
                visibleInsertImage={modal}
                toggleModalInsertImage={toggleModalInsertImage}
                handleGetSelectMedia={handleGetSelectMedia}
              />
            </Provider>
          );
        };

        let Modal = React.createElement(renderElement);
        ReactDOM.render(Modal, document.querySelector('#local-editor'));

        function toggleModalInsertImage() {
          ReactDOM.unmountComponentAtNode(document.querySelector('#local-editor'));
        }

        function handleGetSelectMedia(payload) {

          if (payload) {
            const { media } = payload;

            _.each(media, imageUrl => {

              editor.model.change(writer => {
                const imageElement = writer.createElement('image', { src: imageUrl });

                editor.model.insertContent( imageElement, editor.model.document.selection );
              });

            });
          }
        }
      });

      return view;
    });
  }
}

export default InsertImage;
`


how to insert multiple imageUrl ?
` const imageElement = writer.createElement('image', { src: imageUrl }); `
` imageUrl ` -> is array - for example [imageUrl, imageUrl]
Thank you
