### ISSUE TITLE
why i can't get this custom plugin working?

### ISSUE THREAD

**Issue by xwillmadeit** [ckeditor/ckeditor5-react#96]
I followed [this guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#integrating-ckeditor-5-built-from-source) and create a simple insert image plugin but it's not working. Here is my [project](https://github.com/xwillmadeit/editor)，are there something wrong？

Also i want to know can i write a react component as a plugin then insert the result into the editor?

**Comment by Mgsy** [comment]
Hello, your plugin doesn't work, because you didn't import Image plugin, so the editor can't recognize the image element.

Run `npm i --save @ckeditor/ckeditor5-image` and insert following imports to your editor config:
```js
import Image from '@ckeditor/ckeditor5-image/src/image';
import ImageCaption from '@ckeditor/ckeditor5-image/src/imagecaption';
```

After enabling above, everything should work fine.

>Also i want to know can i write a react component as a plugin then insert the result into the editor?

@pomek, is it possible?

**Comment by pomek** [comment]
> @pomek, is it possible?

Yes, it does. @oleq prepared a few months ago a PR (https://github.com/ckeditor/ckeditor5/pull/1706) that shows how to do that. Unfortunately, it still waits for a review.
