### ISSUE TITLE
Option to Turn Off Toolbar Completely

### ISSUE THREAD

**Issue by AustinMutschler** [ckeditor/ckeditor5-react#98]
CKEditor has the ability to turn off all of the plugins inside a toolbar; however, what you are left with is a small empty toolbar box. When trying to turn off the actual toolbar (removePlugins: 'toolbar') I get an error t.map is undefined.

Is there a way to turn off the toolbar based on the configurations? If not, can this be added as a new feature?

**Comment by Mgsy** [comment]
Hello, what kind of editor do you use? In the classic editor, when the toolbar has no items it doesn't show up, see below:

![image](https://user-images.githubusercontent.com/20988892/60008217-f3f78080-9673-11e9-9b24-feb78ba923a4.png)

**Comment by AustinMutschler** [comment]
@Mgsy Sorry, I am using the Inline Editor.

**Comment by Mgsy** [comment]
Thanks for the clarification, I can reproduce it in the inline editor. 

cc @oleq

**Comment by oleq** [comment]
If you want your editor to run without the toolbar, use the [`DecoupledEditor`](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/ui/document-editor.html) instead and don't put the toolbar anywhere (skip the `toolbarContainer.appendChild( editor.ui.view.toolbar.element );` part). Is this what you mean?

**Comment by AustinMutschler** [comment]
@oleq I could do that but I would rather use the inline editor specifically; however, if that isn't possible I will try to switch over to the DecoupledEditor.
