### ISSUE TITLE
IE11 import ckeditor5-build-class syntax error

### ISSUE THREAD

**Issue by Friph** [ckeditor/ckeditor5-react#99]
Hey,
quite nice editor, love it.

But I got a syntax error in IE11 only when I import ckeditor5-build-classic.

`import ClassicEditor from '@ckeditor/ckeditor5-build-classic';`.

![image](https://user-images.githubusercontent.com/31510303/60242925-5be9d900-98b7-11e9-8e50-fac99539c72e.png)
![image](https://user-images.githubusercontent.com/31510303/60242944-6c01b880-98b7-11e9-8303-7324573f7c1a.png)

This destroys the whole app on Internet Explorer, so it's not useable and don't load. 

For me it would be enough if the app is useable and only the CKEditor don't work in IE11.

Do you have any solutions for me?

**Comment by Mgsy** [comment]
Hello, CKEditor 5 isn't compatible with IE11. However, some time ago we made some research and run the editor on this browser (but it's still full of bugs). You can read the discussion [here](https://github.com/ckeditor/ckeditor5/issues/330#issuecomment-485749345).

Right now, for the best experience, please use one of the supported browsers. The list is [here](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/support/browser-compatibility.html).
